// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: config/v2/config_admin_service.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_config_v2_config_admin_service_proto protoreflect.FileDescriptor

const file_config_v2_config_admin_service_proto_rawDesc = "" +
	"\n" +
	"$config/v2/config_admin_service.proto\x12\tconfig.v2\x1a%config/v2/backup_config_request.proto\x1a\x1dconfig/v2/config_backup.proto\x1a\x1fconfig/v2/config_snapshot.proto\x1a%config/v2/export_config_request.proto\x1a*config/v2/get_config_history_request.proto\x1a+config/v2/get_config_history_response.proto\x1a(config/v2/get_config_stats_request.proto\x1a)config/v2/get_config_stats_response.proto\x1a$config/v2/health_check_request.proto\x1a%config/v2/health_check_response.proto\x1a%config/v2/import_config_request.proto\x1a%config/v2/reload_config_request.proto\x1a&config/v2/restore_config_request.proto\x1a'config/v2/rollback_config_request.proto\x1a)config/v2/set_config_schema_request.proto\x1a&config/v2/unwatch_config_request.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a!google/protobuf/go_features.proto2\xf4\x06\n" +
	"\x12ConfigAdminService\x12G\n" +
	"\fBackupConfig\x12\x1e.config.v2.BackupConfigRequest\x1a\x17.config.v2.ConfigBackup\x12H\n" +
	"\rRestoreConfig\x12\x1f.config.v2.RestoreConfigRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\fImportConfig\x12\x1e.config.v2.ImportConfigRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\fExportConfig\x12\x1e.config.v2.ExportConfigRequest\x1a\x19.config.v2.ConfigSnapshot\x12F\n" +
	"\fReloadConfig\x12\x1e.config.v2.ReloadConfigRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0eRollbackConfig\x12 .config.v2.RollbackConfigRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x0fSetConfigSchema\x12!.config.v2.SetConfigSchemaRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\x10GetConfigHistory\x12\".config.v2.GetConfigHistoryRequest\x1a#.config.v2.GetConfigHistoryResponse\x12U\n" +
	"\x0eGetConfigStats\x12 .config.v2.GetConfigStatsRequest\x1a!.config.v2.GetConfigStatsResponse\x12X\n" +
	"\vHealthCheck\x12#.config.v2.ConfigHealthCheckRequest\x1a$.config.v2.ConfigHealthCheckResponse\x12H\n" +
	"\rUnwatchConfig\x12\x1f.config.v2.UnwatchConfigRequest\x1a\x16.google.protobuf.EmptyB-Z#github.com/jdfalk/gcommon/config/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_config_v2_config_admin_service_proto_goTypes = []any{
	(*BackupConfigRequest)(nil),       // 0: config.v2.BackupConfigRequest
	(*RestoreConfigRequest)(nil),      // 1: config.v2.RestoreConfigRequest
	(*ImportConfigRequest)(nil),       // 2: config.v2.ImportConfigRequest
	(*ExportConfigRequest)(nil),       // 3: config.v2.ExportConfigRequest
	(*ReloadConfigRequest)(nil),       // 4: config.v2.ReloadConfigRequest
	(*RollbackConfigRequest)(nil),     // 5: config.v2.RollbackConfigRequest
	(*SetConfigSchemaRequest)(nil),    // 6: config.v2.SetConfigSchemaRequest
	(*GetConfigHistoryRequest)(nil),   // 7: config.v2.GetConfigHistoryRequest
	(*GetConfigStatsRequest)(nil),     // 8: config.v2.GetConfigStatsRequest
	(*ConfigHealthCheckRequest)(nil),  // 9: config.v2.ConfigHealthCheckRequest
	(*UnwatchConfigRequest)(nil),      // 10: config.v2.UnwatchConfigRequest
	(*ConfigBackup)(nil),              // 11: config.v2.ConfigBackup
	(*emptypb.Empty)(nil),             // 12: google.protobuf.Empty
	(*ConfigSnapshot)(nil),            // 13: config.v2.ConfigSnapshot
	(*GetConfigHistoryResponse)(nil),  // 14: config.v2.GetConfigHistoryResponse
	(*GetConfigStatsResponse)(nil),    // 15: config.v2.GetConfigStatsResponse
	(*ConfigHealthCheckResponse)(nil), // 16: config.v2.ConfigHealthCheckResponse
}
var file_config_v2_config_admin_service_proto_depIdxs = []int32{
	0,  // 0: config.v2.ConfigAdminService.BackupConfig:input_type -> config.v2.BackupConfigRequest
	1,  // 1: config.v2.ConfigAdminService.RestoreConfig:input_type -> config.v2.RestoreConfigRequest
	2,  // 2: config.v2.ConfigAdminService.ImportConfig:input_type -> config.v2.ImportConfigRequest
	3,  // 3: config.v2.ConfigAdminService.ExportConfig:input_type -> config.v2.ExportConfigRequest
	4,  // 4: config.v2.ConfigAdminService.ReloadConfig:input_type -> config.v2.ReloadConfigRequest
	5,  // 5: config.v2.ConfigAdminService.RollbackConfig:input_type -> config.v2.RollbackConfigRequest
	6,  // 6: config.v2.ConfigAdminService.SetConfigSchema:input_type -> config.v2.SetConfigSchemaRequest
	7,  // 7: config.v2.ConfigAdminService.GetConfigHistory:input_type -> config.v2.GetConfigHistoryRequest
	8,  // 8: config.v2.ConfigAdminService.GetConfigStats:input_type -> config.v2.GetConfigStatsRequest
	9,  // 9: config.v2.ConfigAdminService.HealthCheck:input_type -> config.v2.ConfigHealthCheckRequest
	10, // 10: config.v2.ConfigAdminService.UnwatchConfig:input_type -> config.v2.UnwatchConfigRequest
	11, // 11: config.v2.ConfigAdminService.BackupConfig:output_type -> config.v2.ConfigBackup
	12, // 12: config.v2.ConfigAdminService.RestoreConfig:output_type -> google.protobuf.Empty
	12, // 13: config.v2.ConfigAdminService.ImportConfig:output_type -> google.protobuf.Empty
	13, // 14: config.v2.ConfigAdminService.ExportConfig:output_type -> config.v2.ConfigSnapshot
	12, // 15: config.v2.ConfigAdminService.ReloadConfig:output_type -> google.protobuf.Empty
	12, // 16: config.v2.ConfigAdminService.RollbackConfig:output_type -> google.protobuf.Empty
	12, // 17: config.v2.ConfigAdminService.SetConfigSchema:output_type -> google.protobuf.Empty
	14, // 18: config.v2.ConfigAdminService.GetConfigHistory:output_type -> config.v2.GetConfigHistoryResponse
	15, // 19: config.v2.ConfigAdminService.GetConfigStats:output_type -> config.v2.GetConfigStatsResponse
	16, // 20: config.v2.ConfigAdminService.HealthCheck:output_type -> config.v2.ConfigHealthCheckResponse
	12, // 21: config.v2.ConfigAdminService.UnwatchConfig:output_type -> google.protobuf.Empty
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_config_v2_config_admin_service_proto_init() }
func file_config_v2_config_admin_service_proto_init() {
	if File_config_v2_config_admin_service_proto != nil {
		return
	}
	file_config_v2_backup_config_request_proto_init()
	file_config_v2_config_backup_proto_init()
	file_config_v2_config_snapshot_proto_init()
	file_config_v2_export_config_request_proto_init()
	file_config_v2_get_config_history_request_proto_init()
	file_config_v2_get_config_history_response_proto_init()
	file_config_v2_get_config_stats_request_proto_init()
	file_config_v2_get_config_stats_response_proto_init()
	file_config_v2_health_check_request_proto_init()
	file_config_v2_health_check_response_proto_init()
	file_config_v2_import_config_request_proto_init()
	file_config_v2_reload_config_request_proto_init()
	file_config_v2_restore_config_request_proto_init()
	file_config_v2_rollback_config_request_proto_init()
	file_config_v2_set_config_schema_request_proto_init()
	file_config_v2_unwatch_config_request_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v2_config_admin_service_proto_rawDesc), len(file_config_v2_config_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_config_v2_config_admin_service_proto_goTypes,
		DependencyIndexes: file_config_v2_config_admin_service_proto_depIdxs,
	}.Build()
	File_config_v2_config_admin_service_proto = out.File
	file_config_v2_config_admin_service_proto_goTypes = nil
	file_config_v2_config_admin_service_proto_depIdxs = nil
}
