// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: config/v2/retention_policy.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConfigRetentionPolicy struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled              bool                   `protobuf:"varint,1,opt,name=enabled"`
	xxx_hidden_ConfigRetentionDays  int32                  `protobuf:"varint,2,opt,name=config_retention_days,json=configRetentionDays"`
	xxx_hidden_AuditRetentionDays   int32                  `protobuf:"varint,3,opt,name=audit_retention_days,json=auditRetentionDays"`
	xxx_hidden_BackupRetentionDays  int32                  `protobuf:"varint,4,opt,name=backup_retention_days,json=backupRetentionDays"`
	xxx_hidden_MetricsRetentionDays int32                  `protobuf:"varint,5,opt,name=metrics_retention_days,json=metricsRetentionDays"`
	xxx_hidden_CustomRetention      map[string]int32       `protobuf:"bytes,6,rep,name=custom_retention,json=customRetention" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *ConfigRetentionPolicy) Reset() {
	*x = ConfigRetentionPolicy{}
	mi := &file_config_v2_retention_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigRetentionPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigRetentionPolicy) ProtoMessage() {}

func (x *ConfigRetentionPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_retention_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigRetentionPolicy) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *ConfigRetentionPolicy) GetConfigRetentionDays() int32 {
	if x != nil {
		return x.xxx_hidden_ConfigRetentionDays
	}
	return 0
}

func (x *ConfigRetentionPolicy) GetAuditRetentionDays() int32 {
	if x != nil {
		return x.xxx_hidden_AuditRetentionDays
	}
	return 0
}

func (x *ConfigRetentionPolicy) GetBackupRetentionDays() int32 {
	if x != nil {
		return x.xxx_hidden_BackupRetentionDays
	}
	return 0
}

func (x *ConfigRetentionPolicy) GetMetricsRetentionDays() int32 {
	if x != nil {
		return x.xxx_hidden_MetricsRetentionDays
	}
	return 0
}

func (x *ConfigRetentionPolicy) GetCustomRetention() map[string]int32 {
	if x != nil {
		return x.xxx_hidden_CustomRetention
	}
	return nil
}

func (x *ConfigRetentionPolicy) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *ConfigRetentionPolicy) SetConfigRetentionDays(v int32) {
	x.xxx_hidden_ConfigRetentionDays = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *ConfigRetentionPolicy) SetAuditRetentionDays(v int32) {
	x.xxx_hidden_AuditRetentionDays = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *ConfigRetentionPolicy) SetBackupRetentionDays(v int32) {
	x.xxx_hidden_BackupRetentionDays = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *ConfigRetentionPolicy) SetMetricsRetentionDays(v int32) {
	x.xxx_hidden_MetricsRetentionDays = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *ConfigRetentionPolicy) SetCustomRetention(v map[string]int32) {
	x.xxx_hidden_CustomRetention = v
}

func (x *ConfigRetentionPolicy) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConfigRetentionPolicy) HasConfigRetentionDays() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConfigRetentionPolicy) HasAuditRetentionDays() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ConfigRetentionPolicy) HasBackupRetentionDays() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ConfigRetentionPolicy) HasMetricsRetentionDays() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ConfigRetentionPolicy) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Enabled = false
}

func (x *ConfigRetentionPolicy) ClearConfigRetentionDays() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ConfigRetentionDays = 0
}

func (x *ConfigRetentionPolicy) ClearAuditRetentionDays() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_AuditRetentionDays = 0
}

func (x *ConfigRetentionPolicy) ClearBackupRetentionDays() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_BackupRetentionDays = 0
}

func (x *ConfigRetentionPolicy) ClearMetricsRetentionDays() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_MetricsRetentionDays = 0
}

type ConfigRetentionPolicy_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Retention enabled
	Enabled *bool
	// Configuration retention
	ConfigRetentionDays *int32
	// Audit log retention
	AuditRetentionDays *int32
	// Backup retention
	BackupRetentionDays *int32
	// Metrics retention
	MetricsRetentionDays *int32
	// Custom retention policies
	CustomRetention map[string]int32
}

func (b0 ConfigRetentionPolicy_builder) Build() *ConfigRetentionPolicy {
	m0 := &ConfigRetentionPolicy{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.ConfigRetentionDays != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_ConfigRetentionDays = *b.ConfigRetentionDays
	}
	if b.AuditRetentionDays != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_AuditRetentionDays = *b.AuditRetentionDays
	}
	if b.BackupRetentionDays != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_BackupRetentionDays = *b.BackupRetentionDays
	}
	if b.MetricsRetentionDays != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_MetricsRetentionDays = *b.MetricsRetentionDays
	}
	x.xxx_hidden_CustomRetention = b.CustomRetention
	return m0
}

var File_config_v2_retention_policy_proto protoreflect.FileDescriptor

const file_config_v2_retention_policy_proto_rawDesc = "" +
	"\n" +
	" config/v2/retention_policy.proto\x12\tconfig.v2\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xcb\x03\n" +
	"\x15ConfigRetentionPolicy\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12;\n" +
	"\x15config_retention_days\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x13configRetentionDays\x129\n" +
	"\x14audit_retention_days\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x12auditRetentionDays\x12;\n" +
	"\x15backup_retention_days\x18\x04 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x13backupRetentionDays\x12=\n" +
	"\x16metrics_retention_days\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x14metricsRetentionDays\x12`\n" +
	"\x10custom_retention\x18\x06 \x03(\v25.config.v2.ConfigRetentionPolicy.CustomRetentionEntryR\x0fcustomRetention\x1aB\n" +
	"\x14CustomRetentionEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01B-Z#github.com/jdfalk/gcommon/config/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_config_v2_retention_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_v2_retention_policy_proto_goTypes = []any{
	(*ConfigRetentionPolicy)(nil), // 0: config.v2.ConfigRetentionPolicy
	nil,                           // 1: config.v2.ConfigRetentionPolicy.CustomRetentionEntry
}
var file_config_v2_retention_policy_proto_depIdxs = []int32{
	1, // 0: config.v2.ConfigRetentionPolicy.custom_retention:type_name -> config.v2.ConfigRetentionPolicy.CustomRetentionEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_config_v2_retention_policy_proto_init() }
func file_config_v2_retention_policy_proto_init() {
	if File_config_v2_retention_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v2_retention_policy_proto_rawDesc), len(file_config_v2_retention_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_v2_retention_policy_proto_goTypes,
		DependencyIndexes: file_config_v2_retention_policy_proto_depIdxs,
		MessageInfos:      file_config_v2_retention_policy_proto_msgTypes,
	}.Build()
	File_config_v2_retention_policy_proto = out.File
	file_config_v2_retention_policy_proto_goTypes = nil
	file_config_v2_retention_policy_proto_depIdxs = nil
}
