// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: config/v2/validation_settings.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v2 "github.com/jdfalk/gcommon/common/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidationSettings struct {
	state                       protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Enabled          bool                    `protobuf:"varint,1,opt,name=enabled"`
	xxx_hidden_Rules            *[]*ValidationRule      `protobuf:"bytes,2,rep,name=rules"`
	xxx_hidden_ValidateOnChange bool                    `protobuf:"varint,3,opt,name=validate_on_change,json=validateOnChange"`
	xxx_hidden_ValidateOnAccess bool                    `protobuf:"varint,4,opt,name=validate_on_access,json=validateOnAccess"`
	xxx_hidden_TimeoutSeconds   int32                   `protobuf:"varint,5,opt,name=timeout_seconds,json=timeoutSeconds"`
	xxx_hidden_Retry            *v2.ConfigRetrySettings `protobuf:"bytes,6,opt,name=retry"`
	xxx_hidden_Metadata         map[string]string       `protobuf:"bytes,7,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ValidationSettings) Reset() {
	*x = ValidationSettings{}
	mi := &file_config_v2_validation_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationSettings) ProtoMessage() {}

func (x *ValidationSettings) ProtoReflect() protoreflect.Message {
	mi := &file_config_v2_validation_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValidationSettings) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *ValidationSettings) GetRules() []*ValidationRule {
	if x != nil {
		if x.xxx_hidden_Rules != nil {
			return *x.xxx_hidden_Rules
		}
	}
	return nil
}

func (x *ValidationSettings) GetValidateOnChange() bool {
	if x != nil {
		return x.xxx_hidden_ValidateOnChange
	}
	return false
}

func (x *ValidationSettings) GetValidateOnAccess() bool {
	if x != nil {
		return x.xxx_hidden_ValidateOnAccess
	}
	return false
}

func (x *ValidationSettings) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.xxx_hidden_TimeoutSeconds
	}
	return 0
}

func (x *ValidationSettings) GetRetry() *v2.ConfigRetrySettings {
	if x != nil {
		return x.xxx_hidden_Retry
	}
	return nil
}

func (x *ValidationSettings) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ValidationSettings) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *ValidationSettings) SetRules(v []*ValidationRule) {
	x.xxx_hidden_Rules = &v
}

func (x *ValidationSettings) SetValidateOnChange(v bool) {
	x.xxx_hidden_ValidateOnChange = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *ValidationSettings) SetValidateOnAccess(v bool) {
	x.xxx_hidden_ValidateOnAccess = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *ValidationSettings) SetTimeoutSeconds(v int32) {
	x.xxx_hidden_TimeoutSeconds = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *ValidationSettings) SetRetry(v *v2.ConfigRetrySettings) {
	x.xxx_hidden_Retry = v
}

func (x *ValidationSettings) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *ValidationSettings) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ValidationSettings) HasValidateOnChange() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ValidationSettings) HasValidateOnAccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ValidationSettings) HasTimeoutSeconds() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ValidationSettings) HasRetry() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Retry != nil
}

func (x *ValidationSettings) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Enabled = false
}

func (x *ValidationSettings) ClearValidateOnChange() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ValidateOnChange = false
}

func (x *ValidationSettings) ClearValidateOnAccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ValidateOnAccess = false
}

func (x *ValidationSettings) ClearTimeoutSeconds() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_TimeoutSeconds = 0
}

func (x *ValidationSettings) ClearRetry() {
	x.xxx_hidden_Retry = nil
}

type ValidationSettings_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether validation is enabled
	Enabled *bool
	// Validation rules (using ValidationRule from config_template.proto)
	Rules []*ValidationRule
	// Validation on change
	ValidateOnChange *bool
	// Validation on access
	ValidateOnAccess *bool
	// Validation timeout in seconds
	TimeoutSeconds *int32
	// Validation retry settings
	Retry *v2.ConfigRetrySettings
	// Validation metadata
	Metadata map[string]string
}

func (b0 ValidationSettings_builder) Build() *ValidationSettings {
	m0 := &ValidationSettings{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	x.xxx_hidden_Rules = &b.Rules
	if b.ValidateOnChange != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_ValidateOnChange = *b.ValidateOnChange
	}
	if b.ValidateOnAccess != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_ValidateOnAccess = *b.ValidateOnAccess
	}
	if b.TimeoutSeconds != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_TimeoutSeconds = *b.TimeoutSeconds
	}
	x.xxx_hidden_Retry = b.Retry
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

var File_config_v2_validation_settings_proto protoreflect.FileDescriptor

const file_config_v2_validation_settings_proto_rawDesc = "" +
	"\n" +
	"#config/v2/validation_settings.proto\x12\tconfig.v2\x1a%common/v2/config_retry_settings.proto\x1a\x1fconfig/v2/validation_rule.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xb3\x03\n" +
	"\x12ValidationSettings\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x129\n" +
	"\x05rules\x18\x02 \x03(\v2\x19.config.v2.ValidationRuleB\b\xbaH\x05\x92\x01\x02\b\x01R\x05rules\x12,\n" +
	"\x12validate_on_change\x18\x03 \x01(\bR\x10validateOnChange\x12,\n" +
	"\x12validate_on_access\x18\x04 \x01(\bR\x10validateOnAccess\x120\n" +
	"\x0ftimeout_seconds\x18\x05 \x01(\x05B\a\xbaH\x04\x1a\x02 \x00R\x0etimeoutSeconds\x124\n" +
	"\x05retry\x18\x06 \x01(\v2\x1e.common.v2.ConfigRetrySettingsR\x05retry\x12G\n" +
	"\bmetadata\x18\a \x03(\v2+.config.v2.ValidationSettings.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B-Z#github.com/jdfalk/gcommon/config/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_config_v2_validation_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_config_v2_validation_settings_proto_goTypes = []any{
	(*ValidationSettings)(nil),     // 0: config.v2.ValidationSettings
	nil,                            // 1: config.v2.ValidationSettings.MetadataEntry
	(*ValidationRule)(nil),         // 2: config.v2.ValidationRule
	(*v2.ConfigRetrySettings)(nil), // 3: common.v2.ConfigRetrySettings
}
var file_config_v2_validation_settings_proto_depIdxs = []int32{
	2, // 0: config.v2.ValidationSettings.rules:type_name -> config.v2.ValidationRule
	3, // 1: config.v2.ValidationSettings.retry:type_name -> common.v2.ConfigRetrySettings
	1, // 2: config.v2.ValidationSettings.metadata:type_name -> config.v2.ValidationSettings.MetadataEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_config_v2_validation_settings_proto_init() }
func file_config_v2_validation_settings_proto_init() {
	if File_config_v2_validation_settings_proto != nil {
		return
	}
	file_config_v2_validation_rule_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v2_validation_settings_proto_rawDesc), len(file_config_v2_validation_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_v2_validation_settings_proto_goTypes,
		DependencyIndexes: file_config_v2_validation_settings_proto_depIdxs,
		MessageInfos:      file_config_v2_validation_settings_proto_msgTypes,
	}.Build()
	File_config_v2_validation_settings_proto = out.File
	file_config_v2_validation_settings_proto_goTypes = nil
	file_config_v2_validation_settings_proto_depIdxs = nil
}
