// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: queuepb/v2/queue_stats_point.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueStatsPoint struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp"`
	xxx_hidden_Stats     *QueueStats            `protobuf:"bytes,2,opt,name=stats"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *QueueStatsPoint) Reset() {
	*x = QueueStatsPoint{}
	mi := &file_queuepb_v2_queue_stats_point_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatsPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatsPoint) ProtoMessage() {}

func (x *QueueStatsPoint) ProtoReflect() protoreflect.Message {
	mi := &file_queuepb_v2_queue_stats_point_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueueStatsPoint) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Timestamp
	}
	return nil
}

func (x *QueueStatsPoint) GetStats() *QueueStats {
	if x != nil {
		return x.xxx_hidden_Stats
	}
	return nil
}

func (x *QueueStatsPoint) SetTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_Timestamp = v
}

func (x *QueueStatsPoint) SetStats(v *QueueStats) {
	x.xxx_hidden_Stats = v
}

func (x *QueueStatsPoint) HasTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Timestamp != nil
}

func (x *QueueStatsPoint) HasStats() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Stats != nil
}

func (x *QueueStatsPoint) ClearTimestamp() {
	x.xxx_hidden_Timestamp = nil
}

func (x *QueueStatsPoint) ClearStats() {
	x.xxx_hidden_Stats = nil
}

type QueueStatsPoint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Timestamp for this data point
	Timestamp *timestamppb.Timestamp
	// Statistics at this point in time
	Stats *QueueStats
}

func (b0 QueueStatsPoint_builder) Build() *QueueStatsPoint {
	m0 := &QueueStatsPoint{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Timestamp = b.Timestamp
	x.xxx_hidden_Stats = b.Stats
	return m0
}

var File_queuepb_v2_queue_stats_point_proto protoreflect.FileDescriptor

const file_queuepb_v2_queue_stats_point_proto_rawDesc = "" +
	"\n" +
	"\"queuepb/v2/queue_stats_point.proto\x12\bqueue.v2\x1a\x1cqueuepb/v2/queue_stats.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"w\n" +
	"\x0fQueueStatsPoint\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12*\n" +
	"\x05stats\x18\x02 \x01(\v2\x14.queue.v2.QueueStatsR\x05statsB\x97\x01\n" +
	"\fcom.queue.v2B\x14QueueStatsPointProtoP\x01Z(github.com/jdfalk/gcommon/pkg/queuepb/v2\xa2\x02\x03QXX\xaa\x02\bQueue.V2\xca\x02\bQueue\\V2\xe2\x02\x14Queue\\V2\\GPBMetadata\xea\x02\tQueue::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_queuepb_v2_queue_stats_point_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_queuepb_v2_queue_stats_point_proto_goTypes = []any{
	(*QueueStatsPoint)(nil),       // 0: queue.v2.QueueStatsPoint
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
	(*QueueStats)(nil),            // 2: queue.v2.QueueStats
}
var file_queuepb_v2_queue_stats_point_proto_depIdxs = []int32{
	1, // 0: queue.v2.QueueStatsPoint.timestamp:type_name -> google.protobuf.Timestamp
	2, // 1: queue.v2.QueueStatsPoint.stats:type_name -> queue.v2.QueueStats
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_queuepb_v2_queue_stats_point_proto_init() }
func file_queuepb_v2_queue_stats_point_proto_init() {
	if File_queuepb_v2_queue_stats_point_proto != nil {
		return
	}
	file_queuepb_v2_queue_stats_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queuepb_v2_queue_stats_point_proto_rawDesc), len(file_queuepb_v2_queue_stats_point_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_queuepb_v2_queue_stats_point_proto_goTypes,
		DependencyIndexes: file_queuepb_v2_queue_stats_point_proto_depIdxs,
		MessageInfos:      file_queuepb_v2_queue_stats_point_proto_msgTypes,
	}.Build()
	File_queuepb_v2_queue_stats_point_proto = out.File
	file_queuepb_v2_queue_stats_point_proto_goTypes = nil
	file_queuepb_v2_queue_stats_point_proto_depIdxs = nil
}
