// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: queuepb/v2/workflow_service.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_queuepb_v2_workflow_service_proto protoreflect.FileDescriptor

const file_queuepb_v2_workflow_service_proto_rawDesc = "" +
	"\n" +
	"!queuepb/v2/workflow_service.proto\x12\bqueue.v2\x1a'queuepb/v2/start_workflow_request.proto\x1a(queuepb/v2/start_workflow_response.proto\x1a&queuepb/v2/stop_workflow_request.proto\x1a'queuepb/v2/stop_workflow_response.proto\x1a!google/protobuf/go_features.proto2\xb2\x01\n" +
	"\x0fWorkflowService\x12P\n" +
	"\rStartWorkflow\x12\x1e.queue.v2.StartWorkflowRequest\x1a\x1f.queue.v2.StartWorkflowResponse\x12M\n" +
	"\fStopWorkflow\x12\x1d.queue.v2.StopWorkflowRequest\x1a\x1e.queue.v2.StopWorkflowResponseB\x97\x01\n" +
	"\fcom.queue.v2B\x14WorkflowServiceProtoP\x01Z(github.com/jdfalk/gcommon/pkg/queuepb/v2\xa2\x02\x03QXX\xaa\x02\bQueue.V2\xca\x02\bQueue\\V2\xe2\x02\x14Queue\\V2\\GPBMetadata\xea\x02\tQueue::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_queuepb_v2_workflow_service_proto_goTypes = []any{
	(*StartWorkflowRequest)(nil),  // 0: queue.v2.StartWorkflowRequest
	(*StopWorkflowRequest)(nil),   // 1: queue.v2.StopWorkflowRequest
	(*StartWorkflowResponse)(nil), // 2: queue.v2.StartWorkflowResponse
	(*StopWorkflowResponse)(nil),  // 3: queue.v2.StopWorkflowResponse
}
var file_queuepb_v2_workflow_service_proto_depIdxs = []int32{
	0, // 0: queue.v2.WorkflowService.StartWorkflow:input_type -> queue.v2.StartWorkflowRequest
	1, // 1: queue.v2.WorkflowService.StopWorkflow:input_type -> queue.v2.StopWorkflowRequest
	2, // 2: queue.v2.WorkflowService.StartWorkflow:output_type -> queue.v2.StartWorkflowResponse
	3, // 3: queue.v2.WorkflowService.StopWorkflow:output_type -> queue.v2.StopWorkflowResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_queuepb_v2_workflow_service_proto_init() }
func file_queuepb_v2_workflow_service_proto_init() {
	if File_queuepb_v2_workflow_service_proto != nil {
		return
	}
	file_queuepb_v2_start_workflow_request_proto_init()
	file_queuepb_v2_start_workflow_response_proto_init()
	file_queuepb_v2_stop_workflow_request_proto_init()
	file_queuepb_v2_stop_workflow_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queuepb_v2_workflow_service_proto_rawDesc), len(file_queuepb_v2_workflow_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queuepb_v2_workflow_service_proto_goTypes,
		DependencyIndexes: file_queuepb_v2_workflow_service_proto_depIdxs,
	}.Build()
	File_queuepb_v2_workflow_service_proto = out.File
	file_queuepb_v2_workflow_service_proto_goTypes = nil
	file_queuepb_v2_workflow_service_proto_depIdxs = nil
}
