// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: database/v1/cache_admin_service.proto

package database

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_database_v1_cache_admin_service_proto protoreflect.FileDescriptor

const file_database_v1_cache_admin_service_proto_rawDesc = "" +
	"\n" +
	"%database/v1/cache_admin_service.proto\x12\vdatabase.v1\x1a*database/v1/configure_policy_request.proto\x1a+database/v1/configure_policy_response.proto\x1a*database/v1/create_namespace_request.proto\x1a+database/v1/create_namespace_response.proto\x1a*database/v1/delete_namespace_request.proto\x1a-database/v1/get_namespace_stats_request.proto\x1a.database/v1/get_namespace_stats_response.proto\x1a)database/v1/list_namespaces_request.proto\x1a*database/v1/list_namespaces_response.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a!google/protobuf/go_features.proto2\xde\x03\n" +
	"\x11CacheAdminService\x12\\\n" +
	"\x0fCreateNamespace\x12#.database.v1.CreateNamespaceRequest\x1a$.database.v1.CreateNamespaceResponse\x12N\n" +
	"\x0fDeleteNamespace\x12#.database.v1.DeleteNamespaceRequest\x1a\x16.google.protobuf.Empty\x12Y\n" +
	"\x0eListNamespaces\x12\".database.v1.ListNamespacesRequest\x1a#.database.v1.ListNamespacesResponse\x12b\n" +
	"\x11GetNamespaceStats\x12%.database.v1.GetNamespaceStatsRequest\x1a&.database.v1.GetNamespaceStatsResponse\x12\\\n" +
	"\x0fConfigurePolicy\x12#.database.v1.ConfigurePolicyRequest\x1a$.database.v1.ConfigurePolicyResponseB1Z'github.com/jdfalk/gcommon/pkg/database/\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_database_v1_cache_admin_service_proto_goTypes = []any{
	(*CreateNamespaceRequest)(nil),    // 0: database.v1.CreateNamespaceRequest
	(*DeleteNamespaceRequest)(nil),    // 1: database.v1.DeleteNamespaceRequest
	(*ListNamespacesRequest)(nil),     // 2: database.v1.ListNamespacesRequest
	(*GetNamespaceStatsRequest)(nil),  // 3: database.v1.GetNamespaceStatsRequest
	(*ConfigurePolicyRequest)(nil),    // 4: database.v1.ConfigurePolicyRequest
	(*CreateNamespaceResponse)(nil),   // 5: database.v1.CreateNamespaceResponse
	(*emptypb.Empty)(nil),             // 6: google.protobuf.Empty
	(*ListNamespacesResponse)(nil),    // 7: database.v1.ListNamespacesResponse
	(*GetNamespaceStatsResponse)(nil), // 8: database.v1.GetNamespaceStatsResponse
	(*ConfigurePolicyResponse)(nil),   // 9: database.v1.ConfigurePolicyResponse
}
var file_database_v1_cache_admin_service_proto_depIdxs = []int32{
	0, // 0: database.v1.CacheAdminService.CreateNamespace:input_type -> database.v1.CreateNamespaceRequest
	1, // 1: database.v1.CacheAdminService.DeleteNamespace:input_type -> database.v1.DeleteNamespaceRequest
	2, // 2: database.v1.CacheAdminService.ListNamespaces:input_type -> database.v1.ListNamespacesRequest
	3, // 3: database.v1.CacheAdminService.GetNamespaceStats:input_type -> database.v1.GetNamespaceStatsRequest
	4, // 4: database.v1.CacheAdminService.ConfigurePolicy:input_type -> database.v1.ConfigurePolicyRequest
	5, // 5: database.v1.CacheAdminService.CreateNamespace:output_type -> database.v1.CreateNamespaceResponse
	6, // 6: database.v1.CacheAdminService.DeleteNamespace:output_type -> google.protobuf.Empty
	7, // 7: database.v1.CacheAdminService.ListNamespaces:output_type -> database.v1.ListNamespacesResponse
	8, // 8: database.v1.CacheAdminService.GetNamespaceStats:output_type -> database.v1.GetNamespaceStatsResponse
	9, // 9: database.v1.CacheAdminService.ConfigurePolicy:output_type -> database.v1.ConfigurePolicyResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_database_v1_cache_admin_service_proto_init() }
func file_database_v1_cache_admin_service_proto_init() {
	if File_database_v1_cache_admin_service_proto != nil {
		return
	}
	file_database_v1_configure_policy_request_proto_init()
	file_database_v1_configure_policy_response_proto_init()
	file_database_v1_create_namespace_request_proto_init()
	file_database_v1_create_namespace_response_proto_init()
	file_database_v1_delete_namespace_request_proto_init()
	file_database_v1_get_namespace_stats_request_proto_init()
	file_database_v1_get_namespace_stats_response_proto_init()
	file_database_v1_list_namespaces_request_proto_init()
	file_database_v1_list_namespaces_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_v1_cache_admin_service_proto_rawDesc), len(file_database_v1_cache_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_database_v1_cache_admin_service_proto_goTypes,
		DependencyIndexes: file_database_v1_cache_admin_service_proto_depIdxs,
	}.Build()
	File_database_v1_cache_admin_service_proto = out.File
	file_database_v1_cache_admin_service_proto_goTypes = nil
	file_database_v1_cache_admin_service_proto_depIdxs = nil
}
