// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: database/v1/migration_service.proto

package database

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_database_v1_migration_service_proto protoreflect.FileDescriptor

const file_database_v1_migration_service_proto_rawDesc = "" +
	"\n" +
	"#database/v1/migration_service.proto\x12\vdatabase.v1\x1a.database/v1/get_migration_status_request.proto\x1a/database/v1/get_migration_status_response.proto\x1a)database/v1/list_migrations_request.proto\x1a*database/v1/list_migrations_response.proto\x1a*database/v1/revert_migration_request.proto\x1a+database/v1/revert_migration_response.proto\x1a'database/v1/run_migration_request.proto\x1a(database/v1/run_migration_response.proto\x1a!google/protobuf/go_features.proto2\x89\x03\n" +
	"\x10MigrationService\x12U\n" +
	"\x0eApplyMigration\x12 .database.v1.RunMigrationRequest\x1a!.database.v1.RunMigrationResponse\x12\\\n" +
	"\x0fRevertMigration\x12#.database.v1.RevertMigrationRequest\x1a$.database.v1.RevertMigrationResponse\x12e\n" +
	"\x12GetMigrationStatus\x12&.database.v1.GetMigrationStatusRequest\x1a'.database.v1.GetMigrationStatusResponse\x12Y\n" +
	"\x0eListMigrations\x12\".database.v1.ListMigrationsRequest\x1a#.database.v1.ListMigrationsResponseB0Z&github.com/jdfalk/gcommon/pkg/database\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_database_v1_migration_service_proto_goTypes = []any{
	(*RunMigrationRequest)(nil),        // 0: database.v1.RunMigrationRequest
	(*RevertMigrationRequest)(nil),     // 1: database.v1.RevertMigrationRequest
	(*GetMigrationStatusRequest)(nil),  // 2: database.v1.GetMigrationStatusRequest
	(*ListMigrationsRequest)(nil),      // 3: database.v1.ListMigrationsRequest
	(*RunMigrationResponse)(nil),       // 4: database.v1.RunMigrationResponse
	(*RevertMigrationResponse)(nil),    // 5: database.v1.RevertMigrationResponse
	(*GetMigrationStatusResponse)(nil), // 6: database.v1.GetMigrationStatusResponse
	(*ListMigrationsResponse)(nil),     // 7: database.v1.ListMigrationsResponse
}
var file_database_v1_migration_service_proto_depIdxs = []int32{
	0, // 0: database.v1.MigrationService.ApplyMigration:input_type -> database.v1.RunMigrationRequest
	1, // 1: database.v1.MigrationService.RevertMigration:input_type -> database.v1.RevertMigrationRequest
	2, // 2: database.v1.MigrationService.GetMigrationStatus:input_type -> database.v1.GetMigrationStatusRequest
	3, // 3: database.v1.MigrationService.ListMigrations:input_type -> database.v1.ListMigrationsRequest
	4, // 4: database.v1.MigrationService.ApplyMigration:output_type -> database.v1.RunMigrationResponse
	5, // 5: database.v1.MigrationService.RevertMigration:output_type -> database.v1.RevertMigrationResponse
	6, // 6: database.v1.MigrationService.GetMigrationStatus:output_type -> database.v1.GetMigrationStatusResponse
	7, // 7: database.v1.MigrationService.ListMigrations:output_type -> database.v1.ListMigrationsResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_database_v1_migration_service_proto_init() }
func file_database_v1_migration_service_proto_init() {
	if File_database_v1_migration_service_proto != nil {
		return
	}
	file_database_v1_get_migration_status_request_proto_init()
	file_database_v1_get_migration_status_response_proto_init()
	file_database_v1_list_migrations_request_proto_init()
	file_database_v1_list_migrations_response_proto_init()
	file_database_v1_revert_migration_request_proto_init()
	file_database_v1_revert_migration_response_proto_init()
	file_database_v1_run_migration_request_proto_init()
	file_database_v1_run_migration_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_database_v1_migration_service_proto_rawDesc), len(file_database_v1_migration_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_database_v1_migration_service_proto_goTypes,
		DependencyIndexes: file_database_v1_migration_service_proto_depIdxs,
	}.Build()
	File_database_v1_migration_service_proto = out.File
	file_database_v1_migration_service_proto_goTypes = nil
	file_database_v1_migration_service_proto_depIdxs = nil
}
