// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: commonpb/v1/list_notifications_request.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Request to list previously sent notifications.
type ListNotificationsRequest struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pagination *Pagination            `protobuf:"bytes,1,opt,name=pagination"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_commonpb_v1_list_notifications_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_commonpb_v1_list_notifications_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListNotificationsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.xxx_hidden_Pagination
	}
	return nil
}

func (x *ListNotificationsRequest) SetPagination(v *Pagination) {
	x.xxx_hidden_Pagination = v
}

func (x *ListNotificationsRequest) HasPagination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pagination != nil
}

func (x *ListNotificationsRequest) ClearPagination() {
	x.xxx_hidden_Pagination = nil
}

type ListNotificationsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Pagination information for result set.
	Pagination *Pagination
}

func (b0 ListNotificationsRequest_builder) Build() *ListNotificationsRequest {
	m0 := &ListNotificationsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Pagination = b.Pagination
	return m0
}

var File_commonpb_v1_list_notifications_request_proto protoreflect.FileDescriptor

const file_commonpb_v1_list_notifications_request_proto_rawDesc = "" +
	"\n" +
	",commonpb/v1/list_notifications_request.proto\x12\tcommon.v1\x1a\x1ccommonpb/v1/pagination.proto\x1a!google/protobuf/go_features.proto\"Q\n" +
	"\x18ListNotificationsRequest\x125\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x15.common.v1.PaginationR\n" +
	"paginationB\xa3\x01\n" +
	"\rcom.common.v1B\x1dListNotificationsRequestProtoP\x01Z&github.com/jdfalk/gcommon/pkg/commonpb\xa2\x02\x03CXX\xaa\x02\tCommon.V1\xca\x02\tCommon\\V1\xe2\x02\x15Common\\V1\\GPBMetadata\xea\x02\n" +
	"Common::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_commonpb_v1_list_notifications_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commonpb_v1_list_notifications_request_proto_goTypes = []any{
	(*ListNotificationsRequest)(nil), // 0: common.v1.ListNotificationsRequest
	(*Pagination)(nil),               // 1: common.v1.Pagination
}
var file_commonpb_v1_list_notifications_request_proto_depIdxs = []int32{
	1, // 0: common.v1.ListNotificationsRequest.pagination:type_name -> common.v1.Pagination
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_commonpb_v1_list_notifications_request_proto_init() }
func file_commonpb_v1_list_notifications_request_proto_init() {
	if File_commonpb_v1_list_notifications_request_proto != nil {
		return
	}
	file_commonpb_v1_pagination_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonpb_v1_list_notifications_request_proto_rawDesc), len(file_commonpb_v1_list_notifications_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commonpb_v1_list_notifications_request_proto_goTypes,
		DependencyIndexes: file_commonpb_v1_list_notifications_request_proto_depIdxs,
		MessageInfos:      file_commonpb_v1_list_notifications_request_proto_msgTypes,
	}.Build()
	File_commonpb_v1_list_notifications_request_proto = out.File
	file_commonpb_v1_list_notifications_request_proto_goTypes = nil
	file_commonpb_v1_list_notifications_request_proto_depIdxs = nil
}
