// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: commonpb/v1/rebalance_strategy.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RebalanceStrategy int32

const (
	RebalanceStrategy_REBALANCE_STRATEGY_UNSPECIFIED RebalanceStrategy = 0
	RebalanceStrategy_REBALANCE_STRATEGY_EAGER       RebalanceStrategy = 1 // Stop all consumers, then reassign
	RebalanceStrategy_REBALANCE_STRATEGY_COOPERATIVE RebalanceStrategy = 2 // Incremental cooperative rebalancing
	RebalanceStrategy_REBALANCE_STRATEGY_STATIC      RebalanceStrategy = 3 // Static assignment (no rebalancing)
)

// Enum value maps for RebalanceStrategy.
var (
	RebalanceStrategy_name = map[int32]string{
		0: "REBALANCE_STRATEGY_UNSPECIFIED",
		1: "REBALANCE_STRATEGY_EAGER",
		2: "REBALANCE_STRATEGY_COOPERATIVE",
		3: "REBALANCE_STRATEGY_STATIC",
	}
	RebalanceStrategy_value = map[string]int32{
		"REBALANCE_STRATEGY_UNSPECIFIED": 0,
		"REBALANCE_STRATEGY_EAGER":       1,
		"REBALANCE_STRATEGY_COOPERATIVE": 2,
		"REBALANCE_STRATEGY_STATIC":      3,
	}
)

func (x RebalanceStrategy) Enum() *RebalanceStrategy {
	p := new(RebalanceStrategy)
	*p = x
	return p
}

func (x RebalanceStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RebalanceStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_commonpb_v1_rebalance_strategy_proto_enumTypes[0].Descriptor()
}

func (RebalanceStrategy) Type() protoreflect.EnumType {
	return &file_commonpb_v1_rebalance_strategy_proto_enumTypes[0]
}

func (x RebalanceStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_commonpb_v1_rebalance_strategy_proto protoreflect.FileDescriptor

const file_commonpb_v1_rebalance_strategy_proto_rawDesc = "" +
	"\n" +
	"$commonpb/v1/rebalance_strategy.proto\x12\tcommon.v1\x1a!google/protobuf/go_features.proto*\x98\x01\n" +
	"\x11RebalanceStrategy\x12\"\n" +
	"\x1eREBALANCE_STRATEGY_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18REBALANCE_STRATEGY_EAGER\x10\x01\x12\"\n" +
	"\x1eREBALANCE_STRATEGY_COOPERATIVE\x10\x02\x12\x1d\n" +
	"\x19REBALANCE_STRATEGY_STATIC\x10\x03B\x9c\x01\n" +
	"\rcom.common.v1B\x16RebalanceStrategyProtoP\x01Z&github.com/jdfalk/gcommon/pkg/commonpb\xa2\x02\x03CXX\xaa\x02\tCommon.V1\xca\x02\tCommon\\V1\xe2\x02\x15Common\\V1\\GPBMetadata\xea\x02\n" +
	"Common::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_commonpb_v1_rebalance_strategy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commonpb_v1_rebalance_strategy_proto_goTypes = []any{
	(RebalanceStrategy)(0), // 0: common.v1.RebalanceStrategy
}
var file_commonpb_v1_rebalance_strategy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commonpb_v1_rebalance_strategy_proto_init() }
func file_commonpb_v1_rebalance_strategy_proto_init() {
	if File_commonpb_v1_rebalance_strategy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonpb_v1_rebalance_strategy_proto_rawDesc), len(file_commonpb_v1_rebalance_strategy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commonpb_v1_rebalance_strategy_proto_goTypes,
		DependencyIndexes: file_commonpb_v1_rebalance_strategy_proto_depIdxs,
		EnumInfos:         file_commonpb_v1_rebalance_strategy_proto_enumTypes,
	}.Build()
	File_commonpb_v1_rebalance_strategy_proto = out.File
	file_commonpb_v1_rebalance_strategy_proto_goTypes = nil
	file_commonpb_v1_rebalance_strategy_proto_depIdxs = nil
}
