// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: commonpb/v1/log_service.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_commonpb_v1_log_service_proto protoreflect.FileDescriptor

const file_commonpb_v1_log_service_proto_rawDesc = "" +
	"\n" +
	"\x1dcommonpb/v1/log_service.proto\x12\tcommon.v1\x1a#commonpb/v1/read_logs_request.proto\x1a$commonpb/v1/read_logs_response.proto\x1a#commonpb/v1/write_log_request.proto\x1a$commonpb/v1/write_log_response.proto\x1a!google/protobuf/go_features.proto2\x96\x01\n" +
	"\n" +
	"LogService\x12C\n" +
	"\bWriteLog\x12\x1a.common.v1.WriteLogRequest\x1a\x1b.common.v1.WriteLogResponse\x12C\n" +
	"\bReadLogs\x12\x1a.common.v1.ReadLogsRequest\x1a\x1b.common.v1.ReadLogsResponseB\x95\x01\n" +
	"\rcom.common.v1B\x0fLogServiceProtoP\x01Z&github.com/jdfalk/gcommon/pkg/commonpb\xa2\x02\x03CXX\xaa\x02\tCommon.V1\xca\x02\tCommon\\V1\xe2\x02\x15Common\\V1\\GPBMetadata\xea\x02\n" +
	"Common::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_commonpb_v1_log_service_proto_goTypes = []any{
	(*WriteLogRequest)(nil),  // 0: common.v1.WriteLogRequest
	(*ReadLogsRequest)(nil),  // 1: common.v1.ReadLogsRequest
	(*WriteLogResponse)(nil), // 2: common.v1.WriteLogResponse
	(*ReadLogsResponse)(nil), // 3: common.v1.ReadLogsResponse
}
var file_commonpb_v1_log_service_proto_depIdxs = []int32{
	0, // 0: common.v1.LogService.WriteLog:input_type -> common.v1.WriteLogRequest
	1, // 1: common.v1.LogService.ReadLogs:input_type -> common.v1.ReadLogsRequest
	2, // 2: common.v1.LogService.WriteLog:output_type -> common.v1.WriteLogResponse
	3, // 3: common.v1.LogService.ReadLogs:output_type -> common.v1.ReadLogsResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commonpb_v1_log_service_proto_init() }
func file_commonpb_v1_log_service_proto_init() {
	if File_commonpb_v1_log_service_proto != nil {
		return
	}
	file_commonpb_v1_read_logs_request_proto_init()
	file_commonpb_v1_read_logs_response_proto_init()
	file_commonpb_v1_write_log_request_proto_init()
	file_commonpb_v1_write_log_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonpb_v1_log_service_proto_rawDesc), len(file_commonpb_v1_log_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_commonpb_v1_log_service_proto_goTypes,
		DependencyIndexes: file_commonpb_v1_log_service_proto_depIdxs,
	}.Build()
	File_commonpb_v1_log_service_proto = out.File
	file_commonpb_v1_log_service_proto_goTypes = nil
	file_commonpb_v1_log_service_proto_depIdxs = nil
}
