// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: commonpb/v1/logout_response.proto

package commonpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogoutResponse provides the result of a logout request
type LogoutResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success     bool                   `protobuf:"varint,1,opt,name=success"`
	xxx_hidden_Error       *Error                 `protobuf:"bytes,2,opt,name=error"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_commonpb_v1_logout_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_commonpb_v1_logout_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *LogoutResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *LogoutResponse) GetError() *Error {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return nil
}

func (x *LogoutResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *LogoutResponse) SetError(v *Error) {
	x.xxx_hidden_Error = v
}

func (x *LogoutResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *LogoutResponse) HasError() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Error != nil
}

func (x *LogoutResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

func (x *LogoutResponse) ClearError() {
	x.xxx_hidden_Error = nil
}

type LogoutResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether the logout was successful
	Success *bool
	// Optional error information if logout failed
	Error *Error
}

func (b0 LogoutResponse_builder) Build() *LogoutResponse {
	m0 := &LogoutResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Success = *b.Success
	}
	x.xxx_hidden_Error = b.Error
	return m0
}

var File_commonpb_v1_logout_response_proto protoreflect.FileDescriptor

const file_commonpb_v1_logout_response_proto_rawDesc = "" +
	"\n" +
	"!commonpb/v1/logout_response.proto\x12\tcommon.v1\x1a\x17commonpb/v1/error.proto\x1a!google/protobuf/go_features.proto\"R\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x10.common.v1.ErrorR\x05errorB\x99\x01\n" +
	"\rcom.common.v1B\x13LogoutResponseProtoP\x01Z&github.com/jdfalk/gcommon/pkg/commonpb\xa2\x02\x03CXX\xaa\x02\tCommon.V1\xca\x02\tCommon\\V1\xe2\x02\x15Common\\V1\\GPBMetadata\xea\x02\n" +
	"Common::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_commonpb_v1_logout_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_commonpb_v1_logout_response_proto_goTypes = []any{
	(*LogoutResponse)(nil), // 0: common.v1.LogoutResponse
	(*Error)(nil),          // 1: common.v1.Error
}
var file_commonpb_v1_logout_response_proto_depIdxs = []int32{
	1, // 0: common.v1.LogoutResponse.error:type_name -> common.v1.Error
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_commonpb_v1_logout_response_proto_init() }
func file_commonpb_v1_logout_response_proto_init() {
	if File_commonpb_v1_logout_response_proto != nil {
		return
	}
	file_commonpb_v1_error_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonpb_v1_logout_response_proto_rawDesc), len(file_commonpb_v1_logout_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commonpb_v1_logout_response_proto_goTypes,
		DependencyIndexes: file_commonpb_v1_logout_response_proto_depIdxs,
		MessageInfos:      file_commonpb_v1_logout_response_proto_msgTypes,
	}.Build()
	File_commonpb_v1_logout_response_proto = out.File
	file_commonpb_v1_logout_response_proto_goTypes = nil
	file_commonpb_v1_logout_response_proto_depIdxs = nil
}
