// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: common/v1/list_sessions_request.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Request to list all sessions (admin only).
// Used for administrative monitoring and management.
type AuthListSessionsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pagination  *Pagination            `protobuf:"bytes,1,opt,name=pagination"`
	xxx_hidden_UserId      *string                `protobuf:"bytes,2,opt,name=user_id,json=userId"`
	xxx_hidden_Status      *string                `protobuf:"bytes,3,opt,name=status"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AuthListSessionsRequest) Reset() {
	*x = AuthListSessionsRequest{}
	mi := &file_common_v1_list_sessions_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthListSessionsRequest) ProtoMessage() {}

func (x *AuthListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_list_sessions_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthListSessionsRequest) GetPagination() *Pagination {
	if x != nil {
		return x.xxx_hidden_Pagination
	}
	return nil
}

func (x *AuthListSessionsRequest) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *AuthListSessionsRequest) GetStatus() string {
	if x != nil {
		if x.xxx_hidden_Status != nil {
			return *x.xxx_hidden_Status
		}
		return ""
	}
	return ""
}

func (x *AuthListSessionsRequest) SetPagination(v *Pagination) {
	x.xxx_hidden_Pagination = v
}

func (x *AuthListSessionsRequest) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *AuthListSessionsRequest) SetStatus(v string) {
	x.xxx_hidden_Status = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *AuthListSessionsRequest) HasPagination() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Pagination != nil
}

func (x *AuthListSessionsRequest) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *AuthListSessionsRequest) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *AuthListSessionsRequest) ClearPagination() {
	x.xxx_hidden_Pagination = nil
}

func (x *AuthListSessionsRequest) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_UserId = nil
}

func (x *AuthListSessionsRequest) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Status = nil
}

type AuthListSessionsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Pagination parameters
	Pagination *Pagination
	// Filter by user ID (optional)
	UserId *string
	// Filter by session status (optional)
	Status *string
}

func (b0 AuthListSessionsRequest_builder) Build() *AuthListSessionsRequest {
	m0 := &AuthListSessionsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Pagination = b.Pagination
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_UserId = b.UserId
	}
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Status = b.Status
	}
	return m0
}

var File_common_v1_list_sessions_request_proto protoreflect.FileDescriptor

const file_common_v1_list_sessions_request_proto_rawDesc = "" +
	"\n" +
	"%common/v1/list_sessions_request.proto\x12\tcommon.v1\x1a\x1acommon/v1/pagination.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xda\x01\n" +
	"\x17AuthListSessionsRequest\x125\n" +
	"\n" +
	"pagination\x18\x01 \x01(\v2\x15.common.v1.PaginationR\n" +
	"pagination\x12p\n" +
	"\auser_id\x18\x02 \x01(\tBW\xbaHT\xc8\x01\x01rO2M^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$R\x06userId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06statusB-Z#github.com/jdfalk/gcommon/common/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_common_v1_list_sessions_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v1_list_sessions_request_proto_goTypes = []any{
	(*AuthListSessionsRequest)(nil), // 0: common.v1.AuthListSessionsRequest
	(*Pagination)(nil),              // 1: common.v1.Pagination
}
var file_common_v1_list_sessions_request_proto_depIdxs = []int32{
	1, // 0: common.v1.AuthListSessionsRequest.pagination:type_name -> common.v1.Pagination
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_v1_list_sessions_request_proto_init() }
func file_common_v1_list_sessions_request_proto_init() {
	if File_common_v1_list_sessions_request_proto != nil {
		return
	}
	file_common_v1_pagination_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_list_sessions_request_proto_rawDesc), len(file_common_v1_list_sessions_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_list_sessions_request_proto_goTypes,
		DependencyIndexes: file_common_v1_list_sessions_request_proto_depIdxs,
		MessageInfos:      file_common_v1_list_sessions_request_proto_msgTypes,
	}.Build()
	File_common_v1_list_sessions_request_proto = out.File
	file_common_v1_list_sessions_request_proto_goTypes = nil
	file_common_v1_list_sessions_request_proto_depIdxs = nil
}
