// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: common/v1/session_service.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_common_v1_session_service_proto protoreflect.FileDescriptor

const file_common_v1_session_service_proto_rawDesc = "" +
	"\n" +
	"\x1fcommon/v1/session_service.proto\x12\tcommon.v1\x1a&common/v1/create_session_request.proto\x1a'common/v1/create_session_response.proto\x1a&common/v1/delete_session_request.proto\x1a'common/v1/delete_session_response.proto\x1a#common/v1/get_session_request.proto\x1a$common/v1/get_session_response.proto\x1a%common/v1/list_sessions_request.proto\x1a&common/v1/list_sessions_response.proto\x1a*common/v1/list_user_sessions_request.proto\x1a+common/v1/list_user_sessions_response.proto\x1a)common/v1/terminate_session_request.proto\x1a*common/v1/terminate_session_response.proto\x1a&common/v1/update_session_request.proto\x1a'common/v1/update_session_response.proto\x1a(common/v1/validate_session_request.proto\x1a)common/v1/validate_session_response.proto\x1a!google/protobuf/go_features.proto2\xe4\x05\n" +
	"\x0eSessionService\x12Z\n" +
	"\rCreateSession\x12#.common.v1.AuthCreateSessionRequest\x1a$.common.v1.AuthCreateSessionResponse\x12Q\n" +
	"\n" +
	"GetSession\x12 .common.v1.AuthGetSessionRequest\x1a!.common.v1.AuthGetSessionResponse\x12Z\n" +
	"\rUpdateSession\x12#.common.v1.AuthUpdateSessionRequest\x1a$.common.v1.AuthUpdateSessionResponse\x12X\n" +
	"\x0fValidateSession\x12!.common.v1.ValidateSessionRequest\x1a\".common.v1.ValidateSessionResponse\x12[\n" +
	"\x10TerminateSession\x12\".common.v1.TerminateSessionRequest\x1a#.common.v1.TerminateSessionResponse\x12Z\n" +
	"\rDeleteSession\x12#.common.v1.AuthDeleteSessionRequest\x1a$.common.v1.AuthDeleteSessionResponse\x12[\n" +
	"\x10ListUserSessions\x12\".common.v1.ListUserSessionsRequest\x1a#.common.v1.ListUserSessionsResponse\x12W\n" +
	"\fListSessions\x12\".common.v1.AuthListSessionsRequest\x1a#.common.v1.AuthListSessionsResponseB/Z%github.com/jdfalk/gcommon/pkg/common/\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_common_v1_session_service_proto_goTypes = []any{
	(*AuthCreateSessionRequest)(nil),  // 0: common.v1.AuthCreateSessionRequest
	(*AuthGetSessionRequest)(nil),     // 1: common.v1.AuthGetSessionRequest
	(*AuthUpdateSessionRequest)(nil),  // 2: common.v1.AuthUpdateSessionRequest
	(*ValidateSessionRequest)(nil),    // 3: common.v1.ValidateSessionRequest
	(*TerminateSessionRequest)(nil),   // 4: common.v1.TerminateSessionRequest
	(*AuthDeleteSessionRequest)(nil),  // 5: common.v1.AuthDeleteSessionRequest
	(*ListUserSessionsRequest)(nil),   // 6: common.v1.ListUserSessionsRequest
	(*AuthListSessionsRequest)(nil),   // 7: common.v1.AuthListSessionsRequest
	(*AuthCreateSessionResponse)(nil), // 8: common.v1.AuthCreateSessionResponse
	(*AuthGetSessionResponse)(nil),    // 9: common.v1.AuthGetSessionResponse
	(*AuthUpdateSessionResponse)(nil), // 10: common.v1.AuthUpdateSessionResponse
	(*ValidateSessionResponse)(nil),   // 11: common.v1.ValidateSessionResponse
	(*TerminateSessionResponse)(nil),  // 12: common.v1.TerminateSessionResponse
	(*AuthDeleteSessionResponse)(nil), // 13: common.v1.AuthDeleteSessionResponse
	(*ListUserSessionsResponse)(nil),  // 14: common.v1.ListUserSessionsResponse
	(*AuthListSessionsResponse)(nil),  // 15: common.v1.AuthListSessionsResponse
}
var file_common_v1_session_service_proto_depIdxs = []int32{
	0,  // 0: common.v1.SessionService.CreateSession:input_type -> common.v1.AuthCreateSessionRequest
	1,  // 1: common.v1.SessionService.GetSession:input_type -> common.v1.AuthGetSessionRequest
	2,  // 2: common.v1.SessionService.UpdateSession:input_type -> common.v1.AuthUpdateSessionRequest
	3,  // 3: common.v1.SessionService.ValidateSession:input_type -> common.v1.ValidateSessionRequest
	4,  // 4: common.v1.SessionService.TerminateSession:input_type -> common.v1.TerminateSessionRequest
	5,  // 5: common.v1.SessionService.DeleteSession:input_type -> common.v1.AuthDeleteSessionRequest
	6,  // 6: common.v1.SessionService.ListUserSessions:input_type -> common.v1.ListUserSessionsRequest
	7,  // 7: common.v1.SessionService.ListSessions:input_type -> common.v1.AuthListSessionsRequest
	8,  // 8: common.v1.SessionService.CreateSession:output_type -> common.v1.AuthCreateSessionResponse
	9,  // 9: common.v1.SessionService.GetSession:output_type -> common.v1.AuthGetSessionResponse
	10, // 10: common.v1.SessionService.UpdateSession:output_type -> common.v1.AuthUpdateSessionResponse
	11, // 11: common.v1.SessionService.ValidateSession:output_type -> common.v1.ValidateSessionResponse
	12, // 12: common.v1.SessionService.TerminateSession:output_type -> common.v1.TerminateSessionResponse
	13, // 13: common.v1.SessionService.DeleteSession:output_type -> common.v1.AuthDeleteSessionResponse
	14, // 14: common.v1.SessionService.ListUserSessions:output_type -> common.v1.ListUserSessionsResponse
	15, // 15: common.v1.SessionService.ListSessions:output_type -> common.v1.AuthListSessionsResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_session_service_proto_init() }
func file_common_v1_session_service_proto_init() {
	if File_common_v1_session_service_proto != nil {
		return
	}
	file_common_v1_create_session_request_proto_init()
	file_common_v1_create_session_response_proto_init()
	file_common_v1_delete_session_request_proto_init()
	file_common_v1_delete_session_response_proto_init()
	file_common_v1_get_session_request_proto_init()
	file_common_v1_get_session_response_proto_init()
	file_common_v1_list_sessions_request_proto_init()
	file_common_v1_list_sessions_response_proto_init()
	file_common_v1_list_user_sessions_request_proto_init()
	file_common_v1_list_user_sessions_response_proto_init()
	file_common_v1_terminate_session_request_proto_init()
	file_common_v1_terminate_session_response_proto_init()
	file_common_v1_update_session_request_proto_init()
	file_common_v1_update_session_response_proto_init()
	file_common_v1_validate_session_request_proto_init()
	file_common_v1_validate_session_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_session_service_proto_rawDesc), len(file_common_v1_session_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_v1_session_service_proto_goTypes,
		DependencyIndexes: file_common_v1_session_service_proto_depIdxs,
	}.Build()
	File_common_v1_session_service_proto = out.File
	file_common_v1_session_service_proto_goTypes = nil
	file_common_v1_session_service_proto_depIdxs = nil
}
