// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: web/v2/get_server_logs_response.proto

package v2

import (
	v2 "github.com/jdfalk/gcommon/common/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// GetServerLogsResponse message for web service operations.
// Auto-generated placeholder - implement specific fields as needed.
//
// Follows 1-1-1 pattern: one message per file.
type GetServerLogsResponse struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Success             bool                   `protobuf:"varint,1,opt,name=success"`
	xxx_hidden_RequestMetadata     *v2.RequestMetadata    `protobuf:"bytes,11,opt,name=request_metadata,json=requestMetadata"`
	xxx_hidden_Error               *v2.Error              `protobuf:"bytes,61,opt,name=error"`
	xxx_hidden_ResponseGeneratedAt *timestamppb.Timestamp `protobuf:"bytes,51,opt,name=response_generated_at,json=responseGeneratedAt"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *GetServerLogsResponse) Reset() {
	*x = GetServerLogsResponse{}
	mi := &file_web_v2_get_server_logs_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerLogsResponse) ProtoMessage() {}

func (x *GetServerLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_web_v2_get_server_logs_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetServerLogsResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *GetServerLogsResponse) GetRequestMetadata() *v2.RequestMetadata {
	if x != nil {
		return x.xxx_hidden_RequestMetadata
	}
	return nil
}

func (x *GetServerLogsResponse) GetError() *v2.Error {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return nil
}

func (x *GetServerLogsResponse) GetResponseGeneratedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ResponseGeneratedAt
	}
	return nil
}

func (x *GetServerLogsResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *GetServerLogsResponse) SetRequestMetadata(v *v2.RequestMetadata) {
	x.xxx_hidden_RequestMetadata = v
}

func (x *GetServerLogsResponse) SetError(v *v2.Error) {
	x.xxx_hidden_Error = v
}

func (x *GetServerLogsResponse) SetResponseGeneratedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ResponseGeneratedAt = v
}

func (x *GetServerLogsResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetServerLogsResponse) HasRequestMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RequestMetadata != nil
}

func (x *GetServerLogsResponse) HasError() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Error != nil
}

func (x *GetServerLogsResponse) HasResponseGeneratedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ResponseGeneratedAt != nil
}

func (x *GetServerLogsResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

func (x *GetServerLogsResponse) ClearRequestMetadata() {
	x.xxx_hidden_RequestMetadata = nil
}

func (x *GetServerLogsResponse) ClearError() {
	x.xxx_hidden_Error = nil
}

func (x *GetServerLogsResponse) ClearResponseGeneratedAt() {
	x.xxx_hidden_ResponseGeneratedAt = nil
}

type GetServerLogsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// *
	// Indicates whether the operation was successful.
	Success *bool
	// *
	// Request processing metadata including timing, request ID,
	// and other observability information.
	RequestMetadata *v2.RequestMetadata
	// *
	// Error information if the operation failed
	// or completed with warnings.
	Error *v2.Error
	// *
	// Timestamp when this response was generated.
	ResponseGeneratedAt *timestamppb.Timestamp
}

func (b0 GetServerLogsResponse_builder) Build() *GetServerLogsResponse {
	m0 := &GetServerLogsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Success = *b.Success
	}
	x.xxx_hidden_RequestMetadata = b.RequestMetadata
	x.xxx_hidden_Error = b.Error
	x.xxx_hidden_ResponseGeneratedAt = b.ResponseGeneratedAt
	return m0
}

var File_web_v2_get_server_logs_response_proto protoreflect.FileDescriptor

const file_web_v2_get_server_logs_response_proto_rawDesc = "" +
	"\n" +
	"%web/v2/get_server_logs_response.proto\x12\x06web.v2\x1a\x15common/v2/error.proto\x1a common/v2/request_metadata.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf0\x01\n" +
	"\x15GetServerLogsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12E\n" +
	"\x10request_metadata\x18\v \x01(\v2\x1a.common.v2.RequestMetadataR\x0frequestMetadata\x12&\n" +
	"\x05error\x18= \x01(\v2\x10.common.v2.ErrorR\x05error\x12N\n" +
	"\x15response_generated_at\x183 \x01(\v2\x1a.google.protobuf.TimestampR\x13responseGeneratedAtB*Z github.com/jdfalk/gcommon/web/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_web_v2_get_server_logs_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_web_v2_get_server_logs_response_proto_goTypes = []any{
	(*GetServerLogsResponse)(nil), // 0: web.v2.GetServerLogsResponse
	(*v2.RequestMetadata)(nil),    // 1: common.v2.RequestMetadata
	(*v2.Error)(nil),              // 2: common.v2.Error
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_web_v2_get_server_logs_response_proto_depIdxs = []int32{
	1, // 0: web.v2.GetServerLogsResponse.request_metadata:type_name -> common.v2.RequestMetadata
	2, // 1: web.v2.GetServerLogsResponse.error:type_name -> common.v2.Error
	3, // 2: web.v2.GetServerLogsResponse.response_generated_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_web_v2_get_server_logs_response_proto_init() }
func file_web_v2_get_server_logs_response_proto_init() {
	if File_web_v2_get_server_logs_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_v2_get_server_logs_response_proto_rawDesc), len(file_web_v2_get_server_logs_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_web_v2_get_server_logs_response_proto_goTypes,
		DependencyIndexes: file_web_v2_get_server_logs_response_proto_depIdxs,
		MessageInfos:      file_web_v2_get_server_logs_response_proto_msgTypes,
	}.Build()
	File_web_v2_get_server_logs_response_proto = out.File
	file_web_v2_get_server_logs_response_proto_goTypes = nil
	file_web_v2_get_server_logs_response_proto_depIdxs = nil
}
