// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: metrics/v2/metric_series.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v2 "github.com/jdfalk/gcommon/common/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricSeries struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Type        v2.MetricsMetricType   `protobuf:"varint,2,opt,name=type,enum=common.v2.MetricsMetricType"`
	xxx_hidden_Labels      map[string]string      `protobuf:"bytes,3,rep,name=labels" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	xxx_hidden_Values      *[]*MetricValue        `protobuf:"bytes,4,rep,name=values"`
	xxx_hidden_StepSeconds int64                  `protobuf:"varint,5,opt,name=step_seconds,json=stepSeconds"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MetricSeries) Reset() {
	*x = MetricSeries{}
	mi := &file_metrics_v2_metric_series_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricSeries) ProtoMessage() {}

func (x *MetricSeries) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v2_metric_series_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MetricSeries) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *MetricSeries) GetType() v2.MetricsMetricType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Type
		}
	}
	return v2.MetricsMetricType(0)
}

func (x *MetricSeries) GetLabels() map[string]string {
	if x != nil {
		return x.xxx_hidden_Labels
	}
	return nil
}

func (x *MetricSeries) GetValues() []*MetricValue {
	if x != nil {
		if x.xxx_hidden_Values != nil {
			return *x.xxx_hidden_Values
		}
	}
	return nil
}

func (x *MetricSeries) GetStepSeconds() int64 {
	if x != nil {
		return x.xxx_hidden_StepSeconds
	}
	return 0
}

func (x *MetricSeries) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *MetricSeries) SetType(v v2.MetricsMetricType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *MetricSeries) SetLabels(v map[string]string) {
	x.xxx_hidden_Labels = v
}

func (x *MetricSeries) SetValues(v []*MetricValue) {
	x.xxx_hidden_Values = &v
}

func (x *MetricSeries) SetStepSeconds(v int64) {
	x.xxx_hidden_StepSeconds = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *MetricSeries) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MetricSeries) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MetricSeries) HasStepSeconds() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *MetricSeries) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *MetricSeries) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Type = v2.MetricsMetricType_METRIC_TYPE_UNSPECIFIED
}

func (x *MetricSeries) ClearStepSeconds() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_StepSeconds = 0
}

type MetricSeries_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Metric metadata
	Name   *string
	Type   *v2.MetricsMetricType
	Labels map[string]string
	// Time-ordered series of values
	Values []*MetricValue
	// Resolution/step between data points
	StepSeconds *int64
}

func (b0 MetricSeries_builder) Build() *MetricSeries {
	m0 := &MetricSeries{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Name = b.Name
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Type = *b.Type
	}
	x.xxx_hidden_Labels = b.Labels
	x.xxx_hidden_Values = &b.Values
	if b.StepSeconds != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_StepSeconds = *b.StepSeconds
	}
	return m0
}

var File_metrics_v2_metric_series_proto protoreflect.FileDescriptor

const file_metrics_v2_metric_series_proto_rawDesc = "" +
	"\n" +
	"\x1emetrics/v2/metric_series.proto\x12\n" +
	"metrics.v2\x1a\x1bcommon/v2/metric_type.proto\x1a\x1dmetrics/v2/metric_value.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xac\x02\n" +
	"\fMetricSeries\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\x04name\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.common.v2.MetricsMetricTypeR\x04type\x12<\n" +
	"\x06labels\x18\x03 \x03(\v2$.metrics.v2.MetricSeries.LabelsEntryR\x06labels\x12/\n" +
	"\x06values\x18\x04 \x03(\v2\x17.metrics.v2.MetricValueR\x06values\x12!\n" +
	"\fstep_seconds\x18\x05 \x01(\x03R\vstepSeconds\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B.Z$github.com/jdfalk/gcommon/metrics/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_metrics_v2_metric_series_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metrics_v2_metric_series_proto_goTypes = []any{
	(*MetricSeries)(nil),      // 0: metrics.v2.MetricSeries
	nil,                       // 1: metrics.v2.MetricSeries.LabelsEntry
	(v2.MetricsMetricType)(0), // 2: common.v2.MetricsMetricType
	(*MetricValue)(nil),       // 3: metrics.v2.MetricValue
}
var file_metrics_v2_metric_series_proto_depIdxs = []int32{
	2, // 0: metrics.v2.MetricSeries.type:type_name -> common.v2.MetricsMetricType
	1, // 1: metrics.v2.MetricSeries.labels:type_name -> metrics.v2.MetricSeries.LabelsEntry
	3, // 2: metrics.v2.MetricSeries.values:type_name -> metrics.v2.MetricValue
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_metrics_v2_metric_series_proto_init() }
func file_metrics_v2_metric_series_proto_init() {
	if File_metrics_v2_metric_series_proto != nil {
		return
	}
	file_metrics_v2_metric_value_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_v2_metric_series_proto_rawDesc), len(file_metrics_v2_metric_series_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_v2_metric_series_proto_goTypes,
		DependencyIndexes: file_metrics_v2_metric_series_proto_depIdxs,
		MessageInfos:      file_metrics_v2_metric_series_proto_msgTypes,
	}.Build()
	File_metrics_v2_metric_series_proto = out.File
	file_metrics_v2_metric_series_proto_goTypes = nil
	file_metrics_v2_metric_series_proto_depIdxs = nil
}
