// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: organizationpb/v2/domain_config.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DomainConfig struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DomainName       *string                `protobuf:"bytes,1,opt,name=domain_name,json=domainName"`
	xxx_hidden_SslCertificate   *string                `protobuf:"bytes,2,opt,name=ssl_certificate,json=sslCertificate"`
	xxx_hidden_Dns              *DNSConfig             `protobuf:"bytes,3,opt,name=dns"`
	xxx_hidden_ValidationStatus *string                `protobuf:"bytes,4,opt,name=validation_status,json=validationStatus"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DomainConfig) Reset() {
	*x = DomainConfig{}
	mi := &file_organizationpb_v2_domain_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DomainConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DomainConfig) ProtoMessage() {}

func (x *DomainConfig) ProtoReflect() protoreflect.Message {
	mi := &file_organizationpb_v2_domain_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DomainConfig) GetDomainName() string {
	if x != nil {
		if x.xxx_hidden_DomainName != nil {
			return *x.xxx_hidden_DomainName
		}
		return ""
	}
	return ""
}

func (x *DomainConfig) GetSslCertificate() string {
	if x != nil {
		if x.xxx_hidden_SslCertificate != nil {
			return *x.xxx_hidden_SslCertificate
		}
		return ""
	}
	return ""
}

func (x *DomainConfig) GetDns() *DNSConfig {
	if x != nil {
		return x.xxx_hidden_Dns
	}
	return nil
}

func (x *DomainConfig) GetValidationStatus() string {
	if x != nil {
		if x.xxx_hidden_ValidationStatus != nil {
			return *x.xxx_hidden_ValidationStatus
		}
		return ""
	}
	return ""
}

func (x *DomainConfig) SetDomainName(v string) {
	x.xxx_hidden_DomainName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *DomainConfig) SetSslCertificate(v string) {
	x.xxx_hidden_SslCertificate = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *DomainConfig) SetDns(v *DNSConfig) {
	x.xxx_hidden_Dns = v
}

func (x *DomainConfig) SetValidationStatus(v string) {
	x.xxx_hidden_ValidationStatus = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *DomainConfig) HasDomainName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DomainConfig) HasSslCertificate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DomainConfig) HasDns() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Dns != nil
}

func (x *DomainConfig) HasValidationStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DomainConfig) ClearDomainName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DomainName = nil
}

func (x *DomainConfig) ClearSslCertificate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SslCertificate = nil
}

func (x *DomainConfig) ClearDns() {
	x.xxx_hidden_Dns = nil
}

func (x *DomainConfig) ClearValidationStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ValidationStatus = nil
}

type DomainConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Custom domain name
	DomainName *string
	// SSL certificate ARN or ID
	SslCertificate *string
	// DNS configuration
	Dns *DNSConfig
	// Domain validation status
	ValidationStatus *string
}

func (b0 DomainConfig_builder) Build() *DomainConfig {
	m0 := &DomainConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DomainName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_DomainName = b.DomainName
	}
	if b.SslCertificate != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_SslCertificate = b.SslCertificate
	}
	x.xxx_hidden_Dns = b.Dns
	if b.ValidationStatus != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_ValidationStatus = b.ValidationStatus
	}
	return m0
}

var File_organizationpb_v2_domain_config_proto protoreflect.FileDescriptor

const file_organizationpb_v2_domain_config_proto_rawDesc = "" +
	"\n" +
	"%organizationpb/v2/domain_config.proto\x12\x0forganization.v2\x1a\"organizationpb/v2/dns_config.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xbe\x01\n" +
	"\fDomainConfig\x12*\n" +
	"\vdomain_name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\n" +
	"domainName\x12'\n" +
	"\x0fssl_certificate\x18\x02 \x01(\tR\x0esslCertificate\x12,\n" +
	"\x03dns\x18\x03 \x01(\v2\x1a.organization.v2.DNSConfigR\x03dns\x12+\n" +
	"\x11validation_status\x18\x04 \x01(\tR\x10validationStatusB\xbe\x01\n" +
	"\x13com.organization.v2B\x11DomainConfigProtoP\x01Z/github.com/jdfalk/gcommon/pkg/organizationpb/v2\xa2\x02\x03OXX\xaa\x02\x0fOrganization.V2\xca\x02\x0fOrganization\\V2\xe2\x02\x1bOrganization\\V2\\GPBMetadata\xea\x02\x10Organization::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_organizationpb_v2_domain_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_organizationpb_v2_domain_config_proto_goTypes = []any{
	(*DomainConfig)(nil), // 0: organization.v2.DomainConfig
	(*DNSConfig)(nil),    // 1: organization.v2.DNSConfig
}
var file_organizationpb_v2_domain_config_proto_depIdxs = []int32{
	1, // 0: organization.v2.DomainConfig.dns:type_name -> organization.v2.DNSConfig
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_organizationpb_v2_domain_config_proto_init() }
func file_organizationpb_v2_domain_config_proto_init() {
	if File_organizationpb_v2_domain_config_proto != nil {
		return
	}
	file_organizationpb_v2_dns_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organizationpb_v2_domain_config_proto_rawDesc), len(file_organizationpb_v2_domain_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organizationpb_v2_domain_config_proto_goTypes,
		DependencyIndexes: file_organizationpb_v2_domain_config_proto_depIdxs,
		MessageInfos:      file_organizationpb_v2_domain_config_proto_msgTypes,
	}.Build()
	File_organizationpb_v2_domain_config_proto = out.File
	file_organizationpb_v2_domain_config_proto_goTypes = nil
	file_organizationpb_v2_domain_config_proto_depIdxs = nil
}
