// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: organizationpb/v1/delete_team_response.proto

package organizationpb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	commonpb "github.com/jdfalk/gcommon/pkg/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeleteTeamResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Errors      *[]*commonpb.Error     `protobuf:"bytes,1,rep,name=errors"`
	xxx_hidden_Success     bool                   `protobuf:"varint,2,opt,name=success"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DeleteTeamResponse) Reset() {
	*x = DeleteTeamResponse{}
	mi := &file_organizationpb_v1_delete_team_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTeamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTeamResponse) ProtoMessage() {}

func (x *DeleteTeamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_organizationpb_v1_delete_team_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteTeamResponse) GetErrors() []*commonpb.Error {
	if x != nil {
		if x.xxx_hidden_Errors != nil {
			return *x.xxx_hidden_Errors
		}
	}
	return nil
}

func (x *DeleteTeamResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *DeleteTeamResponse) SetErrors(v []*commonpb.Error) {
	x.xxx_hidden_Errors = &v
}

func (x *DeleteTeamResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *DeleteTeamResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DeleteTeamResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Success = false
}

type DeleteTeamResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Any errors encountered
	Errors []*commonpb.Error
	// Success status
	Success *bool
}

func (b0 DeleteTeamResponse_builder) Build() *DeleteTeamResponse {
	m0 := &DeleteTeamResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Errors = &b.Errors
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Success = *b.Success
	}
	return m0
}

var File_organizationpb_v1_delete_team_response_proto protoreflect.FileDescriptor

const file_organizationpb_v1_delete_team_response_proto_rawDesc = "" +
	"\n" +
	",organizationpb/v1/delete_team_response.proto\x12\x0forganization.v1\x1a\x17commonpb/v1/error.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"b\n" +
	"\x12DeleteTeamResponse\x122\n" +
	"\x06errors\x18\x01 \x03(\v2\x10.common.v1.ErrorB\b\xbaH\x05\x92\x01\x02\b\x01R\x06errors\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccessB\xc1\x01\n" +
	"\x13com.organization.v1B\x17DeleteTeamResponseProtoP\x01Z,github.com/jdfalk/gcommon/pkg/organizationpb\xa2\x02\x03OXX\xaa\x02\x0fOrganization.V1\xca\x02\x0fOrganization\\V1\xe2\x02\x1bOrganization\\V1\\GPBMetadata\xea\x02\x10Organization::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_organizationpb_v1_delete_team_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_organizationpb_v1_delete_team_response_proto_goTypes = []any{
	(*DeleteTeamResponse)(nil), // 0: organization.v1.DeleteTeamResponse
	(*commonpb.Error)(nil),     // 1: common.v1.Error
}
var file_organizationpb_v1_delete_team_response_proto_depIdxs = []int32{
	1, // 0: organization.v1.DeleteTeamResponse.errors:type_name -> common.v1.Error
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_organizationpb_v1_delete_team_response_proto_init() }
func file_organizationpb_v1_delete_team_response_proto_init() {
	if File_organizationpb_v1_delete_team_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organizationpb_v1_delete_team_response_proto_rawDesc), len(file_organizationpb_v1_delete_team_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organizationpb_v1_delete_team_response_proto_goTypes,
		DependencyIndexes: file_organizationpb_v1_delete_team_response_proto_depIdxs,
		MessageInfos:      file_organizationpb_v1_delete_team_response_proto_msgTypes,
	}.Build()
	File_organizationpb_v1_delete_team_response_proto = out.File
	file_organizationpb_v1_delete_team_response_proto_goTypes = nil
	file_organizationpb_v1_delete_team_response_proto_depIdxs = nil
}
