// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: queuepb/v1/list_topics_response.proto

package queuepb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListTopicsResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Topics        *[]*TopicInfo          `protobuf:"bytes,1,rep,name=topics"`
	xxx_hidden_NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken"`
	xxx_hidden_TotalCount    int32                  `protobuf:"varint,3,opt,name=total_count,json=totalCount"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_queuepb_v1_list_topics_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queuepb_v1_list_topics_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListTopicsResponse) GetTopics() []*TopicInfo {
	if x != nil {
		if x.xxx_hidden_Topics != nil {
			return *x.xxx_hidden_Topics
		}
	}
	return nil
}

func (x *ListTopicsResponse) GetNextPageToken() string {
	if x != nil {
		if x.xxx_hidden_NextPageToken != nil {
			return *x.xxx_hidden_NextPageToken
		}
		return ""
	}
	return ""
}

func (x *ListTopicsResponse) GetTotalCount() int32 {
	if x != nil {
		return x.xxx_hidden_TotalCount
	}
	return 0
}

func (x *ListTopicsResponse) SetTopics(v []*TopicInfo) {
	x.xxx_hidden_Topics = &v
}

func (x *ListTopicsResponse) SetNextPageToken(v string) {
	x.xxx_hidden_NextPageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ListTopicsResponse) SetTotalCount(v int32) {
	x.xxx_hidden_TotalCount = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *ListTopicsResponse) HasNextPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListTopicsResponse) HasTotalCount() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ListTopicsResponse) ClearNextPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NextPageToken = nil
}

func (x *ListTopicsResponse) ClearTotalCount() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_TotalCount = 0
}

type ListTopicsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// List of topics
	Topics []*TopicInfo
	// Next page token
	NextPageToken *string
	// Total count
	TotalCount *int32
}

func (b0 ListTopicsResponse_builder) Build() *ListTopicsResponse {
	m0 := &ListTopicsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Topics = &b.Topics
	if b.NextPageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_NextPageToken = b.NextPageToken
	}
	if b.TotalCount != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_TotalCount = *b.TotalCount
	}
	return m0
}

var File_queuepb_v1_list_topics_response_proto protoreflect.FileDescriptor

const file_queuepb_v1_list_topics_response_proto_rawDesc = "" +
	"\n" +
	"%queuepb/v1/list_topics_response.proto\x12\bqueue.v1\x1a\x1bqueuepb/v1/topic_info.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xa6\x01\n" +
	"\x12ListTopicsResponse\x125\n" +
	"\x06topics\x18\x01 \x03(\v2\x13.queue.v1.TopicInfoB\b\xbaH\x05\x92\x01\x02\b\x01R\x06topics\x12/\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\rnextPageToken\x12(\n" +
	"\vtotal_count\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\n" +
	"totalCountB\x97\x01\n" +
	"\fcom.queue.v1B\x17ListTopicsResponseProtoP\x01Z%github.com/jdfalk/gcommon/pkg/queuepb\xa2\x02\x03QXX\xaa\x02\bQueue.V1\xca\x02\bQueue\\V1\xe2\x02\x14Queue\\V1\\GPBMetadata\xea\x02\tQueue::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_queuepb_v1_list_topics_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_queuepb_v1_list_topics_response_proto_goTypes = []any{
	(*ListTopicsResponse)(nil), // 0: queue.v1.ListTopicsResponse
	(*TopicInfo)(nil),          // 1: queue.v1.TopicInfo
}
var file_queuepb_v1_list_topics_response_proto_depIdxs = []int32{
	1, // 0: queue.v1.ListTopicsResponse.topics:type_name -> queue.v1.TopicInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_queuepb_v1_list_topics_response_proto_init() }
func file_queuepb_v1_list_topics_response_proto_init() {
	if File_queuepb_v1_list_topics_response_proto != nil {
		return
	}
	file_queuepb_v1_topic_info_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queuepb_v1_list_topics_response_proto_rawDesc), len(file_queuepb_v1_list_topics_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_queuepb_v1_list_topics_response_proto_goTypes,
		DependencyIndexes: file_queuepb_v1_list_topics_response_proto_depIdxs,
		MessageInfos:      file_queuepb_v1_list_topics_response_proto_msgTypes,
	}.Build()
	File_queuepb_v1_list_topics_response_proto = out.File
	file_queuepb_v1_list_topics_response_proto_goTypes = nil
	file_queuepb_v1_list_topics_response_proto_depIdxs = nil
}
