// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: healthpb/v1/health_service.proto

package healthpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_healthpb_v1_health_service_proto protoreflect.FileDescriptor

const file_healthpb_v1_health_service_proto_rawDesc = "" +
	"\n" +
	" healthpb/v1/health_service.proto\x12\thealth.v1\x1a&healthpb/v1/health_check_request.proto\x1a)healthpb/v1/readiness_check_request.proto\x1a&healthpb/v1/watch_health_request.proto\x1a'healthpb/v1/health_check_response.proto\x1a*healthpb/v1/readiness_check_response.proto\x1a'healthpb/v1/watch_health_response.proto\x1a!google/protobuf/go_features.proto2\xfe\x01\n" +
	"\rHealthService\x12F\n" +
	"\x05Check\x12\x1d.health.v1.HealthCheckRequest\x1a\x1e.health.v1.HealthCheckResponse\x12U\n" +
	"\x0eCheckReadiness\x12 .health.v1.ReadinessCheckRequest\x1a!.health.v1.ReadinessCheckResponse\x12N\n" +
	"\vWatchHealth\x12\x1d.health.v1.WatchHealthRequest\x1a\x1e.health.v1.WatchHealthResponse0\x01B\x98\x01\n" +
	"\rcom.health.v1B\x12HealthServiceProtoP\x01Z&github.com/jdfalk/gcommon/pkg/healthpb\xa2\x02\x03HXX\xaa\x02\tHealth.V1\xca\x02\tHealth\\V1\xe2\x02\x15Health\\V1\\GPBMetadata\xea\x02\n" +
	"Health::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_healthpb_v1_health_service_proto_goTypes = []any{
	(*HealthCheckRequest)(nil),     // 0: health.v1.HealthCheckRequest
	(*ReadinessCheckRequest)(nil),  // 1: health.v1.ReadinessCheckRequest
	(*WatchHealthRequest)(nil),     // 2: health.v1.WatchHealthRequest
	(*HealthCheckResponse)(nil),    // 3: health.v1.HealthCheckResponse
	(*ReadinessCheckResponse)(nil), // 4: health.v1.ReadinessCheckResponse
	(*WatchHealthResponse)(nil),    // 5: health.v1.WatchHealthResponse
}
var file_healthpb_v1_health_service_proto_depIdxs = []int32{
	0, // 0: health.v1.HealthService.Check:input_type -> health.v1.HealthCheckRequest
	1, // 1: health.v1.HealthService.CheckReadiness:input_type -> health.v1.ReadinessCheckRequest
	2, // 2: health.v1.HealthService.WatchHealth:input_type -> health.v1.WatchHealthRequest
	3, // 3: health.v1.HealthService.Check:output_type -> health.v1.HealthCheckResponse
	4, // 4: health.v1.HealthService.CheckReadiness:output_type -> health.v1.ReadinessCheckResponse
	5, // 5: health.v1.HealthService.WatchHealth:output_type -> health.v1.WatchHealthResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_healthpb_v1_health_service_proto_init() }
func file_healthpb_v1_health_service_proto_init() {
	if File_healthpb_v1_health_service_proto != nil {
		return
	}
	file_healthpb_v1_health_check_request_proto_init()
	file_healthpb_v1_readiness_check_request_proto_init()
	file_healthpb_v1_watch_health_request_proto_init()
	file_healthpb_v1_health_check_response_proto_init()
	file_healthpb_v1_readiness_check_response_proto_init()
	file_healthpb_v1_watch_health_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_healthpb_v1_health_service_proto_rawDesc), len(file_healthpb_v1_health_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_healthpb_v1_health_service_proto_goTypes,
		DependencyIndexes: file_healthpb_v1_health_service_proto_depIdxs,
	}.Build()
	File_healthpb_v1_health_service_proto = out.File
	file_healthpb_v1_health_service_proto_goTypes = nil
	file_healthpb_v1_health_service_proto_depIdxs = nil
}
