// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: metricspb/v2/list_metrics_response.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v2 "github.com/jdfalk/gcommon/pkg/commonpb/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// ListMetricsResponse lists available metrics.
type ListMetricsResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metrics *[]*MetricMetadata     `protobuf:"bytes,1,rep,name=metrics"`
	xxx_hidden_Error   *v2.Error              `protobuf:"bytes,2,opt,name=error"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListMetricsResponse) Reset() {
	*x = ListMetricsResponse{}
	mi := &file_metricspb_v2_list_metrics_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMetricsResponse) ProtoMessage() {}

func (x *ListMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metricspb_v2_list_metrics_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListMetricsResponse) GetMetrics() []*MetricMetadata {
	if x != nil {
		if x.xxx_hidden_Metrics != nil {
			return *x.xxx_hidden_Metrics
		}
	}
	return nil
}

func (x *ListMetricsResponse) GetError() *v2.Error {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return nil
}

func (x *ListMetricsResponse) SetMetrics(v []*MetricMetadata) {
	x.xxx_hidden_Metrics = &v
}

func (x *ListMetricsResponse) SetError(v *v2.Error) {
	x.xxx_hidden_Error = v
}

func (x *ListMetricsResponse) HasError() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Error != nil
}

func (x *ListMetricsResponse) ClearError() {
	x.xxx_hidden_Error = nil
}

type ListMetricsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Available metrics
	Metrics []*MetricMetadata
	// Error information
	Error *v2.Error
}

func (b0 ListMetricsResponse_builder) Build() *ListMetricsResponse {
	m0 := &ListMetricsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metrics = &b.Metrics
	x.xxx_hidden_Error = b.Error
	return m0
}

var File_metricspb_v2_list_metrics_response_proto protoreflect.FileDescriptor

const file_metricspb_v2_list_metrics_response_proto_rawDesc = "" +
	"\n" +
	"(metricspb/v2/list_metrics_response.proto\x12\n" +
	"metrics.v2\x1a\x17commonpb/v2/error.proto\x1a\"metricspb/v2/metric_metadata.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"}\n" +
	"\x13ListMetricsResponse\x12>\n" +
	"\ametrics\x18\x01 \x03(\v2\x1a.metrics.v2.MetricMetadataB\b\xbaH\x05\x92\x01\x02\b\x01R\ametrics\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x10.common.v2.ErrorR\x05errorB\xa7\x01\n" +
	"\x0ecom.metrics.v2B\x18ListMetricsResponseProtoP\x01Z*github.com/jdfalk/gcommon/pkg/metricspb/v2\xa2\x02\x03MXX\xaa\x02\n" +
	"Metrics.V2\xca\x02\n" +
	"Metrics\\V2\xe2\x02\x16Metrics\\V2\\GPBMetadata\xea\x02\vMetrics::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_metricspb_v2_list_metrics_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metricspb_v2_list_metrics_response_proto_goTypes = []any{
	(*ListMetricsResponse)(nil), // 0: metrics.v2.ListMetricsResponse
	(*MetricMetadata)(nil),      // 1: metrics.v2.MetricMetadata
	(*v2.Error)(nil),            // 2: common.v2.Error
}
var file_metricspb_v2_list_metrics_response_proto_depIdxs = []int32{
	1, // 0: metrics.v2.ListMetricsResponse.metrics:type_name -> metrics.v2.MetricMetadata
	2, // 1: metrics.v2.ListMetricsResponse.error:type_name -> common.v2.Error
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_metricspb_v2_list_metrics_response_proto_init() }
func file_metricspb_v2_list_metrics_response_proto_init() {
	if File_metricspb_v2_list_metrics_response_proto != nil {
		return
	}
	file_metricspb_v2_metric_metadata_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metricspb_v2_list_metrics_response_proto_rawDesc), len(file_metricspb_v2_list_metrics_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metricspb_v2_list_metrics_response_proto_goTypes,
		DependencyIndexes: file_metricspb_v2_list_metrics_response_proto_depIdxs,
		MessageInfos:      file_metricspb_v2_list_metrics_response_proto_msgTypes,
	}.Build()
	File_metricspb_v2_list_metrics_response_proto = out.File
	file_metricspb_v2_list_metrics_response_proto_goTypes = nil
	file_metricspb_v2_list_metrics_response_proto_depIdxs = nil
}
