// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: web/v1/update_middleware_config_request.proto

package web

import (
	common "github.com/jdfalk/gcommon/pkg/common/"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateMiddlewareConfigRequest struct {
	state               protoimpl.MessageState  `protogen:"opaque.v1"`
	xxx_hidden_Metadata *common.RequestMetadata `protobuf:"bytes,1,opt,name=metadata"`
	xxx_hidden_Config   *MiddlewareConfig       `protobuf:"bytes,2,opt,name=config"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *UpdateMiddlewareConfigRequest) Reset() {
	*x = UpdateMiddlewareConfigRequest{}
	mi := &file_web_v1_update_middleware_config_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMiddlewareConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMiddlewareConfigRequest) ProtoMessage() {}

func (x *UpdateMiddlewareConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_web_v1_update_middleware_config_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateMiddlewareConfigRequest) GetMetadata() *common.RequestMetadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *UpdateMiddlewareConfigRequest) GetConfig() *MiddlewareConfig {
	if x != nil {
		return x.xxx_hidden_Config
	}
	return nil
}

func (x *UpdateMiddlewareConfigRequest) SetMetadata(v *common.RequestMetadata) {
	x.xxx_hidden_Metadata = v
}

func (x *UpdateMiddlewareConfigRequest) SetConfig(v *MiddlewareConfig) {
	x.xxx_hidden_Config = v
}

func (x *UpdateMiddlewareConfigRequest) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *UpdateMiddlewareConfigRequest) HasConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Config != nil
}

func (x *UpdateMiddlewareConfigRequest) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *UpdateMiddlewareConfigRequest) ClearConfig() {
	x.xxx_hidden_Config = nil
}

type UpdateMiddlewareConfigRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Request metadata for tracing and auth
	Metadata *common.RequestMetadata
	// Updated middleware configuration
	Config *MiddlewareConfig
}

func (b0 UpdateMiddlewareConfigRequest_builder) Build() *UpdateMiddlewareConfigRequest {
	m0 := &UpdateMiddlewareConfigRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_Config = b.Config
	return m0
}

var File_web_v1_update_middleware_config_request_proto protoreflect.FileDescriptor

const file_web_v1_update_middleware_config_request_proto_rawDesc = "" +
	"\n" +
	"-web/v1/update_middleware_config_request.proto\x12\x06web.v1\x1a common/v1/request_metadata.proto\x1a\x1eweb/v1/middleware_config.proto\x1a!google/protobuf/go_features.proto\"\x89\x01\n" +
	"\x1dUpdateMiddlewareConfigRequest\x126\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1a.common.v1.RequestMetadataR\bmetadata\x120\n" +
	"\x06config\x18\x02 \x01(\v2\x18.web.v1.MiddlewareConfigR\x06configB,Z\"github.com/jdfalk/gcommon/pkg/web/\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_web_v1_update_middleware_config_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_web_v1_update_middleware_config_request_proto_goTypes = []any{
	(*UpdateMiddlewareConfigRequest)(nil), // 0: web.v1.UpdateMiddlewareConfigRequest
	(*common.RequestMetadata)(nil),        // 1: common.v1.RequestMetadata
	(*MiddlewareConfig)(nil),              // 2: web.v1.MiddlewareConfig
}
var file_web_v1_update_middleware_config_request_proto_depIdxs = []int32{
	1, // 0: web.v1.UpdateMiddlewareConfigRequest.metadata:type_name -> common.v1.RequestMetadata
	2, // 1: web.v1.UpdateMiddlewareConfigRequest.config:type_name -> web.v1.MiddlewareConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_web_v1_update_middleware_config_request_proto_init() }
func file_web_v1_update_middleware_config_request_proto_init() {
	if File_web_v1_update_middleware_config_request_proto != nil {
		return
	}
	file_web_v1_middleware_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_v1_update_middleware_config_request_proto_rawDesc), len(file_web_v1_update_middleware_config_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_web_v1_update_middleware_config_request_proto_goTypes,
		DependencyIndexes: file_web_v1_update_middleware_config_request_proto_depIdxs,
		MessageInfos:      file_web_v1_update_middleware_config_request_proto_msgTypes,
	}.Build()
	File_web_v1_update_middleware_config_request_proto = out.File
	file_web_v1_update_middleware_config_request_proto_goTypes = nil
	file_web_v1_update_middleware_config_request_proto_depIdxs = nil
}
