// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: metricspb/v1/record_summary_response.proto

package metricspb

import (
	commonpb "github.com/jdfalk/gcommon/pkg/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// RecordSummaryResponse returns updated summary stats.
type RecordSummaryResponse struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Metric *SummaryMetric         `protobuf:"bytes,1,opt,name=metric"`
	xxx_hidden_Stats  *RecordingStats        `protobuf:"bytes,2,opt,name=stats"`
	xxx_hidden_Error  *commonpb.Error        `protobuf:"bytes,3,opt,name=error"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RecordSummaryResponse) Reset() {
	*x = RecordSummaryResponse{}
	mi := &file_metricspb_v1_record_summary_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSummaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSummaryResponse) ProtoMessage() {}

func (x *RecordSummaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metricspb_v1_record_summary_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecordSummaryResponse) GetMetric() *SummaryMetric {
	if x != nil {
		return x.xxx_hidden_Metric
	}
	return nil
}

func (x *RecordSummaryResponse) GetStats() *RecordingStats {
	if x != nil {
		return x.xxx_hidden_Stats
	}
	return nil
}

func (x *RecordSummaryResponse) GetError() *commonpb.Error {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return nil
}

func (x *RecordSummaryResponse) SetMetric(v *SummaryMetric) {
	x.xxx_hidden_Metric = v
}

func (x *RecordSummaryResponse) SetStats(v *RecordingStats) {
	x.xxx_hidden_Stats = v
}

func (x *RecordSummaryResponse) SetError(v *commonpb.Error) {
	x.xxx_hidden_Error = v
}

func (x *RecordSummaryResponse) HasMetric() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metric != nil
}

func (x *RecordSummaryResponse) HasStats() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Stats != nil
}

func (x *RecordSummaryResponse) HasError() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Error != nil
}

func (x *RecordSummaryResponse) ClearMetric() {
	x.xxx_hidden_Metric = nil
}

func (x *RecordSummaryResponse) ClearStats() {
	x.xxx_hidden_Stats = nil
}

func (x *RecordSummaryResponse) ClearError() {
	x.xxx_hidden_Error = nil
}

type RecordSummaryResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Updated summary metric
	Metric *SummaryMetric
	// Processing stats
	Stats *RecordingStats
	// Error information
	Error *commonpb.Error
}

func (b0 RecordSummaryResponse_builder) Build() *RecordSummaryResponse {
	m0 := &RecordSummaryResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Metric = b.Metric
	x.xxx_hidden_Stats = b.Stats
	x.xxx_hidden_Error = b.Error
	return m0
}

var File_metricspb_v1_record_summary_response_proto protoreflect.FileDescriptor

const file_metricspb_v1_record_summary_response_proto_rawDesc = "" +
	"\n" +
	"*metricspb/v1/record_summary_response.proto\x12\n" +
	"metrics.v1\x1a\x17commonpb/v1/error.proto\x1a\"metricspb/v1/recording_stats.proto\x1a!metricspb/v1/summary_metric.proto\x1a!google/protobuf/go_features.proto\"\xa4\x01\n" +
	"\x15RecordSummaryResponse\x121\n" +
	"\x06metric\x18\x01 \x01(\v2\x19.metrics.v1.SummaryMetricR\x06metric\x120\n" +
	"\x05stats\x18\x02 \x01(\v2\x1a.metrics.v1.RecordingStatsR\x05stats\x12&\n" +
	"\x05error\x18\x03 \x01(\v2\x10.common.v1.ErrorR\x05errorB\xa6\x01\n" +
	"\x0ecom.metrics.v1B\x1aRecordSummaryResponseProtoP\x01Z'github.com/jdfalk/gcommon/pkg/metricspb\xa2\x02\x03MXX\xaa\x02\n" +
	"Metrics.V1\xca\x02\n" +
	"Metrics\\V1\xe2\x02\x16Metrics\\V1\\GPBMetadata\xea\x02\vMetrics::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_metricspb_v1_record_summary_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metricspb_v1_record_summary_response_proto_goTypes = []any{
	(*RecordSummaryResponse)(nil), // 0: metrics.v1.RecordSummaryResponse
	(*SummaryMetric)(nil),         // 1: metrics.v1.SummaryMetric
	(*RecordingStats)(nil),        // 2: metrics.v1.RecordingStats
	(*commonpb.Error)(nil),        // 3: common.v1.Error
}
var file_metricspb_v1_record_summary_response_proto_depIdxs = []int32{
	1, // 0: metrics.v1.RecordSummaryResponse.metric:type_name -> metrics.v1.SummaryMetric
	2, // 1: metrics.v1.RecordSummaryResponse.stats:type_name -> metrics.v1.RecordingStats
	3, // 2: metrics.v1.RecordSummaryResponse.error:type_name -> common.v1.Error
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_metricspb_v1_record_summary_response_proto_init() }
func file_metricspb_v1_record_summary_response_proto_init() {
	if File_metricspb_v1_record_summary_response_proto != nil {
		return
	}
	file_metricspb_v1_recording_stats_proto_init()
	file_metricspb_v1_summary_metric_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metricspb_v1_record_summary_response_proto_rawDesc), len(file_metricspb_v1_record_summary_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metricspb_v1_record_summary_response_proto_goTypes,
		DependencyIndexes: file_metricspb_v1_record_summary_response_proto_depIdxs,
		MessageInfos:      file_metricspb_v1_record_summary_response_proto_msgTypes,
	}.Build()
	File_metricspb_v1_record_summary_response_proto = out.File
	file_metricspb_v1_record_summary_response_proto_goTypes = nil
	file_metricspb_v1_record_summary_response_proto_depIdxs = nil
}
