// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: metricspb/v1/set_alerting_rules_request.proto

package metricspb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	commonpb "github.com/jdfalk/gcommon/pkg/commonpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetAlertingRulesRequest struct {
	state               protoimpl.MessageState    `protogen:"opaque.v1"`
	xxx_hidden_MetricId *string                   `protobuf:"bytes,1,opt,name=metric_id,json=metricId"`
	xxx_hidden_Rules    *[]*AlertingRule          `protobuf:"bytes,2,rep,name=rules"`
	xxx_hidden_Metadata *commonpb.RequestMetadata `protobuf:"bytes,3,opt,name=metadata"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SetAlertingRulesRequest) Reset() {
	*x = SetAlertingRulesRequest{}
	mi := &file_metricspb_v1_set_alerting_rules_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAlertingRulesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAlertingRulesRequest) ProtoMessage() {}

func (x *SetAlertingRulesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metricspb_v1_set_alerting_rules_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SetAlertingRulesRequest) GetMetricId() string {
	if x != nil {
		if x.xxx_hidden_MetricId != nil {
			return *x.xxx_hidden_MetricId
		}
		return ""
	}
	return ""
}

func (x *SetAlertingRulesRequest) GetRules() []*AlertingRule {
	if x != nil {
		if x.xxx_hidden_Rules != nil {
			return *x.xxx_hidden_Rules
		}
	}
	return nil
}

func (x *SetAlertingRulesRequest) GetMetadata() *commonpb.RequestMetadata {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Metadata) {
				protoimpl.X.UnmarshalField(x, 3)
			}
			var rv *commonpb.RequestMetadata
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Metadata), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *SetAlertingRulesRequest) SetMetricId(v string) {
	x.xxx_hidden_MetricId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *SetAlertingRulesRequest) SetRules(v []*AlertingRule) {
	x.xxx_hidden_Rules = &v
}

func (x *SetAlertingRulesRequest) SetMetadata(v *commonpb.RequestMetadata) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Metadata, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
	}
}

func (x *SetAlertingRulesRequest) HasMetricId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SetAlertingRulesRequest) HasMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *SetAlertingRulesRequest) ClearMetricId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MetricId = nil
}

func (x *SetAlertingRulesRequest) ClearMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Metadata, (*commonpb.RequestMetadata)(nil))
}

type SetAlertingRulesRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Metric identifier
	MetricId *string
	// Rules to set
	Rules []*AlertingRule
	// Request metadata
	Metadata *commonpb.RequestMetadata
}

func (b0 SetAlertingRulesRequest_builder) Build() *SetAlertingRulesRequest {
	m0 := &SetAlertingRulesRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MetricId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_MetricId = b.MetricId
	}
	x.xxx_hidden_Rules = &b.Rules
	if b.Metadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Metadata = b.Metadata
	}
	return m0
}

var File_metricspb_v1_set_alerting_rules_request_proto protoreflect.FileDescriptor

const file_metricspb_v1_set_alerting_rules_request_proto_rawDesc = "" +
	"\n" +
	"-metricspb/v1/set_alerting_rules_request.proto\x12\n" +
	"metrics.v1\x1a\"commonpb/v1/request_metadata.proto\x1a metricspb/v1/alerting_rule.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xb5\x01\n" +
	"\x17SetAlertingRulesRequest\x12$\n" +
	"\tmetric_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\bmetricId\x128\n" +
	"\x05rules\x18\x02 \x03(\v2\x18.metrics.v1.AlertingRuleB\b\xbaH\x05\x92\x01\x02\b\x01R\x05rules\x12:\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1a.common.v1.RequestMetadataB\x02(\x01R\bmetadataB\xa8\x01\n" +
	"\x0ecom.metrics.v1B\x1cSetAlertingRulesRequestProtoP\x01Z'github.com/jdfalk/gcommon/pkg/metricspb\xa2\x02\x03MXX\xaa\x02\n" +
	"Metrics.V1\xca\x02\n" +
	"Metrics\\V1\xe2\x02\x16Metrics\\V1\\GPBMetadata\xea\x02\vMetrics::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_metricspb_v1_set_alerting_rules_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metricspb_v1_set_alerting_rules_request_proto_goTypes = []any{
	(*SetAlertingRulesRequest)(nil),  // 0: metrics.v1.SetAlertingRulesRequest
	(*AlertingRule)(nil),             // 1: metrics.v1.AlertingRule
	(*commonpb.RequestMetadata)(nil), // 2: common.v1.RequestMetadata
}
var file_metricspb_v1_set_alerting_rules_request_proto_depIdxs = []int32{
	1, // 0: metrics.v1.SetAlertingRulesRequest.rules:type_name -> metrics.v1.AlertingRule
	2, // 1: metrics.v1.SetAlertingRulesRequest.metadata:type_name -> common.v1.RequestMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_metricspb_v1_set_alerting_rules_request_proto_init() }
func file_metricspb_v1_set_alerting_rules_request_proto_init() {
	if File_metricspb_v1_set_alerting_rules_request_proto != nil {
		return
	}
	file_metricspb_v1_alerting_rule_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metricspb_v1_set_alerting_rules_request_proto_rawDesc), len(file_metricspb_v1_set_alerting_rules_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metricspb_v1_set_alerting_rules_request_proto_goTypes,
		DependencyIndexes: file_metricspb_v1_set_alerting_rules_request_proto_depIdxs,
		MessageInfos:      file_metricspb_v1_set_alerting_rules_request_proto_msgTypes,
	}.Build()
	File_metricspb_v1_set_alerting_rules_request_proto = out.File
	file_metricspb_v1_set_alerting_rules_request_proto_goTypes = nil
	file_metricspb_v1_set_alerting_rules_request_proto_depIdxs = nil
}
