// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: commonpb/v2/health_status.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// buf:lint:ignore ENUM_VALUE_PREFIX
type CommonHealthStatus int32

const (
	// Default value indicating health status was not specified
	CommonHealthStatus_HEALTH_STATUS_UNSPECIFIED CommonHealthStatus = 0
	// Service/component is operating normally
	CommonHealthStatus_HEALTH_STATUS_HEALTHY CommonHealthStatus = 1
	// Service/component is not functioning properly
	CommonHealthStatus_HEALTH_STATUS_UNHEALTHY CommonHealthStatus = 2
	// Service/component is partially functioning with degraded performance
	CommonHealthStatus_HEALTH_STATUS_DEGRADED CommonHealthStatus = 3
	// Service/component is in the process of starting up
	CommonHealthStatus_HEALTH_STATUS_STARTING CommonHealthStatus = 4
	// Service/component is in the process of shutting down
	CommonHealthStatus_HEALTH_STATUS_STOPPING CommonHealthStatus = 5
)

// Enum value maps for CommonHealthStatus.
var (
	CommonHealthStatus_name = map[int32]string{
		0: "HEALTH_STATUS_UNSPECIFIED",
		1: "HEALTH_STATUS_HEALTHY",
		2: "HEALTH_STATUS_UNHEALTHY",
		3: "HEALTH_STATUS_DEGRADED",
		4: "HEALTH_STATUS_STARTING",
		5: "HEALTH_STATUS_STOPPING",
	}
	CommonHealthStatus_value = map[string]int32{
		"HEALTH_STATUS_UNSPECIFIED": 0,
		"HEALTH_STATUS_HEALTHY":     1,
		"HEALTH_STATUS_UNHEALTHY":   2,
		"HEALTH_STATUS_DEGRADED":    3,
		"HEALTH_STATUS_STARTING":    4,
		"HEALTH_STATUS_STOPPING":    5,
	}
)

func (x CommonHealthStatus) Enum() *CommonHealthStatus {
	p := new(CommonHealthStatus)
	*p = x
	return p
}

func (x CommonHealthStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommonHealthStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_commonpb_v2_health_status_proto_enumTypes[0].Descriptor()
}

func (CommonHealthStatus) Type() protoreflect.EnumType {
	return &file_commonpb_v2_health_status_proto_enumTypes[0]
}

func (x CommonHealthStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_commonpb_v2_health_status_proto protoreflect.FileDescriptor

const file_commonpb_v2_health_status_proto_rawDesc = "" +
	"\n" +
	"\x1fcommonpb/v2/health_status.proto\x12\tcommon.v2\x1a!google/protobuf/go_features.proto*\xbf\x01\n" +
	"\x12CommonHealthStatus\x12\x1d\n" +
	"\x19HEALTH_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15HEALTH_STATUS_HEALTHY\x10\x01\x12\x1b\n" +
	"\x17HEALTH_STATUS_UNHEALTHY\x10\x02\x12\x1a\n" +
	"\x16HEALTH_STATUS_DEGRADED\x10\x03\x12\x1a\n" +
	"\x16HEALTH_STATUS_STARTING\x10\x04\x12\x1a\n" +
	"\x16HEALTH_STATUS_STOPPING\x10\x05B\x9a\x01\n" +
	"\rcom.common.v2B\x11HealthStatusProtoP\x01Z)github.com/jdfalk/gcommon/pkg/commonpb/v2\xa2\x02\x03CXX\xaa\x02\tCommon.V2\xca\x02\tCommon\\V2\xe2\x02\x15Common\\V2\\GPBMetadata\xea\x02\n" +
	"Common::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_commonpb_v2_health_status_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commonpb_v2_health_status_proto_goTypes = []any{
	(CommonHealthStatus)(0), // 0: common.v2.CommonHealthStatus
}
var file_commonpb_v2_health_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commonpb_v2_health_status_proto_init() }
func file_commonpb_v2_health_status_proto_init() {
	if File_commonpb_v2_health_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonpb_v2_health_status_proto_rawDesc), len(file_commonpb_v2_health_status_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commonpb_v2_health_status_proto_goTypes,
		DependencyIndexes: file_commonpb_v2_health_status_proto_depIdxs,
		EnumInfos:         file_commonpb_v2_health_status_proto_enumTypes,
	}.Build()
	File_commonpb_v2_health_status_proto = out.File
	file_commonpb_v2_health_status_proto_goTypes = nil
	file_commonpb_v2_health_status_proto_depIdxs = nil
}
