// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: commonpb/v2/media_type.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Media type classification for library items.
type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNSPECIFIED MediaType = 0
	MediaType_MEDIA_TYPE_MOVIE       MediaType = 1
	MediaType_MEDIA_TYPE_TV_EPISODE  MediaType = 2
	MediaType_MEDIA_TYPE_DOCUMENTARY MediaType = 3
	MediaType_MEDIA_TYPE_ANIME       MediaType = 4
	MediaType_MEDIA_TYPE_AUDIOBOOK   MediaType = 5
	MediaType_MEDIA_TYPE_PODCAST     MediaType = 6
	MediaType_MEDIA_TYPE_MUSIC       MediaType = 7
	MediaType_MEDIA_TYPE_LECTURE     MediaType = 8
	MediaType_MEDIA_TYPE_INTERVIEW   MediaType = 9
	MediaType_MEDIA_TYPE_RADIO_SHOW  MediaType = 10
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0:  "MEDIA_TYPE_UNSPECIFIED",
		1:  "MEDIA_TYPE_MOVIE",
		2:  "MEDIA_TYPE_TV_EPISODE",
		3:  "MEDIA_TYPE_DOCUMENTARY",
		4:  "MEDIA_TYPE_ANIME",
		5:  "MEDIA_TYPE_AUDIOBOOK",
		6:  "MEDIA_TYPE_PODCAST",
		7:  "MEDIA_TYPE_MUSIC",
		8:  "MEDIA_TYPE_LECTURE",
		9:  "MEDIA_TYPE_INTERVIEW",
		10: "MEDIA_TYPE_RADIO_SHOW",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNSPECIFIED": 0,
		"MEDIA_TYPE_MOVIE":       1,
		"MEDIA_TYPE_TV_EPISODE":  2,
		"MEDIA_TYPE_DOCUMENTARY": 3,
		"MEDIA_TYPE_ANIME":       4,
		"MEDIA_TYPE_AUDIOBOOK":   5,
		"MEDIA_TYPE_PODCAST":     6,
		"MEDIA_TYPE_MUSIC":       7,
		"MEDIA_TYPE_LECTURE":     8,
		"MEDIA_TYPE_INTERVIEW":   9,
		"MEDIA_TYPE_RADIO_SHOW":  10,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_commonpb_v2_media_type_proto_enumTypes[0].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_commonpb_v2_media_type_proto_enumTypes[0]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_commonpb_v2_media_type_proto protoreflect.FileDescriptor

const file_commonpb_v2_media_type_proto_rawDesc = "" +
	"\n" +
	"\x1ccommonpb/v2/media_type.proto\x12\tcommon.v2\x1a!google/protobuf/go_features.proto*\x9f\x02\n" +
	"\tMediaType\x12\x1a\n" +
	"\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_MOVIE\x10\x01\x12\x19\n" +
	"\x15MEDIA_TYPE_TV_EPISODE\x10\x02\x12\x1a\n" +
	"\x16MEDIA_TYPE_DOCUMENTARY\x10\x03\x12\x14\n" +
	"\x10MEDIA_TYPE_ANIME\x10\x04\x12\x18\n" +
	"\x14MEDIA_TYPE_AUDIOBOOK\x10\x05\x12\x16\n" +
	"\x12MEDIA_TYPE_PODCAST\x10\x06\x12\x14\n" +
	"\x10MEDIA_TYPE_MUSIC\x10\a\x12\x16\n" +
	"\x12MEDIA_TYPE_LECTURE\x10\b\x12\x18\n" +
	"\x14MEDIA_TYPE_INTERVIEW\x10\t\x12\x19\n" +
	"\x15MEDIA_TYPE_RADIO_SHOW\x10\n" +
	"B\x97\x01\n" +
	"\rcom.common.v2B\x0eMediaTypeProtoP\x01Z)github.com/jdfalk/gcommon/pkg/commonpb/v2\xa2\x02\x03CXX\xaa\x02\tCommon.V2\xca\x02\tCommon\\V2\xe2\x02\x15Common\\V2\\GPBMetadata\xea\x02\n" +
	"Common::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_commonpb_v2_media_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commonpb_v2_media_type_proto_goTypes = []any{
	(MediaType)(0), // 0: common.v2.MediaType
}
var file_commonpb_v2_media_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commonpb_v2_media_type_proto_init() }
func file_commonpb_v2_media_type_proto_init() {
	if File_commonpb_v2_media_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonpb_v2_media_type_proto_rawDesc), len(file_commonpb_v2_media_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commonpb_v2_media_type_proto_goTypes,
		DependencyIndexes: file_commonpb_v2_media_type_proto_depIdxs,
		EnumInfos:         file_commonpb_v2_media_type_proto_enumTypes,
	}.Build()
	File_commonpb_v2_media_type_proto = out.File
	file_commonpb_v2_media_type_proto_goTypes = nil
	file_commonpb_v2_media_type_proto_depIdxs = nil
}
