// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: commonpb/v2/offset_type.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Types of offsets that can be retrieved.
// Defines different offset positions in a queue or partition.
type OffsetType int32

const (
	// Unspecified offset type
	OffsetType_OFFSET_TYPE_UNSPECIFIED OffsetType = 0
	// Earliest available offset
	OffsetType_OFFSET_TYPE_EARLIEST OffsetType = 1
	// Latest available offset
	OffsetType_OFFSET_TYPE_LATEST OffsetType = 2
	// Current consumer offset
	OffsetType_OFFSET_TYPE_CURRENT OffsetType = 3
	// Committed offset for consumer group
	OffsetType_OFFSET_TYPE_COMMITTED OffsetType = 4
)

// Enum value maps for OffsetType.
var (
	OffsetType_name = map[int32]string{
		0: "OFFSET_TYPE_UNSPECIFIED",
		1: "OFFSET_TYPE_EARLIEST",
		2: "OFFSET_TYPE_LATEST",
		3: "OFFSET_TYPE_CURRENT",
		4: "OFFSET_TYPE_COMMITTED",
	}
	OffsetType_value = map[string]int32{
		"OFFSET_TYPE_UNSPECIFIED": 0,
		"OFFSET_TYPE_EARLIEST":    1,
		"OFFSET_TYPE_LATEST":      2,
		"OFFSET_TYPE_CURRENT":     3,
		"OFFSET_TYPE_COMMITTED":   4,
	}
)

func (x OffsetType) Enum() *OffsetType {
	p := new(OffsetType)
	*p = x
	return p
}

func (x OffsetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OffsetType) Descriptor() protoreflect.EnumDescriptor {
	return file_commonpb_v2_offset_type_proto_enumTypes[0].Descriptor()
}

func (OffsetType) Type() protoreflect.EnumType {
	return &file_commonpb_v2_offset_type_proto_enumTypes[0]
}

func (x OffsetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_commonpb_v2_offset_type_proto protoreflect.FileDescriptor

const file_commonpb_v2_offset_type_proto_rawDesc = "" +
	"\n" +
	"\x1dcommonpb/v2/offset_type.proto\x12\tcommon.v2\x1a!google/protobuf/go_features.proto*\x8f\x01\n" +
	"\n" +
	"OffsetType\x12\x1b\n" +
	"\x17OFFSET_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14OFFSET_TYPE_EARLIEST\x10\x01\x12\x16\n" +
	"\x12OFFSET_TYPE_LATEST\x10\x02\x12\x17\n" +
	"\x13OFFSET_TYPE_CURRENT\x10\x03\x12\x19\n" +
	"\x15OFFSET_TYPE_COMMITTED\x10\x04B\x98\x01\n" +
	"\rcom.common.v2B\x0fOffsetTypeProtoP\x01Z)github.com/jdfalk/gcommon/pkg/commonpb/v2\xa2\x02\x03CXX\xaa\x02\tCommon.V2\xca\x02\tCommon\\V2\xe2\x02\x15Common\\V2\\GPBMetadata\xea\x02\n" +
	"Common::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_commonpb_v2_offset_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commonpb_v2_offset_type_proto_goTypes = []any{
	(OffsetType)(0), // 0: common.v2.OffsetType
}
var file_commonpb_v2_offset_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commonpb_v2_offset_type_proto_init() }
func file_commonpb_v2_offset_type_proto_init() {
	if File_commonpb_v2_offset_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonpb_v2_offset_type_proto_rawDesc), len(file_commonpb_v2_offset_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commonpb_v2_offset_type_proto_goTypes,
		DependencyIndexes: file_commonpb_v2_offset_type_proto_depIdxs,
		EnumInfos:         file_commonpb_v2_offset_type_proto_enumTypes,
	}.Build()
	File_commonpb_v2_offset_type_proto = out.File
	file_commonpb_v2_offset_type_proto_goTypes = nil
	file_commonpb_v2_offset_type_proto_depIdxs = nil
}
