// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: commonpb/v2/permission_type.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Permission categories for authorization decisions.
type PermissionType int32

const (
	// Unspecified permission type.
	PermissionType_PERMISSION_TYPE_UNSPECIFIED PermissionType = 0
	// Read-only access.
	PermissionType_PERMISSION_TYPE_READ PermissionType = 1
	// Write access.
	PermissionType_PERMISSION_TYPE_WRITE PermissionType = 2
	// Delete access.
	PermissionType_PERMISSION_TYPE_DELETE PermissionType = 3
	// Administrative privileges.
	PermissionType_PERMISSION_TYPE_ADMIN PermissionType = 4
	// Execute or run operations.
	PermissionType_PERMISSION_TYPE_EXECUTE PermissionType = 5
)

// Enum value maps for PermissionType.
var (
	PermissionType_name = map[int32]string{
		0: "PERMISSION_TYPE_UNSPECIFIED",
		1: "PERMISSION_TYPE_READ",
		2: "PERMISSION_TYPE_WRITE",
		3: "PERMISSION_TYPE_DELETE",
		4: "PERMISSION_TYPE_ADMIN",
		5: "PERMISSION_TYPE_EXECUTE",
	}
	PermissionType_value = map[string]int32{
		"PERMISSION_TYPE_UNSPECIFIED": 0,
		"PERMISSION_TYPE_READ":        1,
		"PERMISSION_TYPE_WRITE":       2,
		"PERMISSION_TYPE_DELETE":      3,
		"PERMISSION_TYPE_ADMIN":       4,
		"PERMISSION_TYPE_EXECUTE":     5,
	}
)

func (x PermissionType) Enum() *PermissionType {
	p := new(PermissionType)
	*p = x
	return p
}

func (x PermissionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PermissionType) Descriptor() protoreflect.EnumDescriptor {
	return file_commonpb_v2_permission_type_proto_enumTypes[0].Descriptor()
}

func (PermissionType) Type() protoreflect.EnumType {
	return &file_commonpb_v2_permission_type_proto_enumTypes[0]
}

func (x PermissionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

var File_commonpb_v2_permission_type_proto protoreflect.FileDescriptor

const file_commonpb_v2_permission_type_proto_rawDesc = "" +
	"\n" +
	"!commonpb/v2/permission_type.proto\x12\tcommon.v2\x1a!google/protobuf/go_features.proto*\xba\x01\n" +
	"\x0ePermissionType\x12\x1f\n" +
	"\x1bPERMISSION_TYPE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14PERMISSION_TYPE_READ\x10\x01\x12\x19\n" +
	"\x15PERMISSION_TYPE_WRITE\x10\x02\x12\x1a\n" +
	"\x16PERMISSION_TYPE_DELETE\x10\x03\x12\x19\n" +
	"\x15PERMISSION_TYPE_ADMIN\x10\x04\x12\x1b\n" +
	"\x17PERMISSION_TYPE_EXECUTE\x10\x05B\x9c\x01\n" +
	"\rcom.common.v2B\x13PermissionTypeProtoP\x01Z)github.com/jdfalk/gcommon/pkg/commonpb/v2\xa2\x02\x03CXX\xaa\x02\tCommon.V2\xca\x02\tCommon\\V2\xe2\x02\x15Common\\V2\\GPBMetadata\xea\x02\n" +
	"Common::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_commonpb_v2_permission_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_commonpb_v2_permission_type_proto_goTypes = []any{
	(PermissionType)(0), // 0: common.v2.PermissionType
}
var file_commonpb_v2_permission_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_commonpb_v2_permission_type_proto_init() }
func file_commonpb_v2_permission_type_proto_init() {
	if File_commonpb_v2_permission_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_commonpb_v2_permission_type_proto_rawDesc), len(file_commonpb_v2_permission_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_commonpb_v2_permission_type_proto_goTypes,
		DependencyIndexes: file_commonpb_v2_permission_type_proto_depIdxs,
		EnumInfos:         file_commonpb_v2_permission_type_proto_enumTypes,
	}.Build()
	File_commonpb_v2_permission_type_proto = out.File
	file_commonpb_v2_permission_type_proto_goTypes = nil
	file_commonpb_v2_permission_type_proto_depIdxs = nil
}
