// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: media/v1/media_processing_service.proto

package media

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_media_v1_media_processing_service_proto protoreflect.FileDescriptor

const file_media_v1_media_processing_service_proto_rawDesc = "" +
	"\n" +
	"'media/v1/media_processing_service.proto\x12\bmedia.v1\x1a$media/v1/analyze_media_request.proto\x1a%media/v1/analyze_media_response.proto\x1a$media/v1/extract_audio_request.proto\x1a%media/v1/extract_audio_response.proto\x1a(media/v1/extract_subtitles_request.proto\x1a)media/v1/extract_subtitles_response.proto\x1a,media/v1/get_processing_status_request.proto\x1a-media/v1/get_processing_status_response.proto\x1a&media/v1/transcode_media_request.proto\x1a'media/v1/transcode_media_response.proto\x1a!google/protobuf/go_features.proto2\xca\x03\n" +
	"\x16MediaProcessingService\x12S\n" +
	"\x0eTranscodeMedia\x12\x1f.media.v1.TranscodeMediaRequest\x1a .media.v1.TranscodeMediaResponse\x12M\n" +
	"\fAnalyzeMedia\x12\x1d.media.v1.AnalyzeMediaRequest\x1a\x1e.media.v1.AnalyzeMediaResponse\x12M\n" +
	"\fExtractAudio\x12\x1d.media.v1.ExtractAudioRequest\x1a\x1e.media.v1.ExtractAudioResponse\x12Y\n" +
	"\x10ExtractSubtitles\x12!.media.v1.ExtractSubtitlesRequest\x1a\".media.v1.ExtractSubtitlesResponse\x12b\n" +
	"\x13GetProcessingStatus\x12$.media.v1.GetProcessingStatusRequest\x1a%.media.v1.GetProcessingStatusResponseB.Z$github.com/jdfalk/gcommon/pkg/media/\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_media_v1_media_processing_service_proto_goTypes = []any{
	(*TranscodeMediaRequest)(nil),       // 0: media.v1.TranscodeMediaRequest
	(*AnalyzeMediaRequest)(nil),         // 1: media.v1.AnalyzeMediaRequest
	(*ExtractAudioRequest)(nil),         // 2: media.v1.ExtractAudioRequest
	(*ExtractSubtitlesRequest)(nil),     // 3: media.v1.ExtractSubtitlesRequest
	(*GetProcessingStatusRequest)(nil),  // 4: media.v1.GetProcessingStatusRequest
	(*TranscodeMediaResponse)(nil),      // 5: media.v1.TranscodeMediaResponse
	(*AnalyzeMediaResponse)(nil),        // 6: media.v1.AnalyzeMediaResponse
	(*ExtractAudioResponse)(nil),        // 7: media.v1.ExtractAudioResponse
	(*ExtractSubtitlesResponse)(nil),    // 8: media.v1.ExtractSubtitlesResponse
	(*GetProcessingStatusResponse)(nil), // 9: media.v1.GetProcessingStatusResponse
}
var file_media_v1_media_processing_service_proto_depIdxs = []int32{
	0, // 0: media.v1.MediaProcessingService.TranscodeMedia:input_type -> media.v1.TranscodeMediaRequest
	1, // 1: media.v1.MediaProcessingService.AnalyzeMedia:input_type -> media.v1.AnalyzeMediaRequest
	2, // 2: media.v1.MediaProcessingService.ExtractAudio:input_type -> media.v1.ExtractAudioRequest
	3, // 3: media.v1.MediaProcessingService.ExtractSubtitles:input_type -> media.v1.ExtractSubtitlesRequest
	4, // 4: media.v1.MediaProcessingService.GetProcessingStatus:input_type -> media.v1.GetProcessingStatusRequest
	5, // 5: media.v1.MediaProcessingService.TranscodeMedia:output_type -> media.v1.TranscodeMediaResponse
	6, // 6: media.v1.MediaProcessingService.AnalyzeMedia:output_type -> media.v1.AnalyzeMediaResponse
	7, // 7: media.v1.MediaProcessingService.ExtractAudio:output_type -> media.v1.ExtractAudioResponse
	8, // 8: media.v1.MediaProcessingService.ExtractSubtitles:output_type -> media.v1.ExtractSubtitlesResponse
	9, // 9: media.v1.MediaProcessingService.GetProcessingStatus:output_type -> media.v1.GetProcessingStatusResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_media_v1_media_processing_service_proto_init() }
func file_media_v1_media_processing_service_proto_init() {
	if File_media_v1_media_processing_service_proto != nil {
		return
	}
	file_media_v1_analyze_media_request_proto_init()
	file_media_v1_analyze_media_response_proto_init()
	file_media_v1_extract_audio_request_proto_init()
	file_media_v1_extract_audio_response_proto_init()
	file_media_v1_extract_subtitles_request_proto_init()
	file_media_v1_extract_subtitles_response_proto_init()
	file_media_v1_get_processing_status_request_proto_init()
	file_media_v1_get_processing_status_response_proto_init()
	file_media_v1_transcode_media_request_proto_init()
	file_media_v1_transcode_media_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v1_media_processing_service_proto_rawDesc), len(file_media_v1_media_processing_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_v1_media_processing_service_proto_goTypes,
		DependencyIndexes: file_media_v1_media_processing_service_proto_depIdxs,
	}.Build()
	File_media_v1_media_processing_service_proto = out.File
	file_media_v1_media_processing_service_proto_goTypes = nil
	file_media_v1_media_processing_service_proto_depIdxs = nil
}
