// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: media/v1/normalize_audio_request.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NormalizeAudioRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AudioFileId *string                `protobuf:"bytes,1,opt,name=audio_file_id,json=audioFileId"`
	xxx_hidden_Options     *NormalizationOptions  `protobuf:"bytes,2,opt,name=options"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *NormalizeAudioRequest) Reset() {
	*x = NormalizeAudioRequest{}
	mi := &file_media_v1_normalize_audio_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NormalizeAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NormalizeAudioRequest) ProtoMessage() {}

func (x *NormalizeAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_normalize_audio_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NormalizeAudioRequest) GetAudioFileId() string {
	if x != nil {
		if x.xxx_hidden_AudioFileId != nil {
			return *x.xxx_hidden_AudioFileId
		}
		return ""
	}
	return ""
}

func (x *NormalizeAudioRequest) GetOptions() *NormalizationOptions {
	if x != nil {
		return x.xxx_hidden_Options
	}
	return nil
}

func (x *NormalizeAudioRequest) SetAudioFileId(v string) {
	x.xxx_hidden_AudioFileId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *NormalizeAudioRequest) SetOptions(v *NormalizationOptions) {
	x.xxx_hidden_Options = v
}

func (x *NormalizeAudioRequest) HasAudioFileId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *NormalizeAudioRequest) HasOptions() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Options != nil
}

func (x *NormalizeAudioRequest) ClearAudioFileId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_AudioFileId = nil
}

func (x *NormalizeAudioRequest) ClearOptions() {
	x.xxx_hidden_Options = nil
}

type NormalizeAudioRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	AudioFileId *string
	Options     *NormalizationOptions
}

func (b0 NormalizeAudioRequest_builder) Build() *NormalizeAudioRequest {
	m0 := &NormalizeAudioRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.AudioFileId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_AudioFileId = b.AudioFileId
	}
	x.xxx_hidden_Options = b.Options
	return m0
}

var File_media_v1_normalize_audio_request_proto protoreflect.FileDescriptor

const file_media_v1_normalize_audio_request_proto_rawDesc = "" +
	"\n" +
	"&media/v1/normalize_audio_request.proto\x12\bmedia.v1\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\x1a$media/v1/normalization_options.proto\"~\n" +
	"\x15NormalizeAudioRequest\x12+\n" +
	"\raudio_file_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vaudioFileId\x128\n" +
	"\aoptions\x18\x02 \x01(\v2\x1e.media.v1.NormalizationOptionsR\aoptionsB,Z\"github.com/jdfalk/gcommon/media/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_media_v1_normalize_audio_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_media_v1_normalize_audio_request_proto_goTypes = []any{
	(*NormalizeAudioRequest)(nil), // 0: media.v1.NormalizeAudioRequest
	(*NormalizationOptions)(nil),  // 1: media.v1.NormalizationOptions
}
var file_media_v1_normalize_audio_request_proto_depIdxs = []int32{
	1, // 0: media.v1.NormalizeAudioRequest.options:type_name -> media.v1.NormalizationOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_media_v1_normalize_audio_request_proto_init() }
func file_media_v1_normalize_audio_request_proto_init() {
	if File_media_v1_normalize_audio_request_proto != nil {
		return
	}
	file_media_v1_normalization_options_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v1_normalize_audio_request_proto_rawDesc), len(file_media_v1_normalize_audio_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_v1_normalize_audio_request_proto_goTypes,
		DependencyIndexes: file_media_v1_normalize_audio_request_proto_depIdxs,
		MessageInfos:      file_media_v1_normalize_audio_request_proto_msgTypes,
	}.Build()
	File_media_v1_normalize_audio_request_proto = out.File
	file_media_v1_normalize_audio_request_proto_goTypes = nil
	file_media_v1_normalize_audio_request_proto_depIdxs = nil
}
