// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: media/v1/update_media_file_response.proto

package media

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Response from updating a media file.
type UpdateMediaFileResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MediaFile *MediaFile             `protobuf:"bytes,1,opt,name=media_file,json=mediaFile"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateMediaFileResponse) Reset() {
	*x = UpdateMediaFileResponse{}
	mi := &file_media_v1_update_media_file_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMediaFileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMediaFileResponse) ProtoMessage() {}

func (x *UpdateMediaFileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_v1_update_media_file_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateMediaFileResponse) GetMediaFile() *MediaFile {
	if x != nil {
		return x.xxx_hidden_MediaFile
	}
	return nil
}

func (x *UpdateMediaFileResponse) SetMediaFile(v *MediaFile) {
	x.xxx_hidden_MediaFile = v
}

func (x *UpdateMediaFileResponse) HasMediaFile() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MediaFile != nil
}

func (x *UpdateMediaFileResponse) ClearMediaFile() {
	x.xxx_hidden_MediaFile = nil
}

type UpdateMediaFileResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	MediaFile *MediaFile
}

func (b0 UpdateMediaFileResponse_builder) Build() *UpdateMediaFileResponse {
	m0 := &UpdateMediaFileResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MediaFile = b.MediaFile
	return m0
}

var File_media_v1_update_media_file_response_proto protoreflect.FileDescriptor

const file_media_v1_update_media_file_response_proto_rawDesc = "" +
	"\n" +
	")media/v1/update_media_file_response.proto\x12\bmedia.v1\x1a\x19media/v1/media_file.proto\x1a!google/protobuf/go_features.proto\"M\n" +
	"\x17UpdateMediaFileResponse\x122\n" +
	"\n" +
	"media_file\x18\x01 \x01(\v2\x13.media.v1.MediaFileR\tmediaFileB-Z#github.com/jdfalk/gcommon/pkg/media\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_media_v1_update_media_file_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_media_v1_update_media_file_response_proto_goTypes = []any{
	(*UpdateMediaFileResponse)(nil), // 0: media.v1.UpdateMediaFileResponse
	(*MediaFile)(nil),               // 1: media.v1.MediaFile
}
var file_media_v1_update_media_file_response_proto_depIdxs = []int32{
	1, // 0: media.v1.UpdateMediaFileResponse.media_file:type_name -> media.v1.MediaFile
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_media_v1_update_media_file_response_proto_init() }
func file_media_v1_update_media_file_response_proto_init() {
	if File_media_v1_update_media_file_response_proto != nil {
		return
	}
	file_media_v1_media_file_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v1_update_media_file_response_proto_rawDesc), len(file_media_v1_update_media_file_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_v1_update_media_file_response_proto_goTypes,
		DependencyIndexes: file_media_v1_update_media_file_response_proto_depIdxs,
		MessageInfos:      file_media_v1_update_media_file_response_proto_msgTypes,
	}.Build()
	File_media_v1_update_media_file_response_proto = out.File
	file_media_v1_update_media_file_response_proto_goTypes = nil
	file_media_v1_update_media_file_response_proto_depIdxs = nil
}
