// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: authpb/v2/list_api_keys_request.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListApiKeysRequest represents a request to list API keys for a user
type ListApiKeysRequest struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Page           int32                  `protobuf:"varint,1,opt,name=page"`
	xxx_hidden_PageSize       int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize"`
	xxx_hidden_IsActive       bool                   `protobuf:"varint,3,opt,name=is_active,json=isActive"`
	xxx_hidden_ExpiresBefore  int64                  `protobuf:"varint,4,opt,name=expires_before,json=expiresBefore"`
	xxx_hidden_ExpiresAfter   int64                  `protobuf:"varint,5,opt,name=expires_after,json=expiresAfter"`
	xxx_hidden_IncludeExpired bool                   `protobuf:"varint,6,opt,name=include_expired,json=includeExpired"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ListApiKeysRequest) Reset() {
	*x = ListApiKeysRequest{}
	mi := &file_authpb_v2_list_api_keys_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApiKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApiKeysRequest) ProtoMessage() {}

func (x *ListApiKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authpb_v2_list_api_keys_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListApiKeysRequest) GetPage() int32 {
	if x != nil {
		return x.xxx_hidden_Page
	}
	return 0
}

func (x *ListApiKeysRequest) GetPageSize() int32 {
	if x != nil {
		return x.xxx_hidden_PageSize
	}
	return 0
}

func (x *ListApiKeysRequest) GetIsActive() bool {
	if x != nil {
		return x.xxx_hidden_IsActive
	}
	return false
}

func (x *ListApiKeysRequest) GetExpiresBefore() int64 {
	if x != nil {
		return x.xxx_hidden_ExpiresBefore
	}
	return 0
}

func (x *ListApiKeysRequest) GetExpiresAfter() int64 {
	if x != nil {
		return x.xxx_hidden_ExpiresAfter
	}
	return 0
}

func (x *ListApiKeysRequest) GetIncludeExpired() bool {
	if x != nil {
		return x.xxx_hidden_IncludeExpired
	}
	return false
}

func (x *ListApiKeysRequest) SetPage(v int32) {
	x.xxx_hidden_Page = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *ListApiKeysRequest) SetPageSize(v int32) {
	x.xxx_hidden_PageSize = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *ListApiKeysRequest) SetIsActive(v bool) {
	x.xxx_hidden_IsActive = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *ListApiKeysRequest) SetExpiresBefore(v int64) {
	x.xxx_hidden_ExpiresBefore = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *ListApiKeysRequest) SetExpiresAfter(v int64) {
	x.xxx_hidden_ExpiresAfter = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *ListApiKeysRequest) SetIncludeExpired(v bool) {
	x.xxx_hidden_IncludeExpired = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 6)
}

func (x *ListApiKeysRequest) HasPage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListApiKeysRequest) HasPageSize() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListApiKeysRequest) HasIsActive() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ListApiKeysRequest) HasExpiresBefore() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ListApiKeysRequest) HasExpiresAfter() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ListApiKeysRequest) HasIncludeExpired() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *ListApiKeysRequest) ClearPage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Page = 0
}

func (x *ListApiKeysRequest) ClearPageSize() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PageSize = 0
}

func (x *ListApiKeysRequest) ClearIsActive() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_IsActive = false
}

func (x *ListApiKeysRequest) ClearExpiresBefore() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ExpiresBefore = 0
}

func (x *ListApiKeysRequest) ClearExpiresAfter() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ExpiresAfter = 0
}

func (x *ListApiKeysRequest) ClearIncludeExpired() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_IncludeExpired = false
}

type ListApiKeysRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Page number for pagination (starting from 1)
	Page *int32
	// Number of items per page
	PageSize *int32
	// Filter by active/inactive keys
	IsActive *bool
	// Filter by keys that expire before this timestamp
	ExpiresBefore *int64
	// Filter by keys that expire after this timestamp
	ExpiresAfter *int64
	// Include expired keys in the results
	IncludeExpired *bool
}

func (b0 ListApiKeysRequest_builder) Build() *ListApiKeysRequest {
	m0 := &ListApiKeysRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Page != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Page = *b.Page
	}
	if b.PageSize != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_PageSize = *b.PageSize
	}
	if b.IsActive != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_IsActive = *b.IsActive
	}
	if b.ExpiresBefore != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_ExpiresBefore = *b.ExpiresBefore
	}
	if b.ExpiresAfter != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_ExpiresAfter = *b.ExpiresAfter
	}
	if b.IncludeExpired != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 6)
		x.xxx_hidden_IncludeExpired = *b.IncludeExpired
	}
	return m0
}

var File_authpb_v2_list_api_keys_request_proto protoreflect.FileDescriptor

const file_authpb_v2_list_api_keys_request_proto_rawDesc = "" +
	"\n" +
	"%authpb/v2/list_api_keys_request.proto\x12\aauth.v2\x1a!google/protobuf/go_features.proto\"\xd7\x01\n" +
	"\x12ListApiKeysRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1b\n" +
	"\tis_active\x18\x03 \x01(\bR\bisActive\x12%\n" +
	"\x0eexpires_before\x18\x04 \x01(\x03R\rexpiresBefore\x12#\n" +
	"\rexpires_after\x18\x05 \x01(\x03R\fexpiresAfter\x12'\n" +
	"\x0finclude_expired\x18\x06 \x01(\bR\x0eincludeExpiredB\x91\x01\n" +
	"\vcom.auth.v2B\x17ListApiKeysRequestProtoP\x01Z$github.com/jdfalk/gcommon/pkg/authpb\xa2\x02\x03AXX\xaa\x02\aAuth.V2\xca\x02\aAuth\\V2\xe2\x02\x13Auth\\V2\\GPBMetadata\xea\x02\bAuth::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_authpb_v2_list_api_keys_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authpb_v2_list_api_keys_request_proto_goTypes = []any{
	(*ListApiKeysRequest)(nil), // 0: auth.v2.ListApiKeysRequest
}
var file_authpb_v2_list_api_keys_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authpb_v2_list_api_keys_request_proto_init() }
func file_authpb_v2_list_api_keys_request_proto_init() {
	if File_authpb_v2_list_api_keys_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authpb_v2_list_api_keys_request_proto_rawDesc), len(file_authpb_v2_list_api_keys_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authpb_v2_list_api_keys_request_proto_goTypes,
		DependencyIndexes: file_authpb_v2_list_api_keys_request_proto_depIdxs,
		MessageInfos:      file_authpb_v2_list_api_keys_request_proto_msgTypes,
	}.Build()
	File_authpb_v2_list_api_keys_request_proto = out.File
	file_authpb_v2_list_api_keys_request_proto_goTypes = nil
	file_authpb_v2_list_api_keys_request_proto_depIdxs = nil
}
