// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: authpb/v2/update_profile_response.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UpdateProfileResponse represents the response to a profile update request
type UpdateProfileResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status        AuthStatus             `protobuf:"varint,1,opt,name=status,enum=auth.v2.AuthStatus"`
	xxx_hidden_Profile       *UserProfile           `protobuf:"bytes,2,opt,name=profile"`
	xxx_hidden_UpdatedFields []string               `protobuf:"bytes,3,rep,name=updated_fields,json=updatedFields"`
	xxx_hidden_Message       *string                `protobuf:"bytes,4,opt,name=message"`
	xxx_hidden_ErrorMessage  *string                `protobuf:"bytes,5,opt,name=error_message,json=errorMessage"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *UpdateProfileResponse) Reset() {
	*x = UpdateProfileResponse{}
	mi := &file_authpb_v2_update_profile_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResponse) ProtoMessage() {}

func (x *UpdateProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authpb_v2_update_profile_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UpdateProfileResponse) GetStatus() AuthStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Status
		}
	}
	return AuthStatus_AUTH_STATUS_UNSPECIFIED
}

func (x *UpdateProfileResponse) GetProfile() *UserProfile {
	if x != nil {
		return x.xxx_hidden_Profile
	}
	return nil
}

func (x *UpdateProfileResponse) GetUpdatedFields() []string {
	if x != nil {
		return x.xxx_hidden_UpdatedFields
	}
	return nil
}

func (x *UpdateProfileResponse) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *UpdateProfileResponse) GetErrorMessage() string {
	if x != nil {
		if x.xxx_hidden_ErrorMessage != nil {
			return *x.xxx_hidden_ErrorMessage
		}
		return ""
	}
	return ""
}

func (x *UpdateProfileResponse) SetStatus(v AuthStatus) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *UpdateProfileResponse) SetProfile(v *UserProfile) {
	x.xxx_hidden_Profile = v
}

func (x *UpdateProfileResponse) SetUpdatedFields(v []string) {
	x.xxx_hidden_UpdatedFields = v
}

func (x *UpdateProfileResponse) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *UpdateProfileResponse) SetErrorMessage(v string) {
	x.xxx_hidden_ErrorMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *UpdateProfileResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UpdateProfileResponse) HasProfile() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Profile != nil
}

func (x *UpdateProfileResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UpdateProfileResponse) HasErrorMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *UpdateProfileResponse) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = AuthStatus_AUTH_STATUS_UNSPECIFIED
}

func (x *UpdateProfileResponse) ClearProfile() {
	x.xxx_hidden_Profile = nil
}

func (x *UpdateProfileResponse) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Message = nil
}

func (x *UpdateProfileResponse) ClearErrorMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ErrorMessage = nil
}

type UpdateProfileResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Operation status
	Status *AuthStatus
	// Updated user profile
	Profile *UserProfile
	// Fields that were actually updated
	UpdatedFields []string
	// Success message
	Message *string
	// Error message if update failed
	ErrorMessage *string
}

func (b0 UpdateProfileResponse_builder) Build() *UpdateProfileResponse {
	m0 := &UpdateProfileResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Status = *b.Status
	}
	x.xxx_hidden_Profile = b.Profile
	x.xxx_hidden_UpdatedFields = b.UpdatedFields
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Message = b.Message
	}
	if b.ErrorMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_ErrorMessage = b.ErrorMessage
	}
	return m0
}

var File_authpb_v2_update_profile_response_proto protoreflect.FileDescriptor

const file_authpb_v2_update_profile_response_proto_rawDesc = "" +
	"\n" +
	"'authpb/v2/update_profile_response.proto\x12\aauth.v2\x1a\x1bauthpb/v2/auth_status.proto\x1a!google/protobuf/go_features.proto\x1a%authpb/v2/user_profile_response.proto\"\xda\x01\n" +
	"\x15UpdateProfileResponse\x12+\n" +
	"\x06status\x18\x01 \x01(\x0e2\x13.auth.v2.AuthStatusR\x06status\x12.\n" +
	"\aprofile\x18\x02 \x01(\v2\x14.auth.v2.UserProfileR\aprofile\x12%\n" +
	"\x0eupdated_fields\x18\x03 \x03(\tR\rupdatedFields\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessageB\x94\x01\n" +
	"\vcom.auth.v2B\x1aUpdateProfileResponseProtoP\x01Z$github.com/jdfalk/gcommon/pkg/authpb\xa2\x02\x03AXX\xaa\x02\aAuth.V2\xca\x02\aAuth\\V2\xe2\x02\x13Auth\\V2\\GPBMetadata\xea\x02\bAuth::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_authpb_v2_update_profile_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authpb_v2_update_profile_response_proto_goTypes = []any{
	(*UpdateProfileResponse)(nil), // 0: auth.v2.UpdateProfileResponse
	(AuthStatus)(0),               // 1: auth.v2.AuthStatus
	(*UserProfile)(nil),           // 2: auth.v2.UserProfile
}
var file_authpb_v2_update_profile_response_proto_depIdxs = []int32{
	1, // 0: auth.v2.UpdateProfileResponse.status:type_name -> auth.v2.AuthStatus
	2, // 1: auth.v2.UpdateProfileResponse.profile:type_name -> auth.v2.UserProfile
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_authpb_v2_update_profile_response_proto_init() }
func file_authpb_v2_update_profile_response_proto_init() {
	if File_authpb_v2_update_profile_response_proto != nil {
		return
	}
	file_authpb_v2_auth_status_proto_init()
	file_authpb_v2_user_profile_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authpb_v2_update_profile_response_proto_rawDesc), len(file_authpb_v2_update_profile_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authpb_v2_update_profile_response_proto_goTypes,
		DependencyIndexes: file_authpb_v2_update_profile_response_proto_depIdxs,
		MessageInfos:      file_authpb_v2_update_profile_response_proto_msgTypes,
	}.Build()
	File_authpb_v2_update_profile_response_proto = out.File
	file_authpb_v2_update_profile_response_proto_goTypes = nil
	file_authpb_v2_update_profile_response_proto_depIdxs = nil
}
