// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: authpb/v2/user_profile_request.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// UserProfileRequest represents a request to get user profile information
type UserProfileRequest struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UserId               *string                `protobuf:"bytes,1,opt,name=user_id,json=userId"`
	xxx_hidden_IncludeSensitive     bool                   `protobuf:"varint,2,opt,name=include_sensitive,json=includeSensitive"`
	xxx_hidden_IncludeStats         bool                   `protobuf:"varint,3,opt,name=include_stats,json=includeStats"`
	xxx_hidden_IncludeOauthAccounts bool                   `protobuf:"varint,4,opt,name=include_oauth_accounts,json=includeOauthAccounts"`
	XXX_raceDetectHookData          protoimpl.RaceDetectHookData
	XXX_presence                    [1]uint32
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *UserProfileRequest) Reset() {
	*x = UserProfileRequest{}
	mi := &file_authpb_v2_user_profile_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserProfileRequest) ProtoMessage() {}

func (x *UserProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authpb_v2_user_profile_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserProfileRequest) GetUserId() string {
	if x != nil {
		if x.xxx_hidden_UserId != nil {
			return *x.xxx_hidden_UserId
		}
		return ""
	}
	return ""
}

func (x *UserProfileRequest) GetIncludeSensitive() bool {
	if x != nil {
		return x.xxx_hidden_IncludeSensitive
	}
	return false
}

func (x *UserProfileRequest) GetIncludeStats() bool {
	if x != nil {
		return x.xxx_hidden_IncludeStats
	}
	return false
}

func (x *UserProfileRequest) GetIncludeOauthAccounts() bool {
	if x != nil {
		return x.xxx_hidden_IncludeOauthAccounts
	}
	return false
}

func (x *UserProfileRequest) SetUserId(v string) {
	x.xxx_hidden_UserId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *UserProfileRequest) SetIncludeSensitive(v bool) {
	x.xxx_hidden_IncludeSensitive = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *UserProfileRequest) SetIncludeStats(v bool) {
	x.xxx_hidden_IncludeStats = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *UserProfileRequest) SetIncludeOauthAccounts(v bool) {
	x.xxx_hidden_IncludeOauthAccounts = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *UserProfileRequest) HasUserId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserProfileRequest) HasIncludeSensitive() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UserProfileRequest) HasIncludeStats() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *UserProfileRequest) HasIncludeOauthAccounts() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *UserProfileRequest) ClearUserId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_UserId = nil
}

func (x *UserProfileRequest) ClearIncludeSensitive() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_IncludeSensitive = false
}

func (x *UserProfileRequest) ClearIncludeStats() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_IncludeStats = false
}

func (x *UserProfileRequest) ClearIncludeOauthAccounts() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_IncludeOauthAccounts = false
}

type UserProfileRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// User ID to get profile for (if not provided, get current user)
	UserId *string
	// Whether to include sensitive information (requires admin permissions)
	IncludeSensitive *bool
	// Whether to include user statistics
	IncludeStats *bool
	// Whether to include linked OAuth accounts
	IncludeOauthAccounts *bool
}

func (b0 UserProfileRequest_builder) Build() *UserProfileRequest {
	m0 := &UserProfileRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.UserId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_UserId = b.UserId
	}
	if b.IncludeSensitive != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_IncludeSensitive = *b.IncludeSensitive
	}
	if b.IncludeStats != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_IncludeStats = *b.IncludeStats
	}
	if b.IncludeOauthAccounts != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_IncludeOauthAccounts = *b.IncludeOauthAccounts
	}
	return m0
}

var File_authpb_v2_user_profile_request_proto protoreflect.FileDescriptor

const file_authpb_v2_user_profile_request_proto_rawDesc = "" +
	"\n" +
	"$authpb/v2/user_profile_request.proto\x12\aauth.v2\x1a!google/protobuf/go_features.proto\"\xb5\x01\n" +
	"\x12UserProfileRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12+\n" +
	"\x11include_sensitive\x18\x02 \x01(\bR\x10includeSensitive\x12#\n" +
	"\rinclude_stats\x18\x03 \x01(\bR\fincludeStats\x124\n" +
	"\x16include_oauth_accounts\x18\x04 \x01(\bR\x14includeOauthAccountsB\x91\x01\n" +
	"\vcom.auth.v2B\x17UserProfileRequestProtoP\x01Z$github.com/jdfalk/gcommon/pkg/authpb\xa2\x02\x03AXX\xaa\x02\aAuth.V2\xca\x02\aAuth\\V2\xe2\x02\x13Auth\\V2\\GPBMetadata\xea\x02\bAuth::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_authpb_v2_user_profile_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authpb_v2_user_profile_request_proto_goTypes = []any{
	(*UserProfileRequest)(nil), // 0: auth.v2.UserProfileRequest
}
var file_authpb_v2_user_profile_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authpb_v2_user_profile_request_proto_init() }
func file_authpb_v2_user_profile_request_proto_init() {
	if File_authpb_v2_user_profile_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authpb_v2_user_profile_request_proto_rawDesc), len(file_authpb_v2_user_profile_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authpb_v2_user_profile_request_proto_goTypes,
		DependencyIndexes: file_authpb_v2_user_profile_request_proto_depIdxs,
		MessageInfos:      file_authpb_v2_user_profile_request_proto_msgTypes,
	}.Build()
	File_authpb_v2_user_profile_request_proto = out.File
	file_authpb_v2_user_profile_request_proto_goTypes = nil
	file_authpb_v2_user_profile_request_proto_depIdxs = nil
}
