// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: organization/v2/compute_isolation.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v2 "github.com/jdfalk/gcommon/common/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComputeIsolation struct {
	state                       protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_ComputeInstance  *string                        `protobuf:"bytes,1,opt,name=compute_instance,json=computeInstance"`
	xxx_hidden_Namespace        *string                        `protobuf:"bytes,2,opt,name=namespace"`
	xxx_hidden_Cpu              *CPUAllocation                 `protobuf:"bytes,3,opt,name=cpu"`
	xxx_hidden_Memory           *MemoryAllocation              `protobuf:"bytes,4,opt,name=memory"`
	xxx_hidden_DedicatedCompute bool                           `protobuf:"varint,5,opt,name=dedicated_compute,json=dedicatedCompute"`
	xxx_hidden_Limits           *v2.OrganizationResourceLimits `protobuf:"bytes,6,opt,name=limits"`
	xxx_hidden_AutoScaling      *AutoScalingConfig             `protobuf:"bytes,7,opt,name=auto_scaling,json=autoScaling"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ComputeIsolation) Reset() {
	*x = ComputeIsolation{}
	mi := &file_organization_v2_compute_isolation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComputeIsolation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComputeIsolation) ProtoMessage() {}

func (x *ComputeIsolation) ProtoReflect() protoreflect.Message {
	mi := &file_organization_v2_compute_isolation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ComputeIsolation) GetComputeInstance() string {
	if x != nil {
		if x.xxx_hidden_ComputeInstance != nil {
			return *x.xxx_hidden_ComputeInstance
		}
		return ""
	}
	return ""
}

func (x *ComputeIsolation) GetNamespace() string {
	if x != nil {
		if x.xxx_hidden_Namespace != nil {
			return *x.xxx_hidden_Namespace
		}
		return ""
	}
	return ""
}

func (x *ComputeIsolation) GetCpu() *CPUAllocation {
	if x != nil {
		return x.xxx_hidden_Cpu
	}
	return nil
}

func (x *ComputeIsolation) GetMemory() *MemoryAllocation {
	if x != nil {
		return x.xxx_hidden_Memory
	}
	return nil
}

func (x *ComputeIsolation) GetDedicatedCompute() bool {
	if x != nil {
		return x.xxx_hidden_DedicatedCompute
	}
	return false
}

func (x *ComputeIsolation) GetLimits() *v2.OrganizationResourceLimits {
	if x != nil {
		return x.xxx_hidden_Limits
	}
	return nil
}

func (x *ComputeIsolation) GetAutoScaling() *AutoScalingConfig {
	if x != nil {
		return x.xxx_hidden_AutoScaling
	}
	return nil
}

func (x *ComputeIsolation) SetComputeInstance(v string) {
	x.xxx_hidden_ComputeInstance = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *ComputeIsolation) SetNamespace(v string) {
	x.xxx_hidden_Namespace = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *ComputeIsolation) SetCpu(v *CPUAllocation) {
	x.xxx_hidden_Cpu = v
}

func (x *ComputeIsolation) SetMemory(v *MemoryAllocation) {
	x.xxx_hidden_Memory = v
}

func (x *ComputeIsolation) SetDedicatedCompute(v bool) {
	x.xxx_hidden_DedicatedCompute = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *ComputeIsolation) SetLimits(v *v2.OrganizationResourceLimits) {
	x.xxx_hidden_Limits = v
}

func (x *ComputeIsolation) SetAutoScaling(v *AutoScalingConfig) {
	x.xxx_hidden_AutoScaling = v
}

func (x *ComputeIsolation) HasComputeInstance() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ComputeIsolation) HasNamespace() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ComputeIsolation) HasCpu() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Cpu != nil
}

func (x *ComputeIsolation) HasMemory() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Memory != nil
}

func (x *ComputeIsolation) HasDedicatedCompute() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ComputeIsolation) HasLimits() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Limits != nil
}

func (x *ComputeIsolation) HasAutoScaling() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AutoScaling != nil
}

func (x *ComputeIsolation) ClearComputeInstance() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_ComputeInstance = nil
}

func (x *ComputeIsolation) ClearNamespace() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Namespace = nil
}

func (x *ComputeIsolation) ClearCpu() {
	x.xxx_hidden_Cpu = nil
}

func (x *ComputeIsolation) ClearMemory() {
	x.xxx_hidden_Memory = nil
}

func (x *ComputeIsolation) ClearDedicatedCompute() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_DedicatedCompute = false
}

func (x *ComputeIsolation) ClearLimits() {
	x.xxx_hidden_Limits = nil
}

func (x *ComputeIsolation) ClearAutoScaling() {
	x.xxx_hidden_AutoScaling = nil
}

type ComputeIsolation_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Dedicated compute instance identifier
	ComputeInstance *string
	// Container or namespace identifier
	Namespace *string
	// CPU allocation for this tenant
	Cpu *CPUAllocation
	// Memory allocation for this tenant
	Memory *MemoryAllocation
	// Whether tenant has dedicated compute resources
	DedicatedCompute *bool
	// Resource limits and quotas
	Limits *v2.OrganizationResourceLimits
	// Auto-scaling configuration
	AutoScaling *AutoScalingConfig
}

func (b0 ComputeIsolation_builder) Build() *ComputeIsolation {
	m0 := &ComputeIsolation{}
	b, x := &b0, m0
	_, _ = b, x
	if b.ComputeInstance != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_ComputeInstance = b.ComputeInstance
	}
	if b.Namespace != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Namespace = b.Namespace
	}
	x.xxx_hidden_Cpu = b.Cpu
	x.xxx_hidden_Memory = b.Memory
	if b.DedicatedCompute != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_DedicatedCompute = *b.DedicatedCompute
	}
	x.xxx_hidden_Limits = b.Limits
	x.xxx_hidden_AutoScaling = b.AutoScaling
	return m0
}

var File_organization_v2_compute_isolation_proto protoreflect.FileDescriptor

const file_organization_v2_compute_isolation_proto_rawDesc = "" +
	"\n" +
	"'organization/v2/compute_isolation.proto\x12\x0forganization.v2\x1a,common/v2/organization_resource_limits.proto\x1a)organization/v2/auto_scaling_config.proto\x1a$organization/v2/cpu_allocation.proto\x1a'organization/v2/memory_allocation.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\x8d\x03\n" +
	"\x10ComputeIsolation\x122\n" +
	"\x10compute_instance\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fcomputeInstance\x12%\n" +
	"\tnamespace\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\tnamespace\x120\n" +
	"\x03cpu\x18\x03 \x01(\v2\x1e.organization.v2.CPUAllocationR\x03cpu\x129\n" +
	"\x06memory\x18\x04 \x01(\v2!.organization.v2.MemoryAllocationR\x06memory\x12+\n" +
	"\x11dedicated_compute\x18\x05 \x01(\bR\x10dedicatedCompute\x12=\n" +
	"\x06limits\x18\x06 \x01(\v2%.common.v2.OrganizationResourceLimitsR\x06limits\x12E\n" +
	"\fauto_scaling\x18\a \x01(\v2\".organization.v2.AutoScalingConfigR\vautoScalingB3Z)github.com/jdfalk/gcommon/organization/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_organization_v2_compute_isolation_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_organization_v2_compute_isolation_proto_goTypes = []any{
	(*ComputeIsolation)(nil),              // 0: organization.v2.ComputeIsolation
	(*CPUAllocation)(nil),                 // 1: organization.v2.CPUAllocation
	(*MemoryAllocation)(nil),              // 2: organization.v2.MemoryAllocation
	(*v2.OrganizationResourceLimits)(nil), // 3: common.v2.OrganizationResourceLimits
	(*AutoScalingConfig)(nil),             // 4: organization.v2.AutoScalingConfig
}
var file_organization_v2_compute_isolation_proto_depIdxs = []int32{
	1, // 0: organization.v2.ComputeIsolation.cpu:type_name -> organization.v2.CPUAllocation
	2, // 1: organization.v2.ComputeIsolation.memory:type_name -> organization.v2.MemoryAllocation
	3, // 2: organization.v2.ComputeIsolation.limits:type_name -> common.v2.OrganizationResourceLimits
	4, // 3: organization.v2.ComputeIsolation.auto_scaling:type_name -> organization.v2.AutoScalingConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_organization_v2_compute_isolation_proto_init() }
func file_organization_v2_compute_isolation_proto_init() {
	if File_organization_v2_compute_isolation_proto != nil {
		return
	}
	file_organization_v2_auto_scaling_config_proto_init()
	file_organization_v2_cpu_allocation_proto_init()
	file_organization_v2_memory_allocation_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_v2_compute_isolation_proto_rawDesc), len(file_organization_v2_compute_isolation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organization_v2_compute_isolation_proto_goTypes,
		DependencyIndexes: file_organization_v2_compute_isolation_proto_depIdxs,
		MessageInfos:      file_organization_v2_compute_isolation_proto_msgTypes,
	}.Build()
	File_organization_v2_compute_isolation_proto = out.File
	file_organization_v2_compute_isolation_proto_goTypes = nil
	file_organization_v2_compute_isolation_proto_depIdxs = nil
}
