// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: organization/v2/load_balancer_config.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrganizationLoadBalancerConfig struct {
	state                  protoimpl.MessageState         `protogen:"opaque.v1"`
	xxx_hidden_Type        *string                        `protobuf:"bytes,1,opt,name=type"`
	xxx_hidden_Algorithm   *string                        `protobuf:"bytes,2,opt,name=algorithm"`
	xxx_hidden_HealthCheck *OrganizationHealthCheckConfig `protobuf:"bytes,3,opt,name=health_check,json=healthCheck"`
	xxx_hidden_Ssl         *SSLConfig                     `protobuf:"bytes,4,opt,name=ssl"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OrganizationLoadBalancerConfig) Reset() {
	*x = OrganizationLoadBalancerConfig{}
	mi := &file_organization_v2_load_balancer_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationLoadBalancerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationLoadBalancerConfig) ProtoMessage() {}

func (x *OrganizationLoadBalancerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_organization_v2_load_balancer_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OrganizationLoadBalancerConfig) GetType() string {
	if x != nil {
		if x.xxx_hidden_Type != nil {
			return *x.xxx_hidden_Type
		}
		return ""
	}
	return ""
}

func (x *OrganizationLoadBalancerConfig) GetAlgorithm() string {
	if x != nil {
		if x.xxx_hidden_Algorithm != nil {
			return *x.xxx_hidden_Algorithm
		}
		return ""
	}
	return ""
}

func (x *OrganizationLoadBalancerConfig) GetHealthCheck() *OrganizationHealthCheckConfig {
	if x != nil {
		return x.xxx_hidden_HealthCheck
	}
	return nil
}

func (x *OrganizationLoadBalancerConfig) GetSsl() *SSLConfig {
	if x != nil {
		return x.xxx_hidden_Ssl
	}
	return nil
}

func (x *OrganizationLoadBalancerConfig) SetType(v string) {
	x.xxx_hidden_Type = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *OrganizationLoadBalancerConfig) SetAlgorithm(v string) {
	x.xxx_hidden_Algorithm = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *OrganizationLoadBalancerConfig) SetHealthCheck(v *OrganizationHealthCheckConfig) {
	x.xxx_hidden_HealthCheck = v
}

func (x *OrganizationLoadBalancerConfig) SetSsl(v *SSLConfig) {
	x.xxx_hidden_Ssl = v
}

func (x *OrganizationLoadBalancerConfig) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OrganizationLoadBalancerConfig) HasAlgorithm() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OrganizationLoadBalancerConfig) HasHealthCheck() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_HealthCheck != nil
}

func (x *OrganizationLoadBalancerConfig) HasSsl() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ssl != nil
}

func (x *OrganizationLoadBalancerConfig) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = nil
}

func (x *OrganizationLoadBalancerConfig) ClearAlgorithm() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Algorithm = nil
}

func (x *OrganizationLoadBalancerConfig) ClearHealthCheck() {
	x.xxx_hidden_HealthCheck = nil
}

func (x *OrganizationLoadBalancerConfig) ClearSsl() {
	x.xxx_hidden_Ssl = nil
}

type OrganizationLoadBalancerConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Load balancer type (application, network)
	Type *string
	// Load balancing algorithm
	Algorithm *string
	// Health check configuration
	HealthCheck *OrganizationHealthCheckConfig
	// SSL/TLS configuration
	Ssl *SSLConfig
}

func (b0 OrganizationLoadBalancerConfig_builder) Build() *OrganizationLoadBalancerConfig {
	m0 := &OrganizationLoadBalancerConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Type = b.Type
	}
	if b.Algorithm != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Algorithm = b.Algorithm
	}
	x.xxx_hidden_HealthCheck = b.HealthCheck
	x.xxx_hidden_Ssl = b.Ssl
	return m0
}

var File_organization_v2_load_balancer_config_proto protoreflect.FileDescriptor

const file_organization_v2_load_balancer_config_proto_rawDesc = "" +
	"\n" +
	"*organization/v2/load_balancer_config.proto\x12\x0forganization.v2\x1a)organization/v2/health_check_config.proto\x1a organization/v2/ssl_config.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xe5\x01\n" +
	"\x1eOrganizationLoadBalancerConfig\x12\x1b\n" +
	"\x04type\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04type\x12%\n" +
	"\talgorithm\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\talgorithm\x12Q\n" +
	"\fhealth_check\x18\x03 \x01(\v2..organization.v2.OrganizationHealthCheckConfigR\vhealthCheck\x12,\n" +
	"\x03ssl\x18\x04 \x01(\v2\x1a.organization.v2.SSLConfigR\x03sslB3Z)github.com/jdfalk/gcommon/organization/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_organization_v2_load_balancer_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_organization_v2_load_balancer_config_proto_goTypes = []any{
	(*OrganizationLoadBalancerConfig)(nil), // 0: organization.v2.OrganizationLoadBalancerConfig
	(*OrganizationHealthCheckConfig)(nil),  // 1: organization.v2.OrganizationHealthCheckConfig
	(*SSLConfig)(nil),                      // 2: organization.v2.SSLConfig
}
var file_organization_v2_load_balancer_config_proto_depIdxs = []int32{
	1, // 0: organization.v2.OrganizationLoadBalancerConfig.health_check:type_name -> organization.v2.OrganizationHealthCheckConfig
	2, // 1: organization.v2.OrganizationLoadBalancerConfig.ssl:type_name -> organization.v2.SSLConfig
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_organization_v2_load_balancer_config_proto_init() }
func file_organization_v2_load_balancer_config_proto_init() {
	if File_organization_v2_load_balancer_config_proto != nil {
		return
	}
	file_organization_v2_health_check_config_proto_init()
	file_organization_v2_ssl_config_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_v2_load_balancer_config_proto_rawDesc), len(file_organization_v2_load_balancer_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organization_v2_load_balancer_config_proto_goTypes,
		DependencyIndexes: file_organization_v2_load_balancer_config_proto_depIdxs,
		MessageInfos:      file_organization_v2_load_balancer_config_proto_msgTypes,
	}.Build()
	File_organization_v2_load_balancer_config_proto = out.File
	file_organization_v2_load_balancer_config_proto_goTypes = nil
	file_organization_v2_load_balancer_config_proto_depIdxs = nil
}
