// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: organization/v2/organization_settings.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v2 "github.com/jdfalk/gcommon/common/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrganizationSettings struct {
	state                     protoimpl.MessageState               `protogen:"opaque.v1"`
	xxx_hidden_OrganizationId *string                              `protobuf:"bytes,1,opt,name=organization_id,json=organizationId"`
	xxx_hidden_Security       *SecuritySettings                    `protobuf:"bytes,2,opt,name=security"`
	xxx_hidden_Ui             *UISettings                          `protobuf:"bytes,3,opt,name=ui"`
	xxx_hidden_Integrations   *IntegrationSettings                 `protobuf:"bytes,4,opt,name=integrations"`
	xxx_hidden_Notifications  *v2.OrganizationNotificationSettings `protobuf:"bytes,5,opt,name=notifications"`
	xxx_hidden_Billing        *BillingSettings                     `protobuf:"bytes,6,opt,name=billing"`
	xxx_hidden_Compliance     *v2.OrganizationComplianceSettings   `protobuf:"bytes,7,opt,name=compliance"`
	xxx_hidden_FeatureFlags   *[]*FeatureFlag                      `protobuf:"bytes,8,rep,name=feature_flags,json=featureFlags"`
	xxx_hidden_CustomSettings *[]*v2.KeyValue                      `protobuf:"bytes,9,rep,name=custom_settings,json=customSettings"`
	xxx_hidden_UpdatedAt      *timestamppb.Timestamp               `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_UpdatedBy      *string                              `protobuf:"bytes,11,opt,name=updated_by,json=updatedBy"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *OrganizationSettings) Reset() {
	*x = OrganizationSettings{}
	mi := &file_organization_v2_organization_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrganizationSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrganizationSettings) ProtoMessage() {}

func (x *OrganizationSettings) ProtoReflect() protoreflect.Message {
	mi := &file_organization_v2_organization_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OrganizationSettings) GetOrganizationId() string {
	if x != nil {
		if x.xxx_hidden_OrganizationId != nil {
			return *x.xxx_hidden_OrganizationId
		}
		return ""
	}
	return ""
}

func (x *OrganizationSettings) GetSecurity() *SecuritySettings {
	if x != nil {
		return x.xxx_hidden_Security
	}
	return nil
}

func (x *OrganizationSettings) GetUi() *UISettings {
	if x != nil {
		return x.xxx_hidden_Ui
	}
	return nil
}

func (x *OrganizationSettings) GetIntegrations() *IntegrationSettings {
	if x != nil {
		return x.xxx_hidden_Integrations
	}
	return nil
}

func (x *OrganizationSettings) GetNotifications() *v2.OrganizationNotificationSettings {
	if x != nil {
		return x.xxx_hidden_Notifications
	}
	return nil
}

func (x *OrganizationSettings) GetBilling() *BillingSettings {
	if x != nil {
		return x.xxx_hidden_Billing
	}
	return nil
}

func (x *OrganizationSettings) GetCompliance() *v2.OrganizationComplianceSettings {
	if x != nil {
		return x.xxx_hidden_Compliance
	}
	return nil
}

func (x *OrganizationSettings) GetFeatureFlags() []*FeatureFlag {
	if x != nil {
		if x.xxx_hidden_FeatureFlags != nil {
			return *x.xxx_hidden_FeatureFlags
		}
	}
	return nil
}

func (x *OrganizationSettings) GetCustomSettings() []*v2.KeyValue {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 8) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_CustomSettings) {
				protoimpl.X.UnmarshalField(x, 9)
			}
			var rv *[]*v2.KeyValue
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_CustomSettings), protoimpl.Pointer(&rv))
			return *rv
		}
	}
	return nil
}

func (x *OrganizationSettings) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 9) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_UpdatedAt) {
				protoimpl.X.UnmarshalField(x, 10)
			}
			var rv *timestamppb.Timestamp
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_UpdatedAt), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *OrganizationSettings) GetUpdatedBy() string {
	if x != nil {
		if x.xxx_hidden_UpdatedBy != nil {
			return *x.xxx_hidden_UpdatedBy
		}
		return ""
	}
	return ""
}

func (x *OrganizationSettings) SetOrganizationId(v string) {
	x.xxx_hidden_OrganizationId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 11)
}

func (x *OrganizationSettings) SetSecurity(v *SecuritySettings) {
	x.xxx_hidden_Security = v
}

func (x *OrganizationSettings) SetUi(v *UISettings) {
	x.xxx_hidden_Ui = v
}

func (x *OrganizationSettings) SetIntegrations(v *IntegrationSettings) {
	x.xxx_hidden_Integrations = v
}

func (x *OrganizationSettings) SetNotifications(v *v2.OrganizationNotificationSettings) {
	x.xxx_hidden_Notifications = v
}

func (x *OrganizationSettings) SetBilling(v *BillingSettings) {
	x.xxx_hidden_Billing = v
}

func (x *OrganizationSettings) SetCompliance(v *v2.OrganizationComplianceSettings) {
	x.xxx_hidden_Compliance = v
}

func (x *OrganizationSettings) SetFeatureFlags(v []*FeatureFlag) {
	x.xxx_hidden_FeatureFlags = &v
}

func (x *OrganizationSettings) SetCustomSettings(v []*v2.KeyValue) {
	var sv *[]*v2.KeyValue
	protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_CustomSettings), protoimpl.Pointer(&sv))
	if sv == nil {
		sv = &[]*v2.KeyValue{}
		protoimpl.X.AtomicInitializePointer(protoimpl.Pointer(&x.xxx_hidden_CustomSettings), protoimpl.Pointer(&sv))
	}
	*sv = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 11)
}

func (x *OrganizationSettings) SetUpdatedAt(v *timestamppb.Timestamp) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_UpdatedAt, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 11)
	}
}

func (x *OrganizationSettings) SetUpdatedBy(v string) {
	x.xxx_hidden_UpdatedBy = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 10, 11)
}

func (x *OrganizationSettings) HasOrganizationId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OrganizationSettings) HasSecurity() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Security != nil
}

func (x *OrganizationSettings) HasUi() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Ui != nil
}

func (x *OrganizationSettings) HasIntegrations() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Integrations != nil
}

func (x *OrganizationSettings) HasNotifications() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Notifications != nil
}

func (x *OrganizationSettings) HasBilling() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Billing != nil
}

func (x *OrganizationSettings) HasCompliance() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Compliance != nil
}

func (x *OrganizationSettings) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *OrganizationSettings) HasUpdatedBy() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 10)
}

func (x *OrganizationSettings) ClearOrganizationId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_OrganizationId = nil
}

func (x *OrganizationSettings) ClearSecurity() {
	x.xxx_hidden_Security = nil
}

func (x *OrganizationSettings) ClearUi() {
	x.xxx_hidden_Ui = nil
}

func (x *OrganizationSettings) ClearIntegrations() {
	x.xxx_hidden_Integrations = nil
}

func (x *OrganizationSettings) ClearNotifications() {
	x.xxx_hidden_Notifications = nil
}

func (x *OrganizationSettings) ClearBilling() {
	x.xxx_hidden_Billing = nil
}

func (x *OrganizationSettings) ClearCompliance() {
	x.xxx_hidden_Compliance = nil
}

func (x *OrganizationSettings) ClearUpdatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_UpdatedAt, (*timestamppb.Timestamp)(nil))
}

func (x *OrganizationSettings) ClearUpdatedBy() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 10)
	x.xxx_hidden_UpdatedBy = nil
}

type OrganizationSettings_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Organization identifier
	OrganizationId *string
	// Security and authentication settings
	Security *SecuritySettings
	// User interface and experience settings
	Ui *UISettings
	// Integration and API settings
	Integrations *IntegrationSettings
	// Notification and communication settings
	Notifications *v2.OrganizationNotificationSettings
	// Billing and subscription settings
	Billing *BillingSettings
	// Data retention and compliance settings
	Compliance *v2.OrganizationComplianceSettings
	// Feature flags and experimental features
	FeatureFlags []*FeatureFlag
	// Custom organization-specific settings
	CustomSettings []*v2.KeyValue
	// Settings last update timestamp
	UpdatedAt *timestamppb.Timestamp
	// User ID who last updated these settings
	UpdatedBy *string
}

func (b0 OrganizationSettings_builder) Build() *OrganizationSettings {
	m0 := &OrganizationSettings{}
	b, x := &b0, m0
	_, _ = b, x
	if b.OrganizationId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 11)
		x.xxx_hidden_OrganizationId = b.OrganizationId
	}
	x.xxx_hidden_Security = b.Security
	x.xxx_hidden_Ui = b.Ui
	x.xxx_hidden_Integrations = b.Integrations
	x.xxx_hidden_Notifications = b.Notifications
	x.xxx_hidden_Billing = b.Billing
	x.xxx_hidden_Compliance = b.Compliance
	x.xxx_hidden_FeatureFlags = &b.FeatureFlags
	if b.CustomSettings != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 11)
		x.xxx_hidden_CustomSettings = &b.CustomSettings
	}
	if b.UpdatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 11)
		x.xxx_hidden_UpdatedAt = b.UpdatedAt
	}
	if b.UpdatedBy != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 10, 11)
		x.xxx_hidden_UpdatedBy = b.UpdatedBy
	}
	return m0
}

var File_organization_v2_organization_settings_proto protoreflect.FileDescriptor

const file_organization_v2_organization_settings_proto_rawDesc = "" +
	"\n" +
	"+organization/v2/organization_settings.proto\x12\x0forganization.v2\x1a\x19common/v2/key_value.proto\x1a0common/v2/organization_compliance_settings.proto\x1a2common/v2/organization_notification_settings.proto\x1a&organization/v2/billing_settings.proto\x1a\"organization/v2/feature_flag.proto\x1a*organization/v2/integration_settings.proto\x1a'organization/v2/security_settings.proto\x1a!organization/v2/ui_settings.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xe2\x06\n" +
	"\x14OrganizationSettings\x12\x80\x01\n" +
	"\x0forganization_id\x18\x01 \x01(\tBW\xbaHT\xc8\x01\x01rO2M^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$R\x0eorganizationId\x12=\n" +
	"\bsecurity\x18\x02 \x01(\v2!.organization.v2.SecuritySettingsR\bsecurity\x12+\n" +
	"\x02ui\x18\x03 \x01(\v2\x1b.organization.v2.UISettingsR\x02ui\x12H\n" +
	"\fintegrations\x18\x04 \x01(\v2$.organization.v2.IntegrationSettingsR\fintegrations\x12Q\n" +
	"\rnotifications\x18\x05 \x01(\v2+.common.v2.OrganizationNotificationSettingsR\rnotifications\x12:\n" +
	"\abilling\x18\x06 \x01(\v2 .organization.v2.BillingSettingsR\abilling\x12I\n" +
	"\n" +
	"compliance\x18\a \x01(\v2).common.v2.OrganizationComplianceSettingsR\n" +
	"compliance\x12A\n" +
	"\rfeature_flags\x18\b \x03(\v2\x1c.organization.v2.FeatureFlagR\ffeatureFlags\x12@\n" +
	"\x0fcustom_settings\x18\t \x03(\v2\x13.common.v2.KeyValueB\x02(\x01R\x0ecustomSettings\x12=\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\x02(\x01R\tupdatedAt\x12s\n" +
	"\n" +
	"updated_by\x18\v \x01(\tBT\xbaHQrO2M^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$R\tupdatedByB3Z)github.com/jdfalk/gcommon/organization/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_organization_v2_organization_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_organization_v2_organization_settings_proto_goTypes = []any{
	(*OrganizationSettings)(nil),                // 0: organization.v2.OrganizationSettings
	(*SecuritySettings)(nil),                    // 1: organization.v2.SecuritySettings
	(*UISettings)(nil),                          // 2: organization.v2.UISettings
	(*IntegrationSettings)(nil),                 // 3: organization.v2.IntegrationSettings
	(*v2.OrganizationNotificationSettings)(nil), // 4: common.v2.OrganizationNotificationSettings
	(*BillingSettings)(nil),                     // 5: organization.v2.BillingSettings
	(*v2.OrganizationComplianceSettings)(nil),   // 6: common.v2.OrganizationComplianceSettings
	(*FeatureFlag)(nil),                         // 7: organization.v2.FeatureFlag
	(*v2.KeyValue)(nil),                         // 8: common.v2.KeyValue
	(*timestamppb.Timestamp)(nil),               // 9: google.protobuf.Timestamp
}
var file_organization_v2_organization_settings_proto_depIdxs = []int32{
	1, // 0: organization.v2.OrganizationSettings.security:type_name -> organization.v2.SecuritySettings
	2, // 1: organization.v2.OrganizationSettings.ui:type_name -> organization.v2.UISettings
	3, // 2: organization.v2.OrganizationSettings.integrations:type_name -> organization.v2.IntegrationSettings
	4, // 3: organization.v2.OrganizationSettings.notifications:type_name -> common.v2.OrganizationNotificationSettings
	5, // 4: organization.v2.OrganizationSettings.billing:type_name -> organization.v2.BillingSettings
	6, // 5: organization.v2.OrganizationSettings.compliance:type_name -> common.v2.OrganizationComplianceSettings
	7, // 6: organization.v2.OrganizationSettings.feature_flags:type_name -> organization.v2.FeatureFlag
	8, // 7: organization.v2.OrganizationSettings.custom_settings:type_name -> common.v2.KeyValue
	9, // 8: organization.v2.OrganizationSettings.updated_at:type_name -> google.protobuf.Timestamp
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_organization_v2_organization_settings_proto_init() }
func file_organization_v2_organization_settings_proto_init() {
	if File_organization_v2_organization_settings_proto != nil {
		return
	}
	file_organization_v2_billing_settings_proto_init()
	file_organization_v2_feature_flag_proto_init()
	file_organization_v2_integration_settings_proto_init()
	file_organization_v2_security_settings_proto_init()
	file_organization_v2_ui_settings_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_v2_organization_settings_proto_rawDesc), len(file_organization_v2_organization_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organization_v2_organization_settings_proto_goTypes,
		DependencyIndexes: file_organization_v2_organization_settings_proto_depIdxs,
		MessageInfos:      file_organization_v2_organization_settings_proto_msgTypes,
	}.Build()
	File_organization_v2_organization_settings_proto = out.File
	file_organization_v2_organization_settings_proto_goTypes = nil
	file_organization_v2_organization_settings_proto_depIdxs = nil
}
