// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: organization/v2/origin_config.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v2 "github.com/jdfalk/gcommon/common/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OriginConfig struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DomainName     *string                `protobuf:"bytes,1,opt,name=domain_name,json=domainName"`
	xxx_hidden_OriginPath     *string                `protobuf:"bytes,2,opt,name=origin_path,json=originPath"`
	xxx_hidden_ProtocolPolicy *string                `protobuf:"bytes,3,opt,name=protocol_policy,json=protocolPolicy"`
	xxx_hidden_CustomHeaders  *[]*v2.KeyValue        `protobuf:"bytes,4,rep,name=custom_headers,json=customHeaders"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *OriginConfig) Reset() {
	*x = OriginConfig{}
	mi := &file_organization_v2_origin_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OriginConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OriginConfig) ProtoMessage() {}

func (x *OriginConfig) ProtoReflect() protoreflect.Message {
	mi := &file_organization_v2_origin_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OriginConfig) GetDomainName() string {
	if x != nil {
		if x.xxx_hidden_DomainName != nil {
			return *x.xxx_hidden_DomainName
		}
		return ""
	}
	return ""
}

func (x *OriginConfig) GetOriginPath() string {
	if x != nil {
		if x.xxx_hidden_OriginPath != nil {
			return *x.xxx_hidden_OriginPath
		}
		return ""
	}
	return ""
}

func (x *OriginConfig) GetProtocolPolicy() string {
	if x != nil {
		if x.xxx_hidden_ProtocolPolicy != nil {
			return *x.xxx_hidden_ProtocolPolicy
		}
		return ""
	}
	return ""
}

func (x *OriginConfig) GetCustomHeaders() []*v2.KeyValue {
	if x != nil {
		if x.xxx_hidden_CustomHeaders != nil {
			return *x.xxx_hidden_CustomHeaders
		}
	}
	return nil
}

func (x *OriginConfig) SetDomainName(v string) {
	x.xxx_hidden_DomainName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *OriginConfig) SetOriginPath(v string) {
	x.xxx_hidden_OriginPath = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *OriginConfig) SetProtocolPolicy(v string) {
	x.xxx_hidden_ProtocolPolicy = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *OriginConfig) SetCustomHeaders(v []*v2.KeyValue) {
	x.xxx_hidden_CustomHeaders = &v
}

func (x *OriginConfig) HasDomainName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *OriginConfig) HasOriginPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *OriginConfig) HasProtocolPolicy() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *OriginConfig) ClearDomainName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_DomainName = nil
}

func (x *OriginConfig) ClearOriginPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_OriginPath = nil
}

func (x *OriginConfig) ClearProtocolPolicy() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ProtocolPolicy = nil
}

type OriginConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Origin domain name
	DomainName *string
	// Origin path
	OriginPath *string
	// Origin protocol policy
	ProtocolPolicy *string
	// Custom headers to send to origin
	CustomHeaders []*v2.KeyValue
}

func (b0 OriginConfig_builder) Build() *OriginConfig {
	m0 := &OriginConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.DomainName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_DomainName = b.DomainName
	}
	if b.OriginPath != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_OriginPath = b.OriginPath
	}
	if b.ProtocolPolicy != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ProtocolPolicy = b.ProtocolPolicy
	}
	x.xxx_hidden_CustomHeaders = &b.CustomHeaders
	return m0
}

var File_organization_v2_origin_config_proto protoreflect.FileDescriptor

const file_organization_v2_origin_config_proto_rawDesc = "" +
	"\n" +
	"#organization/v2/origin_config.proto\x12\x0forganization.v2\x1a\x19common/v2/key_value.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xc0\x01\n" +
	"\fOriginConfig\x12*\n" +
	"\vdomain_name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\n" +
	"domainName\x12\x1f\n" +
	"\vorigin_path\x18\x02 \x01(\tR\n" +
	"originPath\x12'\n" +
	"\x0fprotocol_policy\x18\x03 \x01(\tR\x0eprotocolPolicy\x12:\n" +
	"\x0ecustom_headers\x18\x04 \x03(\v2\x13.common.v2.KeyValueR\rcustomHeadersB3Z)github.com/jdfalk/gcommon/organization/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_organization_v2_origin_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_organization_v2_origin_config_proto_goTypes = []any{
	(*OriginConfig)(nil), // 0: organization.v2.OriginConfig
	(*v2.KeyValue)(nil),  // 1: common.v2.KeyValue
}
var file_organization_v2_origin_config_proto_depIdxs = []int32{
	1, // 0: organization.v2.OriginConfig.custom_headers:type_name -> common.v2.KeyValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_organization_v2_origin_config_proto_init() }
func file_organization_v2_origin_config_proto_init() {
	if File_organization_v2_origin_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_v2_origin_config_proto_rawDesc), len(file_organization_v2_origin_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_organization_v2_origin_config_proto_goTypes,
		DependencyIndexes: file_organization_v2_origin_config_proto_depIdxs,
		MessageInfos:      file_organization_v2_origin_config_proto_msgTypes,
	}.Build()
	File_organization_v2_origin_config_proto = out.File
	file_organization_v2_origin_config_proto_goTypes = nil
	file_organization_v2_origin_config_proto_depIdxs = nil
}
