// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: organization/v2/tenant_service.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_organization_v2_tenant_service_proto protoreflect.FileDescriptor

const file_organization_v2_tenant_service_proto_rawDesc = "" +
	"\n" +
	"$organization/v2/tenant_service.proto\x12\x0forganization.v2\x1a8organization/v2/configure_tenant_isolation_request.proto\x1a9organization/v2/configure_tenant_isolation_response.proto\x1a+organization/v2/create_tenant_request.proto\x1a,organization/v2/create_tenant_response.proto\x1a+organization/v2/delete_tenant_request.proto\x1a,organization/v2/delete_tenant_response.proto\x1a2organization/v2/get_tenant_isolation_request.proto\x1a3organization/v2/get_tenant_isolation_response.proto\x1a(organization/v2/get_tenant_request.proto\x1a)organization/v2/get_tenant_response.proto\x1a.organization/v2/get_tenant_usage_request.proto\x1a/organization/v2/get_tenant_usage_response.proto\x1a*organization/v2/list_tenants_request.proto\x1a+organization/v2/list_tenants_response.proto\x1a1organization/v2/update_tenant_quota_request.proto\x1a2organization/v2/update_tenant_quota_response.proto\x1a+organization/v2/update_tenant_request.proto\x1a,organization/v2/update_tenant_response.proto\x1a!google/protobuf/go_features.proto2\x93\a\n" +
	"\rTenantService\x12[\n" +
	"\fCreateTenant\x12$.organization.v2.CreateTenantRequest\x1a%.organization.v2.CreateTenantResponse\x12R\n" +
	"\tGetTenant\x12!.organization.v2.GetTenantRequest\x1a\".organization.v2.GetTenantResponse\x12[\n" +
	"\fUpdateTenant\x12$.organization.v2.UpdateTenantRequest\x1a%.organization.v2.UpdateTenantResponse\x12[\n" +
	"\fDeleteTenant\x12$.organization.v2.DeleteTenantRequest\x1a%.organization.v2.DeleteTenantResponse\x12X\n" +
	"\vListTenants\x12#.organization.v2.ListTenantsRequest\x1a$.organization.v2.ListTenantsResponse\x12\x7f\n" +
	"\x18ConfigureTenantIsolation\x120.organization.v2.ConfigureTenantIsolationRequest\x1a1.organization.v2.ConfigureTenantIsolationResponse\x12m\n" +
	"\x12GetTenantIsolation\x12*.organization.v2.GetTenantIsolationRequest\x1a+.organization.v2.GetTenantIsolationResponse\x12j\n" +
	"\x11UpdateTenantQuota\x12).organization.v2.UpdateTenantQuotaRequest\x1a*.organization.v2.UpdateTenantQuotaResponse\x12a\n" +
	"\x0eGetTenantUsage\x12&.organization.v2.GetTenantUsageRequest\x1a'.organization.v2.GetTenantUsageResponseB3Z)github.com/jdfalk/gcommon/organization/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_organization_v2_tenant_service_proto_goTypes = []any{
	(*CreateTenantRequest)(nil),              // 0: organization.v2.CreateTenantRequest
	(*GetTenantRequest)(nil),                 // 1: organization.v2.GetTenantRequest
	(*UpdateTenantRequest)(nil),              // 2: organization.v2.UpdateTenantRequest
	(*DeleteTenantRequest)(nil),              // 3: organization.v2.DeleteTenantRequest
	(*ListTenantsRequest)(nil),               // 4: organization.v2.ListTenantsRequest
	(*ConfigureTenantIsolationRequest)(nil),  // 5: organization.v2.ConfigureTenantIsolationRequest
	(*GetTenantIsolationRequest)(nil),        // 6: organization.v2.GetTenantIsolationRequest
	(*UpdateTenantQuotaRequest)(nil),         // 7: organization.v2.UpdateTenantQuotaRequest
	(*GetTenantUsageRequest)(nil),            // 8: organization.v2.GetTenantUsageRequest
	(*CreateTenantResponse)(nil),             // 9: organization.v2.CreateTenantResponse
	(*GetTenantResponse)(nil),                // 10: organization.v2.GetTenantResponse
	(*UpdateTenantResponse)(nil),             // 11: organization.v2.UpdateTenantResponse
	(*DeleteTenantResponse)(nil),             // 12: organization.v2.DeleteTenantResponse
	(*ListTenantsResponse)(nil),              // 13: organization.v2.ListTenantsResponse
	(*ConfigureTenantIsolationResponse)(nil), // 14: organization.v2.ConfigureTenantIsolationResponse
	(*GetTenantIsolationResponse)(nil),       // 15: organization.v2.GetTenantIsolationResponse
	(*UpdateTenantQuotaResponse)(nil),        // 16: organization.v2.UpdateTenantQuotaResponse
	(*GetTenantUsageResponse)(nil),           // 17: organization.v2.GetTenantUsageResponse
}
var file_organization_v2_tenant_service_proto_depIdxs = []int32{
	0,  // 0: organization.v2.TenantService.CreateTenant:input_type -> organization.v2.CreateTenantRequest
	1,  // 1: organization.v2.TenantService.GetTenant:input_type -> organization.v2.GetTenantRequest
	2,  // 2: organization.v2.TenantService.UpdateTenant:input_type -> organization.v2.UpdateTenantRequest
	3,  // 3: organization.v2.TenantService.DeleteTenant:input_type -> organization.v2.DeleteTenantRequest
	4,  // 4: organization.v2.TenantService.ListTenants:input_type -> organization.v2.ListTenantsRequest
	5,  // 5: organization.v2.TenantService.ConfigureTenantIsolation:input_type -> organization.v2.ConfigureTenantIsolationRequest
	6,  // 6: organization.v2.TenantService.GetTenantIsolation:input_type -> organization.v2.GetTenantIsolationRequest
	7,  // 7: organization.v2.TenantService.UpdateTenantQuota:input_type -> organization.v2.UpdateTenantQuotaRequest
	8,  // 8: organization.v2.TenantService.GetTenantUsage:input_type -> organization.v2.GetTenantUsageRequest
	9,  // 9: organization.v2.TenantService.CreateTenant:output_type -> organization.v2.CreateTenantResponse
	10, // 10: organization.v2.TenantService.GetTenant:output_type -> organization.v2.GetTenantResponse
	11, // 11: organization.v2.TenantService.UpdateTenant:output_type -> organization.v2.UpdateTenantResponse
	12, // 12: organization.v2.TenantService.DeleteTenant:output_type -> organization.v2.DeleteTenantResponse
	13, // 13: organization.v2.TenantService.ListTenants:output_type -> organization.v2.ListTenantsResponse
	14, // 14: organization.v2.TenantService.ConfigureTenantIsolation:output_type -> organization.v2.ConfigureTenantIsolationResponse
	15, // 15: organization.v2.TenantService.GetTenantIsolation:output_type -> organization.v2.GetTenantIsolationResponse
	16, // 16: organization.v2.TenantService.UpdateTenantQuota:output_type -> organization.v2.UpdateTenantQuotaResponse
	17, // 17: organization.v2.TenantService.GetTenantUsage:output_type -> organization.v2.GetTenantUsageResponse
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_organization_v2_tenant_service_proto_init() }
func file_organization_v2_tenant_service_proto_init() {
	if File_organization_v2_tenant_service_proto != nil {
		return
	}
	file_organization_v2_configure_tenant_isolation_request_proto_init()
	file_organization_v2_configure_tenant_isolation_response_proto_init()
	file_organization_v2_create_tenant_request_proto_init()
	file_organization_v2_create_tenant_response_proto_init()
	file_organization_v2_delete_tenant_request_proto_init()
	file_organization_v2_delete_tenant_response_proto_init()
	file_organization_v2_get_tenant_isolation_request_proto_init()
	file_organization_v2_get_tenant_isolation_response_proto_init()
	file_organization_v2_get_tenant_request_proto_init()
	file_organization_v2_get_tenant_response_proto_init()
	file_organization_v2_get_tenant_usage_request_proto_init()
	file_organization_v2_get_tenant_usage_response_proto_init()
	file_organization_v2_list_tenants_request_proto_init()
	file_organization_v2_list_tenants_response_proto_init()
	file_organization_v2_update_tenant_quota_request_proto_init()
	file_organization_v2_update_tenant_quota_response_proto_init()
	file_organization_v2_update_tenant_request_proto_init()
	file_organization_v2_update_tenant_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_organization_v2_tenant_service_proto_rawDesc), len(file_organization_v2_tenant_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_organization_v2_tenant_service_proto_goTypes,
		DependencyIndexes: file_organization_v2_tenant_service_proto_depIdxs,
	}.Build()
	File_organization_v2_tenant_service_proto = out.File
	file_organization_v2_tenant_service_proto_goTypes = nil
	file_organization_v2_tenant_service_proto_depIdxs = nil
}
