// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: configpb/v2/backup_settings.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v2 "github.com/jdfalk/gcommon/pkg/commonpb/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackupSettings struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Enabled         bool                   `protobuf:"varint,1,opt,name=enabled"`
	xxx_hidden_Frequency       v2.BackupFrequency     `protobuf:"varint,2,opt,name=frequency,enum=common.v2.BackupFrequency"`
	xxx_hidden_RetentionDays   int32                  `protobuf:"varint,3,opt,name=retention_days,json=retentionDays"`
	xxx_hidden_StorageLocation *string                `protobuf:"bytes,4,opt,name=storage_location,json=storageLocation"`
	xxx_hidden_Encrypted       bool                   `protobuf:"varint,5,opt,name=encrypted"`
	xxx_hidden_Compressed      bool                   `protobuf:"varint,6,opt,name=compressed"`
	xxx_hidden_Metadata        map[string]string      `protobuf:"bytes,7,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *BackupSettings) Reset() {
	*x = BackupSettings{}
	mi := &file_configpb_v2_backup_settings_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupSettings) ProtoMessage() {}

func (x *BackupSettings) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_v2_backup_settings_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BackupSettings) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *BackupSettings) GetFrequency() v2.BackupFrequency {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Frequency
		}
	}
	return v2.BackupFrequency(0)
}

func (x *BackupSettings) GetRetentionDays() int32 {
	if x != nil {
		return x.xxx_hidden_RetentionDays
	}
	return 0
}

func (x *BackupSettings) GetStorageLocation() string {
	if x != nil {
		if x.xxx_hidden_StorageLocation != nil {
			return *x.xxx_hidden_StorageLocation
		}
		return ""
	}
	return ""
}

func (x *BackupSettings) GetEncrypted() bool {
	if x != nil {
		return x.xxx_hidden_Encrypted
	}
	return false
}

func (x *BackupSettings) GetCompressed() bool {
	if x != nil {
		return x.xxx_hidden_Compressed
	}
	return false
}

func (x *BackupSettings) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *BackupSettings) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *BackupSettings) SetFrequency(v v2.BackupFrequency) {
	x.xxx_hidden_Frequency = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *BackupSettings) SetRetentionDays(v int32) {
	x.xxx_hidden_RetentionDays = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *BackupSettings) SetStorageLocation(v string) {
	x.xxx_hidden_StorageLocation = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *BackupSettings) SetEncrypted(v bool) {
	x.xxx_hidden_Encrypted = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 7)
}

func (x *BackupSettings) SetCompressed(v bool) {
	x.xxx_hidden_Compressed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 7)
}

func (x *BackupSettings) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *BackupSettings) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BackupSettings) HasFrequency() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *BackupSettings) HasRetentionDays() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *BackupSettings) HasStorageLocation() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *BackupSettings) HasEncrypted() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *BackupSettings) HasCompressed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *BackupSettings) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Enabled = false
}

func (x *BackupSettings) ClearFrequency() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Frequency = v2.BackupFrequency_BACKUP_FREQUENCY_UNSPECIFIED
}

func (x *BackupSettings) ClearRetentionDays() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_RetentionDays = 0
}

func (x *BackupSettings) ClearStorageLocation() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_StorageLocation = nil
}

func (x *BackupSettings) ClearEncrypted() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Encrypted = false
}

func (x *BackupSettings) ClearCompressed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Compressed = false
}

type BackupSettings_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether backup is enabled
	Enabled *bool
	// Backup frequency
	Frequency *v2.BackupFrequency
	// Backup retention period in days
	RetentionDays *int32
	// Backup storage location
	StorageLocation *string
	// Backup encryption
	Encrypted *bool
	// Backup compression
	Compressed *bool
	// Backup metadata
	Metadata map[string]string
}

func (b0 BackupSettings_builder) Build() *BackupSettings {
	m0 := &BackupSettings{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.Frequency != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Frequency = *b.Frequency
	}
	if b.RetentionDays != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_RetentionDays = *b.RetentionDays
	}
	if b.StorageLocation != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_StorageLocation = b.StorageLocation
	}
	if b.Encrypted != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 7)
		x.xxx_hidden_Encrypted = *b.Encrypted
	}
	if b.Compressed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 7)
		x.xxx_hidden_Compressed = *b.Compressed
	}
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

var File_configpb_v2_backup_settings_proto protoreflect.FileDescriptor

const file_configpb_v2_backup_settings_proto_rawDesc = "" +
	"\n" +
	"!configpb/v2/backup_settings.proto\x12\tconfig.v2\x1a\"commonpb/v2/backup_frequency.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\x88\x03\n" +
	"\x0eBackupSettings\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x128\n" +
	"\tfrequency\x18\x02 \x01(\x0e2\x1a.common.v2.BackupFrequencyR\tfrequency\x12.\n" +
	"\x0eretention_days\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\rretentionDays\x122\n" +
	"\x10storage_location\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fstorageLocation\x12\x1c\n" +
	"\tencrypted\x18\x05 \x01(\bR\tencrypted\x12\x1e\n" +
	"\n" +
	"compressed\x18\x06 \x01(\bR\n" +
	"compressed\x12C\n" +
	"\bmetadata\x18\a \x03(\v2'.config.v2.BackupSettings.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x9c\x01\n" +
	"\rcom.config.v2B\x13BackupSettingsProtoP\x01Z)github.com/jdfalk/gcommon/pkg/configpb/v2\xa2\x02\x03CXX\xaa\x02\tConfig.V2\xca\x02\tConfig\\V2\xe2\x02\x15Config\\V2\\GPBMetadata\xea\x02\n" +
	"Config::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_configpb_v2_backup_settings_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_configpb_v2_backup_settings_proto_goTypes = []any{
	(*BackupSettings)(nil),  // 0: config.v2.BackupSettings
	nil,                     // 1: config.v2.BackupSettings.MetadataEntry
	(v2.BackupFrequency)(0), // 2: common.v2.BackupFrequency
}
var file_configpb_v2_backup_settings_proto_depIdxs = []int32{
	2, // 0: config.v2.BackupSettings.frequency:type_name -> common.v2.BackupFrequency
	1, // 1: config.v2.BackupSettings.metadata:type_name -> config.v2.BackupSettings.MetadataEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_configpb_v2_backup_settings_proto_init() }
func file_configpb_v2_backup_settings_proto_init() {
	if File_configpb_v2_backup_settings_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configpb_v2_backup_settings_proto_rawDesc), len(file_configpb_v2_backup_settings_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configpb_v2_backup_settings_proto_goTypes,
		DependencyIndexes: file_configpb_v2_backup_settings_proto_depIdxs,
		MessageInfos:      file_configpb_v2_backup_settings_proto_msgTypes,
	}.Build()
	File_configpb_v2_backup_settings_proto = out.File
	file_configpb_v2_backup_settings_proto_goTypes = nil
	file_configpb_v2_backup_settings_proto_depIdxs = nil
}
