// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: configpb/v2/health_check_response.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v2 "github.com/jdfalk/gcommon/pkg/commonpb/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// HealthCheckResponse provides health status for the config service.
type ConfigHealthCheckResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status      v2.CommonHealthStatus  `protobuf:"varint,1,opt,name=status,enum=common.v2.CommonHealthStatus"`
	xxx_hidden_Message     *string                `protobuf:"bytes,2,opt,name=message"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ConfigHealthCheckResponse) Reset() {
	*x = ConfigHealthCheckResponse{}
	mi := &file_configpb_v2_health_check_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigHealthCheckResponse) ProtoMessage() {}

func (x *ConfigHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_configpb_v2_health_check_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigHealthCheckResponse) GetStatus() v2.CommonHealthStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Status
		}
	}
	return v2.CommonHealthStatus(0)
}

func (x *ConfigHealthCheckResponse) GetMessage() string {
	if x != nil {
		if x.xxx_hidden_Message != nil {
			return *x.xxx_hidden_Message
		}
		return ""
	}
	return ""
}

func (x *ConfigHealthCheckResponse) SetStatus(v v2.CommonHealthStatus) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *ConfigHealthCheckResponse) SetMessage(v string) {
	x.xxx_hidden_Message = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *ConfigHealthCheckResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConfigHealthCheckResponse) HasMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConfigHealthCheckResponse) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = v2.CommonHealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *ConfigHealthCheckResponse) ClearMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Message = nil
}

type ConfigHealthCheckResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Overall health status
	Status *v2.CommonHealthStatus
	// Optional human-readable message
	Message *string
}

func (b0 ConfigHealthCheckResponse_builder) Build() *ConfigHealthCheckResponse {
	m0 := &ConfigHealthCheckResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Status = *b.Status
	}
	if b.Message != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Message = b.Message
	}
	return m0
}

var File_configpb_v2_health_check_response_proto protoreflect.FileDescriptor

const file_configpb_v2_health_check_response_proto_rawDesc = "" +
	"\n" +
	"'configpb/v2/health_check_response.proto\x12\tconfig.v2\x1a\x1fcommonpb/v2/health_status.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"u\n" +
	"\x19ConfigHealthCheckResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.common.v2.CommonHealthStatusR\x06status\x12!\n" +
	"\amessage\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\amessageB\xa1\x01\n" +
	"\rcom.config.v2B\x18HealthCheckResponseProtoP\x01Z)github.com/jdfalk/gcommon/pkg/configpb/v2\xa2\x02\x03CXX\xaa\x02\tConfig.V2\xca\x02\tConfig\\V2\xe2\x02\x15Config\\V2\\GPBMetadata\xea\x02\n" +
	"Config::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_configpb_v2_health_check_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_configpb_v2_health_check_response_proto_goTypes = []any{
	(*ConfigHealthCheckResponse)(nil), // 0: config.v2.ConfigHealthCheckResponse
	(v2.CommonHealthStatus)(0),        // 1: common.v2.CommonHealthStatus
}
var file_configpb_v2_health_check_response_proto_depIdxs = []int32{
	1, // 0: config.v2.ConfigHealthCheckResponse.status:type_name -> common.v2.CommonHealthStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_configpb_v2_health_check_response_proto_init() }
func file_configpb_v2_health_check_response_proto_init() {
	if File_configpb_v2_health_check_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configpb_v2_health_check_response_proto_rawDesc), len(file_configpb_v2_health_check_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_configpb_v2_health_check_response_proto_goTypes,
		DependencyIndexes: file_configpb_v2_health_check_response_proto_depIdxs,
		MessageInfos:      file_configpb_v2_health_check_response_proto_msgTypes,
	}.Build()
	File_configpb_v2_health_check_response_proto = out.File
	file_configpb_v2_health_check_response_proto_goTypes = nil
	file_configpb_v2_health_check_response_proto_depIdxs = nil
}
