// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: authpb/v1/auth_service.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_authpb_v1_auth_service_proto protoreflect.FileDescriptor

const file_authpb_v1_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x1cauthpb/v1/auth_service.proto\x12\aauth.v1\x1a\x1dauthpb/v1/login_request.proto\x1a\x1eauthpb/v1/login_response.proto\x1a&authpb/v1/validate_token_request.proto\x1a'authpb/v1/validate_token_response.proto\x1a!authpb/v1/authorize_request.proto\x1a\"authpb/v1/authorize_response.proto\x1a&authpb/v1/generate_token_request.proto\x1a'authpb/v1/generate_token_response.proto\x1a%authpb/v1/refresh_token_request.proto\x1a&authpb/v1/refresh_token_response.proto\x1a$authpb/v1/revoke_token_request.proto\x1a%authpb/v1/revoke_token_response.proto\x1a!google/protobuf/go_features.proto2\xc6\x03\n" +
	"\vAuthService\x126\n" +
	"\x05Login\x12\x15.auth.v1.LoginRequest\x1a\x16.auth.v1.LoginResponse\x12N\n" +
	"\rValidateToken\x12\x1d.auth.v1.ValidateTokenRequest\x1a\x1e.auth.v1.ValidateTokenResponse\x12H\n" +
	"\x0fAuthorizeAccess\x12\x19.auth.v1.AuthorizeRequest\x1a\x1a.auth.v1.AuthorizeResponse\x12N\n" +
	"\rGenerateToken\x12\x1d.auth.v1.GenerateTokenRequest\x1a\x1e.auth.v1.GenerateTokenResponse\x12K\n" +
	"\fRefreshToken\x12\x1c.auth.v1.RefreshTokenRequest\x1a\x1d.auth.v1.RefreshTokenResponse\x12H\n" +
	"\vRevokeToken\x12\x1b.auth.v1.RevokeTokenRequest\x1a\x1c.auth.v1.RevokeTokenResponseB\x8a\x01\n" +
	"\vcom.auth.v1B\x10AuthServiceProtoP\x01Z$github.com/jdfalk/gcommon/pkg/authpb\xa2\x02\x03AXX\xaa\x02\aAuth.V1\xca\x02\aAuth\\V1\xe2\x02\x13Auth\\V1\\GPBMetadata\xea\x02\bAuth::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_authpb_v1_auth_service_proto_goTypes = []any{
	(*LoginRequest)(nil),          // 0: auth.v1.LoginRequest
	(*ValidateTokenRequest)(nil),  // 1: auth.v1.ValidateTokenRequest
	(*AuthorizeRequest)(nil),      // 2: auth.v1.AuthorizeRequest
	(*GenerateTokenRequest)(nil),  // 3: auth.v1.GenerateTokenRequest
	(*RefreshTokenRequest)(nil),   // 4: auth.v1.RefreshTokenRequest
	(*RevokeTokenRequest)(nil),    // 5: auth.v1.RevokeTokenRequest
	(*LoginResponse)(nil),         // 6: auth.v1.LoginResponse
	(*ValidateTokenResponse)(nil), // 7: auth.v1.ValidateTokenResponse
	(*AuthorizeResponse)(nil),     // 8: auth.v1.AuthorizeResponse
	(*GenerateTokenResponse)(nil), // 9: auth.v1.GenerateTokenResponse
	(*RefreshTokenResponse)(nil),  // 10: auth.v1.RefreshTokenResponse
	(*RevokeTokenResponse)(nil),   // 11: auth.v1.RevokeTokenResponse
}
var file_authpb_v1_auth_service_proto_depIdxs = []int32{
	0,  // 0: auth.v1.AuthService.Login:input_type -> auth.v1.LoginRequest
	1,  // 1: auth.v1.AuthService.ValidateToken:input_type -> auth.v1.ValidateTokenRequest
	2,  // 2: auth.v1.AuthService.AuthorizeAccess:input_type -> auth.v1.AuthorizeRequest
	3,  // 3: auth.v1.AuthService.GenerateToken:input_type -> auth.v1.GenerateTokenRequest
	4,  // 4: auth.v1.AuthService.RefreshToken:input_type -> auth.v1.RefreshTokenRequest
	5,  // 5: auth.v1.AuthService.RevokeToken:input_type -> auth.v1.RevokeTokenRequest
	6,  // 6: auth.v1.AuthService.Login:output_type -> auth.v1.LoginResponse
	7,  // 7: auth.v1.AuthService.ValidateToken:output_type -> auth.v1.ValidateTokenResponse
	8,  // 8: auth.v1.AuthService.AuthorizeAccess:output_type -> auth.v1.AuthorizeResponse
	9,  // 9: auth.v1.AuthService.GenerateToken:output_type -> auth.v1.GenerateTokenResponse
	10, // 10: auth.v1.AuthService.RefreshToken:output_type -> auth.v1.RefreshTokenResponse
	11, // 11: auth.v1.AuthService.RevokeToken:output_type -> auth.v1.RevokeTokenResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_authpb_v1_auth_service_proto_init() }
func file_authpb_v1_auth_service_proto_init() {
	if File_authpb_v1_auth_service_proto != nil {
		return
	}
	file_authpb_v1_login_request_proto_init()
	file_authpb_v1_login_response_proto_init()
	file_authpb_v1_validate_token_request_proto_init()
	file_authpb_v1_validate_token_response_proto_init()
	file_authpb_v1_authorize_request_proto_init()
	file_authpb_v1_authorize_response_proto_init()
	file_authpb_v1_generate_token_request_proto_init()
	file_authpb_v1_generate_token_response_proto_init()
	file_authpb_v1_refresh_token_request_proto_init()
	file_authpb_v1_refresh_token_response_proto_init()
	file_authpb_v1_revoke_token_request_proto_init()
	file_authpb_v1_revoke_token_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authpb_v1_auth_service_proto_rawDesc), len(file_authpb_v1_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authpb_v1_auth_service_proto_goTypes,
		DependencyIndexes: file_authpb_v1_auth_service_proto_depIdxs,
	}.Build()
	File_authpb_v1_auth_service_proto = out.File
	file_authpb_v1_auth_service_proto_goTypes = nil
	file_authpb_v1_auth_service_proto_depIdxs = nil
}
