// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: authpb/v1/revoke_token_request.proto

package authpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// RevokeTokenRequest represents a token revocation request.
// Contains the token to be revoked.
type RevokeTokenRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Token       *string                `protobuf:"bytes,1,opt,name=token"`
	xxx_hidden_TokenType   *string                `protobuf:"bytes,2,opt,name=token_type,json=tokenType"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_authpb_v1_revoke_token_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_authpb_v1_revoke_token_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RevokeTokenRequest) GetToken() string {
	if x != nil {
		if x.xxx_hidden_Token != nil {
			return *x.xxx_hidden_Token
		}
		return ""
	}
	return ""
}

func (x *RevokeTokenRequest) GetTokenType() string {
	if x != nil {
		if x.xxx_hidden_TokenType != nil {
			return *x.xxx_hidden_TokenType
		}
		return ""
	}
	return ""
}

func (x *RevokeTokenRequest) SetToken(v string) {
	x.xxx_hidden_Token = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RevokeTokenRequest) SetTokenType(v string) {
	x.xxx_hidden_TokenType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RevokeTokenRequest) HasToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RevokeTokenRequest) HasTokenType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RevokeTokenRequest) ClearToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Token = nil
}

func (x *RevokeTokenRequest) ClearTokenType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_TokenType = nil
}

type RevokeTokenRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Token to revoke
	Token *string
	// Type of token being revoked
	TokenType *string
}

func (b0 RevokeTokenRequest_builder) Build() *RevokeTokenRequest {
	m0 := &RevokeTokenRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Token != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Token = b.Token
	}
	if b.TokenType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_TokenType = b.TokenType
	}
	return m0
}

var File_authpb_v1_revoke_token_request_proto protoreflect.FileDescriptor

const file_authpb_v1_revoke_token_request_proto_rawDesc = "" +
	"\n" +
	"$authpb/v1/revoke_token_request.proto\x12\aauth.v1\x1a!google/protobuf/go_features.proto\"I\n" +
	"\x12RevokeTokenRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"token_type\x18\x02 \x01(\tR\ttokenTypeB\x91\x01\n" +
	"\vcom.auth.v1B\x17RevokeTokenRequestProtoP\x01Z$github.com/jdfalk/gcommon/pkg/authpb\xa2\x02\x03AXX\xaa\x02\aAuth.V1\xca\x02\aAuth\\V1\xe2\x02\x13Auth\\V1\\GPBMetadata\xea\x02\bAuth::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_authpb_v1_revoke_token_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_authpb_v1_revoke_token_request_proto_goTypes = []any{
	(*RevokeTokenRequest)(nil), // 0: auth.v1.RevokeTokenRequest
}
var file_authpb_v1_revoke_token_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authpb_v1_revoke_token_request_proto_init() }
func file_authpb_v1_revoke_token_request_proto_init() {
	if File_authpb_v1_revoke_token_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authpb_v1_revoke_token_request_proto_rawDesc), len(file_authpb_v1_revoke_token_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_authpb_v1_revoke_token_request_proto_goTypes,
		DependencyIndexes: file_authpb_v1_revoke_token_request_proto_depIdxs,
		MessageInfos:      file_authpb_v1_revoke_token_request_proto_msgTypes,
	}.Build()
	File_authpb_v1_revoke_token_request_proto = out.File
	file_authpb_v1_revoke_token_request_proto_goTypes = nil
	file_authpb_v1_revoke_token_request_proto_depIdxs = nil
}
