// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: metrics/v1/create_provider_response.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/jdfalk/gcommon/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateProviderResponse struct {
	state                    protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Success       bool                        `protobuf:"varint,1,opt,name=success"`
	xxx_hidden_Error         *v1.Error                   `protobuf:"bytes,2,opt,name=error"`
	xxx_hidden_ProviderId    *string                     `protobuf:"bytes,3,opt,name=provider_id,json=providerId"`
	xxx_hidden_CreatedAt     *timestamppb.Timestamp      `protobuf:"bytes,4,opt,name=created_at,json=createdAt"`
	xxx_hidden_Status        *ProviderStatus             `protobuf:"bytes,5,opt,name=status"`
	xxx_hidden_Validation    *v1.MetricsValidationResult `protobuf:"bytes,6,opt,name=validation"`
	xxx_hidden_AppliedConfig *AppliedConfig              `protobuf:"bytes,7,opt,name=applied_config,json=appliedConfig"`
	xxx_hidden_Warnings      []string                    `protobuf:"bytes,8,rep,name=warnings"`
	xxx_hidden_Endpoints     *ProviderEndpoints          `protobuf:"bytes,9,opt,name=endpoints"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *CreateProviderResponse) Reset() {
	*x = CreateProviderResponse{}
	mi := &file_metrics_v1_create_provider_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProviderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProviderResponse) ProtoMessage() {}

func (x *CreateProviderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_create_provider_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CreateProviderResponse) GetSuccess() bool {
	if x != nil {
		return x.xxx_hidden_Success
	}
	return false
}

func (x *CreateProviderResponse) GetError() *v1.Error {
	if x != nil {
		return x.xxx_hidden_Error
	}
	return nil
}

func (x *CreateProviderResponse) GetProviderId() string {
	if x != nil {
		if x.xxx_hidden_ProviderId != nil {
			return *x.xxx_hidden_ProviderId
		}
		return ""
	}
	return ""
}

func (x *CreateProviderResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *CreateProviderResponse) GetStatus() *ProviderStatus {
	if x != nil {
		return x.xxx_hidden_Status
	}
	return nil
}

func (x *CreateProviderResponse) GetValidation() *v1.MetricsValidationResult {
	if x != nil {
		return x.xxx_hidden_Validation
	}
	return nil
}

func (x *CreateProviderResponse) GetAppliedConfig() *AppliedConfig {
	if x != nil {
		return x.xxx_hidden_AppliedConfig
	}
	return nil
}

func (x *CreateProviderResponse) GetWarnings() []string {
	if x != nil {
		return x.xxx_hidden_Warnings
	}
	return nil
}

func (x *CreateProviderResponse) GetEndpoints() *ProviderEndpoints {
	if x != nil {
		return x.xxx_hidden_Endpoints
	}
	return nil
}

func (x *CreateProviderResponse) SetSuccess(v bool) {
	x.xxx_hidden_Success = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *CreateProviderResponse) SetError(v *v1.Error) {
	x.xxx_hidden_Error = v
}

func (x *CreateProviderResponse) SetProviderId(v string) {
	x.xxx_hidden_ProviderId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 9)
}

func (x *CreateProviderResponse) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *CreateProviderResponse) SetStatus(v *ProviderStatus) {
	x.xxx_hidden_Status = v
}

func (x *CreateProviderResponse) SetValidation(v *v1.MetricsValidationResult) {
	x.xxx_hidden_Validation = v
}

func (x *CreateProviderResponse) SetAppliedConfig(v *AppliedConfig) {
	x.xxx_hidden_AppliedConfig = v
}

func (x *CreateProviderResponse) SetWarnings(v []string) {
	x.xxx_hidden_Warnings = v
}

func (x *CreateProviderResponse) SetEndpoints(v *ProviderEndpoints) {
	x.xxx_hidden_Endpoints = v
}

func (x *CreateProviderResponse) HasSuccess() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *CreateProviderResponse) HasError() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Error != nil
}

func (x *CreateProviderResponse) HasProviderId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *CreateProviderResponse) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *CreateProviderResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Status != nil
}

func (x *CreateProviderResponse) HasValidation() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Validation != nil
}

func (x *CreateProviderResponse) HasAppliedConfig() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_AppliedConfig != nil
}

func (x *CreateProviderResponse) HasEndpoints() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Endpoints != nil
}

func (x *CreateProviderResponse) ClearSuccess() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Success = false
}

func (x *CreateProviderResponse) ClearError() {
	x.xxx_hidden_Error = nil
}

func (x *CreateProviderResponse) ClearProviderId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ProviderId = nil
}

func (x *CreateProviderResponse) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *CreateProviderResponse) ClearStatus() {
	x.xxx_hidden_Status = nil
}

func (x *CreateProviderResponse) ClearValidation() {
	x.xxx_hidden_Validation = nil
}

func (x *CreateProviderResponse) ClearAppliedConfig() {
	x.xxx_hidden_AppliedConfig = nil
}

func (x *CreateProviderResponse) ClearEndpoints() {
	x.xxx_hidden_Endpoints = nil
}

type CreateProviderResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Success status of the creation
	Success *bool
	// Error information if creation failed
	Error *v1.Error
	// ID of the created provider
	ProviderId *string
	// When the provider was created
	CreatedAt *timestamppb.Timestamp
	// Current status of the provider
	Status *ProviderStatus
	// Validation results
	Validation *v1.MetricsValidationResult
	// Configuration details that were applied
	AppliedConfig *AppliedConfig
	// Warnings or informational messages
	Warnings []string
	// Endpoint information for accessing the provider
	Endpoints *ProviderEndpoints
}

func (b0 CreateProviderResponse_builder) Build() *CreateProviderResponse {
	m0 := &CreateProviderResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Success != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_Success = *b.Success
	}
	x.xxx_hidden_Error = b.Error
	if b.ProviderId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 9)
		x.xxx_hidden_ProviderId = b.ProviderId
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_Status = b.Status
	x.xxx_hidden_Validation = b.Validation
	x.xxx_hidden_AppliedConfig = b.AppliedConfig
	x.xxx_hidden_Warnings = b.Warnings
	x.xxx_hidden_Endpoints = b.Endpoints
	return m0
}

var File_metrics_v1_create_provider_response_proto protoreflect.FileDescriptor

const file_metrics_v1_create_provider_response_proto_rawDesc = "" +
	"\n" +
	")metrics/v1/create_provider_response.proto\x12\n" +
	"metrics.v1\x1a\x15common/v1/error.proto\x1a)common/v1/metrics_validation_result.proto\x1a\x1fmetrics/v1/applied_config.proto\x1a#metrics/v1/provider_endpoints.proto\x1a metrics/v1/provider_status.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xd1\x03\n" +
	"\x16CreateProviderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x05error\x18\x02 \x01(\v2\x10.common.v1.ErrorR\x05error\x12\x1f\n" +
	"\vprovider_id\x18\x03 \x01(\tR\n" +
	"providerId\x12A\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedAt\x122\n" +
	"\x06status\x18\x05 \x01(\v2\x1a.metrics.v1.ProviderStatusR\x06status\x12B\n" +
	"\n" +
	"validation\x18\x06 \x01(\v2\".common.v1.MetricsValidationResultR\n" +
	"validation\x12@\n" +
	"\x0eapplied_config\x18\a \x01(\v2\x19.metrics.v1.AppliedConfigR\rappliedConfig\x12\x1a\n" +
	"\bwarnings\x18\b \x03(\tR\bwarnings\x12;\n" +
	"\tendpoints\x18\t \x01(\v2\x1d.metrics.v1.ProviderEndpointsR\tendpointsB.Z$github.com/jdfalk/gcommon/metrics/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_metrics_v1_create_provider_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metrics_v1_create_provider_response_proto_goTypes = []any{
	(*CreateProviderResponse)(nil),     // 0: metrics.v1.CreateProviderResponse
	(*v1.Error)(nil),                   // 1: common.v1.Error
	(*timestamppb.Timestamp)(nil),      // 2: google.protobuf.Timestamp
	(*ProviderStatus)(nil),             // 3: metrics.v1.ProviderStatus
	(*v1.MetricsValidationResult)(nil), // 4: common.v1.MetricsValidationResult
	(*AppliedConfig)(nil),              // 5: metrics.v1.AppliedConfig
	(*ProviderEndpoints)(nil),          // 6: metrics.v1.ProviderEndpoints
}
var file_metrics_v1_create_provider_response_proto_depIdxs = []int32{
	1, // 0: metrics.v1.CreateProviderResponse.error:type_name -> common.v1.Error
	2, // 1: metrics.v1.CreateProviderResponse.created_at:type_name -> google.protobuf.Timestamp
	3, // 2: metrics.v1.CreateProviderResponse.status:type_name -> metrics.v1.ProviderStatus
	4, // 3: metrics.v1.CreateProviderResponse.validation:type_name -> common.v1.MetricsValidationResult
	5, // 4: metrics.v1.CreateProviderResponse.applied_config:type_name -> metrics.v1.AppliedConfig
	6, // 5: metrics.v1.CreateProviderResponse.endpoints:type_name -> metrics.v1.ProviderEndpoints
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_metrics_v1_create_provider_response_proto_init() }
func file_metrics_v1_create_provider_response_proto_init() {
	if File_metrics_v1_create_provider_response_proto != nil {
		return
	}
	file_metrics_v1_applied_config_proto_init()
	file_metrics_v1_provider_endpoints_proto_init()
	file_metrics_v1_provider_status_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_v1_create_provider_response_proto_rawDesc), len(file_metrics_v1_create_provider_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_v1_create_provider_response_proto_goTypes,
		DependencyIndexes: file_metrics_v1_create_provider_response_proto_depIdxs,
		MessageInfos:      file_metrics_v1_create_provider_response_proto_msgTypes,
	}.Build()
	File_metrics_v1_create_provider_response_proto = out.File
	file_metrics_v1_create_provider_response_proto_goTypes = nil
	file_metrics_v1_create_provider_response_proto_depIdxs = nil
}
