// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: metrics/v1/query_step.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/jdfalk/gcommon/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryStep struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_StepId            *string                `protobuf:"bytes,1,opt,name=step_id,json=stepId"`
	xxx_hidden_Operation         v1.QueryOperation      `protobuf:"varint,2,opt,name=operation,enum=common.v1.QueryOperation"`
	xxx_hidden_Description       *string                `protobuf:"bytes,3,opt,name=description"`
	xxx_hidden_EstimatedDuration *durationpb.Duration   `protobuf:"bytes,4,opt,name=estimated_duration,json=estimatedDuration"`
	xxx_hidden_InputStepIds      []string               `protobuf:"bytes,5,rep,name=input_step_ids,json=inputStepIds"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *QueryStep) Reset() {
	*x = QueryStep{}
	mi := &file_metrics_v1_query_step_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryStep) ProtoMessage() {}

func (x *QueryStep) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_v1_query_step_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueryStep) GetStepId() string {
	if x != nil {
		if x.xxx_hidden_StepId != nil {
			return *x.xxx_hidden_StepId
		}
		return ""
	}
	return ""
}

func (x *QueryStep) GetOperation() v1.QueryOperation {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_Operation
		}
	}
	return v1.QueryOperation(0)
}

func (x *QueryStep) GetDescription() string {
	if x != nil {
		if x.xxx_hidden_Description != nil {
			return *x.xxx_hidden_Description
		}
		return ""
	}
	return ""
}

func (x *QueryStep) GetEstimatedDuration() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_EstimatedDuration
	}
	return nil
}

func (x *QueryStep) GetInputStepIds() []string {
	if x != nil {
		return x.xxx_hidden_InputStepIds
	}
	return nil
}

func (x *QueryStep) SetStepId(v string) {
	x.xxx_hidden_StepId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *QueryStep) SetOperation(v v1.QueryOperation) {
	x.xxx_hidden_Operation = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *QueryStep) SetDescription(v string) {
	x.xxx_hidden_Description = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *QueryStep) SetEstimatedDuration(v *durationpb.Duration) {
	x.xxx_hidden_EstimatedDuration = v
}

func (x *QueryStep) SetInputStepIds(v []string) {
	x.xxx_hidden_InputStepIds = v
}

func (x *QueryStep) HasStepId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *QueryStep) HasOperation() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *QueryStep) HasDescription() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *QueryStep) HasEstimatedDuration() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_EstimatedDuration != nil
}

func (x *QueryStep) ClearStepId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_StepId = nil
}

func (x *QueryStep) ClearOperation() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Operation = v1.QueryOperation_QUERY_OPERATION_UNSPECIFIED
}

func (x *QueryStep) ClearDescription() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Description = nil
}

func (x *QueryStep) ClearEstimatedDuration() {
	x.xxx_hidden_EstimatedDuration = nil
}

type QueryStep_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Step identifier
	StepId *string
	// Operation to perform in this step
	Operation *v1.QueryOperation
	// Description of the operation
	Description *string
	// Estimated cost/time for this step
	EstimatedDuration *durationpb.Duration
	// Input from previous steps
	InputStepIds []string
}

func (b0 QueryStep_builder) Build() *QueryStep {
	m0 := &QueryStep{}
	b, x := &b0, m0
	_, _ = b, x
	if b.StepId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_StepId = b.StepId
	}
	if b.Operation != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Operation = *b.Operation
	}
	if b.Description != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Description = b.Description
	}
	x.xxx_hidden_EstimatedDuration = b.EstimatedDuration
	x.xxx_hidden_InputStepIds = b.InputStepIds
	return m0
}

var File_metrics_v1_query_step_proto protoreflect.FileDescriptor

const file_metrics_v1_query_step_proto_rawDesc = "" +
	"\n" +
	"\x1bmetrics/v1/query_step.proto\x12\n" +
	"metrics.v1\x1a\x1fcommon/v1/query_operation.proto\x1a\x1egoogle/protobuf/duration.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xf9\x01\n" +
	"\tQueryStep\x12\x17\n" +
	"\astep_id\x18\x01 \x01(\tR\x06stepId\x127\n" +
	"\toperation\x18\x02 \x01(\x0e2\x19.common.v1.QueryOperationR\toperation\x12*\n" +
	"\vdescription\x18\x03 \x01(\tB\b\xbaH\x05r\x03\x18\xe8\aR\vdescription\x12H\n" +
	"\x12estimated_duration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x11estimatedDuration\x12$\n" +
	"\x0einput_step_ids\x18\x05 \x03(\tR\finputStepIdsB.Z$github.com/jdfalk/gcommon/metrics/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_metrics_v1_query_step_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metrics_v1_query_step_proto_goTypes = []any{
	(*QueryStep)(nil),           // 0: metrics.v1.QueryStep
	(v1.QueryOperation)(0),      // 1: common.v1.QueryOperation
	(*durationpb.Duration)(nil), // 2: google.protobuf.Duration
}
var file_metrics_v1_query_step_proto_depIdxs = []int32{
	1, // 0: metrics.v1.QueryStep.operation:type_name -> common.v1.QueryOperation
	2, // 1: metrics.v1.QueryStep.estimated_duration:type_name -> google.protobuf.Duration
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_metrics_v1_query_step_proto_init() }
func file_metrics_v1_query_step_proto_init() {
	if File_metrics_v1_query_step_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_v1_query_step_proto_rawDesc), len(file_metrics_v1_query_step_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_v1_query_step_proto_goTypes,
		DependencyIndexes: file_metrics_v1_query_step_proto_depIdxs,
		MessageInfos:      file_metrics_v1_query_step_proto_msgTypes,
	}.Build()
	File_metrics_v1_query_step_proto = out.File
	file_metrics_v1_query_step_proto_goTypes = nil
	file_metrics_v1_query_step_proto_depIdxs = nil
}
