// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: common/v2/validate_session_response.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Response to session validation request.
// Contains session validity status and associated user/session information.
// Includes error information if validation fails.
type ValidateSessionResponse struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Valid    bool                   `protobuf:"varint,1,opt,name=valid"`
	xxx_hidden_Session  *Session               `protobuf:"bytes,2,opt,name=session"`
	xxx_hidden_UserInfo *UserInfo              `protobuf:"bytes,3,opt,name=user_info,json=userInfo"`
	xxx_hidden_Error    *Error                 `protobuf:"bytes,4,opt,name=error"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ValidateSessionResponse) Reset() {
	*x = ValidateSessionResponse{}
	mi := &file_common_v2_validate_session_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionResponse) ProtoMessage() {}

func (x *ValidateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_v2_validate_session_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValidateSessionResponse) GetValid() bool {
	if x != nil {
		return x.xxx_hidden_Valid
	}
	return false
}

func (x *ValidateSessionResponse) GetSession() *Session {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Session) {
				protoimpl.X.UnmarshalField(x, 2)
			}
			var rv *Session
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Session), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *ValidateSessionResponse) GetUserInfo() *UserInfo {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_UserInfo) {
				protoimpl.X.UnmarshalField(x, 3)
			}
			var rv *UserInfo
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_UserInfo), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *ValidateSessionResponse) GetError() *Error {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Error) {
				protoimpl.X.UnmarshalField(x, 4)
			}
			var rv *Error
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Error), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *ValidateSessionResponse) SetValid(v bool) {
	x.xxx_hidden_Valid = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ValidateSessionResponse) SetSession(v *Session) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Session, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
	}
}

func (x *ValidateSessionResponse) SetUserInfo(v *UserInfo) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_UserInfo, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
	}
}

func (x *ValidateSessionResponse) SetError(v *Error) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Error, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
	}
}

func (x *ValidateSessionResponse) HasValid() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ValidateSessionResponse) HasSession() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ValidateSessionResponse) HasUserInfo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ValidateSessionResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ValidateSessionResponse) ClearValid() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Valid = false
}

func (x *ValidateSessionResponse) ClearSession() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Session, (*Session)(nil))
}

func (x *ValidateSessionResponse) ClearUserInfo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_UserInfo, (*UserInfo)(nil))
}

func (x *ValidateSessionResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Error, (*Error)(nil))
}

type ValidateSessionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether the session is valid
	Valid *bool
	// Session information if valid
	Session *Session
	// User information associated with the session
	UserInfo *UserInfo
	// Error information if validation fails
	Error *Error
}

func (b0 ValidateSessionResponse_builder) Build() *ValidateSessionResponse {
	m0 := &ValidateSessionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Valid != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Valid = *b.Valid
	}
	if b.Session != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Session = b.Session
	}
	if b.UserInfo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_UserInfo = b.UserInfo
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

var File_common_v2_validate_session_response_proto protoreflect.FileDescriptor

const file_common_v2_validate_session_response_proto_rawDesc = "" +
	"\n" +
	")common/v2/validate_session_response.proto\x12\tcommon.v2\x1a\x15common/v2/error.proto\x1a\x17common/v2/session.proto\x1a\x19common/v2/user_info.proto\x1a!google/protobuf/go_features.proto\"\xc3\x01\n" +
	"\x17ValidateSessionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x120\n" +
	"\asession\x18\x02 \x01(\v2\x12.common.v2.SessionB\x02(\x01R\asession\x124\n" +
	"\tuser_info\x18\x03 \x01(\v2\x13.common.v2.UserInfoB\x02(\x01R\buserInfo\x12*\n" +
	"\x05error\x18\x04 \x01(\v2\x10.common.v2.ErrorB\x02(\x01R\x05errorB-Z#github.com/jdfalk/gcommon/common/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_common_v2_validate_session_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_v2_validate_session_response_proto_goTypes = []any{
	(*ValidateSessionResponse)(nil), // 0: common.v2.ValidateSessionResponse
	(*Session)(nil),                 // 1: common.v2.Session
	(*UserInfo)(nil),                // 2: common.v2.UserInfo
	(*Error)(nil),                   // 3: common.v2.Error
}
var file_common_v2_validate_session_response_proto_depIdxs = []int32{
	1, // 0: common.v2.ValidateSessionResponse.session:type_name -> common.v2.Session
	2, // 1: common.v2.ValidateSessionResponse.user_info:type_name -> common.v2.UserInfo
	3, // 2: common.v2.ValidateSessionResponse.error:type_name -> common.v2.Error
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_v2_validate_session_response_proto_init() }
func file_common_v2_validate_session_response_proto_init() {
	if File_common_v2_validate_session_response_proto != nil {
		return
	}
	file_common_v2_error_proto_init()
	file_common_v2_session_proto_init()
	file_common_v2_user_info_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v2_validate_session_response_proto_rawDesc), len(file_common_v2_validate_session_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v2_validate_session_response_proto_goTypes,
		DependencyIndexes: file_common_v2_validate_session_response_proto_depIdxs,
		MessageInfos:      file_common_v2_validate_session_response_proto_msgTypes,
	}.Build()
	File_common_v2_validate_session_response_proto = out.File
	file_common_v2_validate_session_response_proto_goTypes = nil
	file_common_v2_validate_session_response_proto_depIdxs = nil
}
