// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: media/v2/media_file.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v2 "github.com/jdfalk/gcommon/pkg/common/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Media file representation with associated metadata and tracks.
type MediaFile struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id             *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Path           *string                `protobuf:"bytes,2,opt,name=path"`
	xxx_hidden_Filename       *string                `protobuf:"bytes,3,opt,name=filename"`
	xxx_hidden_Type           v2.MediaType           `protobuf:"varint,4,opt,name=type,enum=common.v2.MediaType"`
	xxx_hidden_SizeBytes      int64                  `protobuf:"varint,5,opt,name=size_bytes,json=sizeBytes"`
	xxx_hidden_CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt"`
	xxx_hidden_ModifiedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=modified_at,json=modifiedAt"`
	xxx_hidden_Metadata       *MediaMetadata         `protobuf:"bytes,8,opt,name=metadata"`
	xxx_hidden_SubtitleTracks *[]*SubtitleTrack      `protobuf:"bytes,9,rep,name=subtitle_tracks,json=subtitleTracks"`
	xxx_hidden_AudioTracks    *[]*AudioTrack         `protobuf:"bytes,10,rep,name=audio_tracks,json=audioTracks"`
	xxx_hidden_Quality        *MediaQuality          `protobuf:"bytes,11,opt,name=quality"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MediaFile) Reset() {
	*x = MediaFile{}
	mi := &file_media_v2_media_file_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaFile) ProtoMessage() {}

func (x *MediaFile) ProtoReflect() protoreflect.Message {
	mi := &file_media_v2_media_file_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MediaFile) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *MediaFile) GetPath() string {
	if x != nil {
		if x.xxx_hidden_Path != nil {
			return *x.xxx_hidden_Path
		}
		return ""
	}
	return ""
}

func (x *MediaFile) GetFilename() string {
	if x != nil {
		if x.xxx_hidden_Filename != nil {
			return *x.xxx_hidden_Filename
		}
		return ""
	}
	return ""
}

func (x *MediaFile) GetType() v2.MediaType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_Type
		}
	}
	return v2.MediaType(0)
}

func (x *MediaFile) GetSizeBytes() int64 {
	if x != nil {
		return x.xxx_hidden_SizeBytes
	}
	return 0
}

func (x *MediaFile) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_CreatedAt) {
				protoimpl.X.UnmarshalField(x, 6)
			}
			var rv *timestamppb.Timestamp
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_CreatedAt), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *MediaFile) GetModifiedAt() *timestamppb.Timestamp {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 6) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_ModifiedAt) {
				protoimpl.X.UnmarshalField(x, 7)
			}
			var rv *timestamppb.Timestamp
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_ModifiedAt), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *MediaFile) GetMetadata() *MediaMetadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *MediaFile) GetSubtitleTracks() []*SubtitleTrack {
	if x != nil {
		if x.xxx_hidden_SubtitleTracks != nil {
			return *x.xxx_hidden_SubtitleTracks
		}
	}
	return nil
}

func (x *MediaFile) GetAudioTracks() []*AudioTrack {
	if x != nil {
		if x.xxx_hidden_AudioTracks != nil {
			return *x.xxx_hidden_AudioTracks
		}
	}
	return nil
}

func (x *MediaFile) GetQuality() *MediaQuality {
	if x != nil {
		return x.xxx_hidden_Quality
	}
	return nil
}

func (x *MediaFile) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 11)
}

func (x *MediaFile) SetPath(v string) {
	x.xxx_hidden_Path = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 11)
}

func (x *MediaFile) SetFilename(v string) {
	x.xxx_hidden_Filename = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 11)
}

func (x *MediaFile) SetType(v v2.MediaType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 11)
}

func (x *MediaFile) SetSizeBytes(v int64) {
	x.xxx_hidden_SizeBytes = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 11)
}

func (x *MediaFile) SetCreatedAt(v *timestamppb.Timestamp) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_CreatedAt, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 11)
	}
}

func (x *MediaFile) SetModifiedAt(v *timestamppb.Timestamp) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_ModifiedAt, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 11)
	}
}

func (x *MediaFile) SetMetadata(v *MediaMetadata) {
	x.xxx_hidden_Metadata = v
}

func (x *MediaFile) SetSubtitleTracks(v []*SubtitleTrack) {
	x.xxx_hidden_SubtitleTracks = &v
}

func (x *MediaFile) SetAudioTracks(v []*AudioTrack) {
	x.xxx_hidden_AudioTracks = &v
}

func (x *MediaFile) SetQuality(v *MediaQuality) {
	x.xxx_hidden_Quality = v
}

func (x *MediaFile) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MediaFile) HasPath() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MediaFile) HasFilename() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MediaFile) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *MediaFile) HasSizeBytes() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *MediaFile) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *MediaFile) HasModifiedAt() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *MediaFile) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *MediaFile) HasQuality() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Quality != nil
}

func (x *MediaFile) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *MediaFile) ClearPath() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Path = nil
}

func (x *MediaFile) ClearFilename() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Filename = nil
}

func (x *MediaFile) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Type = v2.MediaType_MEDIA_TYPE_UNSPECIFIED
}

func (x *MediaFile) ClearSizeBytes() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_SizeBytes = 0
}

func (x *MediaFile) ClearCreatedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_CreatedAt, (*timestamppb.Timestamp)(nil))
}

func (x *MediaFile) ClearModifiedAt() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_ModifiedAt, (*timestamppb.Timestamp)(nil))
}

func (x *MediaFile) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *MediaFile) ClearQuality() {
	x.xxx_hidden_Quality = nil
}

type MediaFile_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id             *string
	Path           *string
	Filename       *string
	Type           *v2.MediaType
	SizeBytes      *int64
	CreatedAt      *timestamppb.Timestamp
	ModifiedAt     *timestamppb.Timestamp
	Metadata       *MediaMetadata
	SubtitleTracks []*SubtitleTrack
	AudioTracks    []*AudioTrack
	Quality        *MediaQuality
}

func (b0 MediaFile_builder) Build() *MediaFile {
	m0 := &MediaFile{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 11)
		x.xxx_hidden_Id = b.Id
	}
	if b.Path != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 11)
		x.xxx_hidden_Path = b.Path
	}
	if b.Filename != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 11)
		x.xxx_hidden_Filename = b.Filename
	}
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 11)
		x.xxx_hidden_Type = *b.Type
	}
	if b.SizeBytes != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 11)
		x.xxx_hidden_SizeBytes = *b.SizeBytes
	}
	if b.CreatedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 11)
		x.xxx_hidden_CreatedAt = b.CreatedAt
	}
	if b.ModifiedAt != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 11)
		x.xxx_hidden_ModifiedAt = b.ModifiedAt
	}
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_SubtitleTracks = &b.SubtitleTracks
	x.xxx_hidden_AudioTracks = &b.AudioTracks
	x.xxx_hidden_Quality = b.Quality
	return m0
}

var File_media_v2_media_file_proto protoreflect.FileDescriptor

const file_media_v2_media_file_proto_rawDesc = "" +
	"\n" +
	"\x19media/v2/media_file.proto\x12\bmedia.v2\x1a\x1acommon/v2/media_type.proto\x1a\x1amedia/v2/audio_track.proto\x1a\x1dmedia/v2/media_metadata.proto\x1a\x1cmedia/v2/media_quality.proto\x1a\x1dmedia/v2/subtitle_track.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\xd5\x04\n" +
	"\tMediaFile\x12g\n" +
	"\x02id\x18\x01 \x01(\tBW\xbaHT\xc8\x01\x01rO2M^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$R\x02id\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x1a\n" +
	"\bfilename\x18\x03 \x01(\tR\bfilename\x12(\n" +
	"\x04type\x18\x04 \x01(\x0e2\x14.common.v2.MediaTypeR\x04type\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x05 \x01(\x03R\tsizeBytes\x12C\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\b\xbaH\x03\xc8\x01\x01(\x01R\tcreatedAt\x12?\n" +
	"\vmodified_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x02(\x01R\n" +
	"modifiedAt\x123\n" +
	"\bmetadata\x18\b \x01(\v2\x17.media.v2.MediaMetadataR\bmetadata\x12@\n" +
	"\x0fsubtitle_tracks\x18\t \x03(\v2\x17.media.v2.SubtitleTrackR\x0esubtitleTracks\x127\n" +
	"\faudio_tracks\x18\n" +
	" \x03(\v2\x14.media.v2.AudioTrackR\vaudioTracks\x120\n" +
	"\aquality\x18\v \x01(\v2\x16.media.v2.MediaQualityR\aqualityB0Z&github.com/jdfalk/gcommon/pkg/media/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_media_v2_media_file_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_media_v2_media_file_proto_goTypes = []any{
	(*MediaFile)(nil),             // 0: media.v2.MediaFile
	(v2.MediaType)(0),             // 1: common.v2.MediaType
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*MediaMetadata)(nil),         // 3: media.v2.MediaMetadata
	(*SubtitleTrack)(nil),         // 4: media.v2.SubtitleTrack
	(*AudioTrack)(nil),            // 5: media.v2.AudioTrack
	(*MediaQuality)(nil),          // 6: media.v2.MediaQuality
}
var file_media_v2_media_file_proto_depIdxs = []int32{
	1, // 0: media.v2.MediaFile.type:type_name -> common.v2.MediaType
	2, // 1: media.v2.MediaFile.created_at:type_name -> google.protobuf.Timestamp
	2, // 2: media.v2.MediaFile.modified_at:type_name -> google.protobuf.Timestamp
	3, // 3: media.v2.MediaFile.metadata:type_name -> media.v2.MediaMetadata
	4, // 4: media.v2.MediaFile.subtitle_tracks:type_name -> media.v2.SubtitleTrack
	5, // 5: media.v2.MediaFile.audio_tracks:type_name -> media.v2.AudioTrack
	6, // 6: media.v2.MediaFile.quality:type_name -> media.v2.MediaQuality
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_media_v2_media_file_proto_init() }
func file_media_v2_media_file_proto_init() {
	if File_media_v2_media_file_proto != nil {
		return
	}
	file_media_v2_audio_track_proto_init()
	file_media_v2_media_metadata_proto_init()
	file_media_v2_media_quality_proto_init()
	file_media_v2_subtitle_track_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v2_media_file_proto_rawDesc), len(file_media_v2_media_file_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_v2_media_file_proto_goTypes,
		DependencyIndexes: file_media_v2_media_file_proto_depIdxs,
		MessageInfos:      file_media_v2_media_file_proto_msgTypes,
	}.Build()
	File_media_v2_media_file_proto = out.File
	file_media_v2_media_file_proto_goTypes = nil
	file_media_v2_media_file_proto_depIdxs = nil
}
