// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: media/v2/subtitle_service.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_media_v2_subtitle_service_proto protoreflect.FileDescriptor

const file_media_v2_subtitle_service_proto_rawDesc = "" +
	"\n" +
	"\x1fmedia/v2/subtitle_service.proto\x12\bmedia.v2\x1a-media/v2/adjust_subtitle_timing_request.proto\x1a.media/v2/adjust_subtitle_timing_response.proto\x1a.media/v2/convert_subtitle_format_request.proto\x1a/media/v2/convert_subtitle_format_response.proto\x1a&media/v2/merge_subtitles_request.proto\x1a'media/v2/merge_subtitles_response.proto\x1a%media/v2/sync_subtitles_request.proto\x1a&media/v2/sync_subtitles_response.proto\x1a)media/v2/validate_subtitles_request.proto\x1a*media/v2/validate_subtitles_response.proto\x1a!google/protobuf/go_features.proto2\xe7\x03\n" +
	"\x0fSubtitleService\x12S\n" +
	"\x0eMergeSubtitles\x12\x1f.media.v2.MergeSubtitlesRequest\x1a .media.v2.MergeSubtitlesResponse\x12P\n" +
	"\rSyncSubtitles\x12\x1e.media.v2.SyncSubtitlesRequest\x1a\x1f.media.v2.SyncSubtitlesResponse\x12e\n" +
	"\x14AdjustSubtitleTiming\x12%.media.v2.AdjustSubtitleTimingRequest\x1a&.media.v2.AdjustSubtitleTimingResponse\x12h\n" +
	"\x15ConvertSubtitleFormat\x12&.media.v2.ConvertSubtitleFormatRequest\x1a'.media.v2.ConvertSubtitleFormatResponse\x12\\\n" +
	"\x11ValidateSubtitles\x12\".media.v2.ValidateSubtitlesRequest\x1a#.media.v2.ValidateSubtitlesResponseB,Z\"github.com/jdfalk/gcommon/media/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_media_v2_subtitle_service_proto_goTypes = []any{
	(*MergeSubtitlesRequest)(nil),         // 0: media.v2.MergeSubtitlesRequest
	(*SyncSubtitlesRequest)(nil),          // 1: media.v2.SyncSubtitlesRequest
	(*AdjustSubtitleTimingRequest)(nil),   // 2: media.v2.AdjustSubtitleTimingRequest
	(*ConvertSubtitleFormatRequest)(nil),  // 3: media.v2.ConvertSubtitleFormatRequest
	(*ValidateSubtitlesRequest)(nil),      // 4: media.v2.ValidateSubtitlesRequest
	(*MergeSubtitlesResponse)(nil),        // 5: media.v2.MergeSubtitlesResponse
	(*SyncSubtitlesResponse)(nil),         // 6: media.v2.SyncSubtitlesResponse
	(*AdjustSubtitleTimingResponse)(nil),  // 7: media.v2.AdjustSubtitleTimingResponse
	(*ConvertSubtitleFormatResponse)(nil), // 8: media.v2.ConvertSubtitleFormatResponse
	(*ValidateSubtitlesResponse)(nil),     // 9: media.v2.ValidateSubtitlesResponse
}
var file_media_v2_subtitle_service_proto_depIdxs = []int32{
	0, // 0: media.v2.SubtitleService.MergeSubtitles:input_type -> media.v2.MergeSubtitlesRequest
	1, // 1: media.v2.SubtitleService.SyncSubtitles:input_type -> media.v2.SyncSubtitlesRequest
	2, // 2: media.v2.SubtitleService.AdjustSubtitleTiming:input_type -> media.v2.AdjustSubtitleTimingRequest
	3, // 3: media.v2.SubtitleService.ConvertSubtitleFormat:input_type -> media.v2.ConvertSubtitleFormatRequest
	4, // 4: media.v2.SubtitleService.ValidateSubtitles:input_type -> media.v2.ValidateSubtitlesRequest
	5, // 5: media.v2.SubtitleService.MergeSubtitles:output_type -> media.v2.MergeSubtitlesResponse
	6, // 6: media.v2.SubtitleService.SyncSubtitles:output_type -> media.v2.SyncSubtitlesResponse
	7, // 7: media.v2.SubtitleService.AdjustSubtitleTiming:output_type -> media.v2.AdjustSubtitleTimingResponse
	8, // 8: media.v2.SubtitleService.ConvertSubtitleFormat:output_type -> media.v2.ConvertSubtitleFormatResponse
	9, // 9: media.v2.SubtitleService.ValidateSubtitles:output_type -> media.v2.ValidateSubtitlesResponse
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_media_v2_subtitle_service_proto_init() }
func file_media_v2_subtitle_service_proto_init() {
	if File_media_v2_subtitle_service_proto != nil {
		return
	}
	file_media_v2_adjust_subtitle_timing_request_proto_init()
	file_media_v2_adjust_subtitle_timing_response_proto_init()
	file_media_v2_convert_subtitle_format_request_proto_init()
	file_media_v2_convert_subtitle_format_response_proto_init()
	file_media_v2_merge_subtitles_request_proto_init()
	file_media_v2_merge_subtitles_response_proto_init()
	file_media_v2_sync_subtitles_request_proto_init()
	file_media_v2_sync_subtitles_response_proto_init()
	file_media_v2_validate_subtitles_request_proto_init()
	file_media_v2_validate_subtitles_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_v2_subtitle_service_proto_rawDesc), len(file_media_v2_subtitle_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_v2_subtitle_service_proto_goTypes,
		DependencyIndexes: file_media_v2_subtitle_service_proto_depIdxs,
	}.Build()
	File_media_v2_subtitle_service_proto = out.File
	file_media_v2_subtitle_service_proto_goTypes = nil
	file_media_v2_subtitle_service_proto_depIdxs = nil
}
