// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: configpb/v1/config_admin_service.proto

package configpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_configpb_v1_config_admin_service_proto protoreflect.FileDescriptor

const file_configpb_v1_config_admin_service_proto_rawDesc = "" +
	"\n" +
	"&configpb/v1/config_admin_service.proto\x12\tconfig.v1\x1a'configpb/v1/backup_config_request.proto\x1a\x1fconfigpb/v1/config_backup.proto\x1a!configpb/v1/config_snapshot.proto\x1a'configpb/v1/export_config_request.proto\x1a,configpb/v1/get_config_history_request.proto\x1a-configpb/v1/get_config_history_response.proto\x1a*configpb/v1/get_config_stats_request.proto\x1a+configpb/v1/get_config_stats_response.proto\x1a&configpb/v1/health_check_request.proto\x1a'configpb/v1/health_check_response.proto\x1a'configpb/v1/import_config_request.proto\x1a'configpb/v1/reload_config_request.proto\x1a(configpb/v1/restore_config_request.proto\x1a)configpb/v1/rollback_config_request.proto\x1a+configpb/v1/set_config_schema_request.proto\x1a(configpb/v1/unwatch_config_request.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a!google/protobuf/go_features.proto2\xf4\x06\n" +
	"\x12ConfigAdminService\x12G\n" +
	"\fBackupConfig\x12\x1e.config.v1.BackupConfigRequest\x1a\x17.config.v1.ConfigBackup\x12H\n" +
	"\rRestoreConfig\x12\x1f.config.v1.RestoreConfigRequest\x1a\x16.google.protobuf.Empty\x12F\n" +
	"\fImportConfig\x12\x1e.config.v1.ImportConfigRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\fExportConfig\x12\x1e.config.v1.ExportConfigRequest\x1a\x19.config.v1.ConfigSnapshot\x12F\n" +
	"\fReloadConfig\x12\x1e.config.v1.ReloadConfigRequest\x1a\x16.google.protobuf.Empty\x12J\n" +
	"\x0eRollbackConfig\x12 .config.v1.RollbackConfigRequest\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\x0fSetConfigSchema\x12!.config.v1.SetConfigSchemaRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\x10GetConfigHistory\x12\".config.v1.GetConfigHistoryRequest\x1a#.config.v1.GetConfigHistoryResponse\x12U\n" +
	"\x0eGetConfigStats\x12 .config.v1.GetConfigStatsRequest\x1a!.config.v1.GetConfigStatsResponse\x12X\n" +
	"\vHealthCheck\x12#.config.v1.ConfigHealthCheckRequest\x1a$.config.v1.ConfigHealthCheckResponse\x12H\n" +
	"\rUnwatchConfig\x12\x1f.config.v1.UnwatchConfigRequest\x1a\x16.google.protobuf.EmptyB\x9d\x01\n" +
	"\rcom.config.v1B\x17ConfigAdminServiceProtoP\x01Z&github.com/jdfalk/gcommon/pkg/configpb\xa2\x02\x03CXX\xaa\x02\tConfig.V1\xca\x02\tConfig\\V1\xe2\x02\x15Config\\V1\\GPBMetadata\xea\x02\n" +
	"Config::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_configpb_v1_config_admin_service_proto_goTypes = []any{
	(*BackupConfigRequest)(nil),       // 0: config.v1.BackupConfigRequest
	(*RestoreConfigRequest)(nil),      // 1: config.v1.RestoreConfigRequest
	(*ImportConfigRequest)(nil),       // 2: config.v1.ImportConfigRequest
	(*ExportConfigRequest)(nil),       // 3: config.v1.ExportConfigRequest
	(*ReloadConfigRequest)(nil),       // 4: config.v1.ReloadConfigRequest
	(*RollbackConfigRequest)(nil),     // 5: config.v1.RollbackConfigRequest
	(*SetConfigSchemaRequest)(nil),    // 6: config.v1.SetConfigSchemaRequest
	(*GetConfigHistoryRequest)(nil),   // 7: config.v1.GetConfigHistoryRequest
	(*GetConfigStatsRequest)(nil),     // 8: config.v1.GetConfigStatsRequest
	(*ConfigHealthCheckRequest)(nil),  // 9: config.v1.ConfigHealthCheckRequest
	(*UnwatchConfigRequest)(nil),      // 10: config.v1.UnwatchConfigRequest
	(*ConfigBackup)(nil),              // 11: config.v1.ConfigBackup
	(*emptypb.Empty)(nil),             // 12: google.protobuf.Empty
	(*ConfigSnapshot)(nil),            // 13: config.v1.ConfigSnapshot
	(*GetConfigHistoryResponse)(nil),  // 14: config.v1.GetConfigHistoryResponse
	(*GetConfigStatsResponse)(nil),    // 15: config.v1.GetConfigStatsResponse
	(*ConfigHealthCheckResponse)(nil), // 16: config.v1.ConfigHealthCheckResponse
}
var file_configpb_v1_config_admin_service_proto_depIdxs = []int32{
	0,  // 0: config.v1.ConfigAdminService.BackupConfig:input_type -> config.v1.BackupConfigRequest
	1,  // 1: config.v1.ConfigAdminService.RestoreConfig:input_type -> config.v1.RestoreConfigRequest
	2,  // 2: config.v1.ConfigAdminService.ImportConfig:input_type -> config.v1.ImportConfigRequest
	3,  // 3: config.v1.ConfigAdminService.ExportConfig:input_type -> config.v1.ExportConfigRequest
	4,  // 4: config.v1.ConfigAdminService.ReloadConfig:input_type -> config.v1.ReloadConfigRequest
	5,  // 5: config.v1.ConfigAdminService.RollbackConfig:input_type -> config.v1.RollbackConfigRequest
	6,  // 6: config.v1.ConfigAdminService.SetConfigSchema:input_type -> config.v1.SetConfigSchemaRequest
	7,  // 7: config.v1.ConfigAdminService.GetConfigHistory:input_type -> config.v1.GetConfigHistoryRequest
	8,  // 8: config.v1.ConfigAdminService.GetConfigStats:input_type -> config.v1.GetConfigStatsRequest
	9,  // 9: config.v1.ConfigAdminService.HealthCheck:input_type -> config.v1.ConfigHealthCheckRequest
	10, // 10: config.v1.ConfigAdminService.UnwatchConfig:input_type -> config.v1.UnwatchConfigRequest
	11, // 11: config.v1.ConfigAdminService.BackupConfig:output_type -> config.v1.ConfigBackup
	12, // 12: config.v1.ConfigAdminService.RestoreConfig:output_type -> google.protobuf.Empty
	12, // 13: config.v1.ConfigAdminService.ImportConfig:output_type -> google.protobuf.Empty
	13, // 14: config.v1.ConfigAdminService.ExportConfig:output_type -> config.v1.ConfigSnapshot
	12, // 15: config.v1.ConfigAdminService.ReloadConfig:output_type -> google.protobuf.Empty
	12, // 16: config.v1.ConfigAdminService.RollbackConfig:output_type -> google.protobuf.Empty
	12, // 17: config.v1.ConfigAdminService.SetConfigSchema:output_type -> google.protobuf.Empty
	14, // 18: config.v1.ConfigAdminService.GetConfigHistory:output_type -> config.v1.GetConfigHistoryResponse
	15, // 19: config.v1.ConfigAdminService.GetConfigStats:output_type -> config.v1.GetConfigStatsResponse
	16, // 20: config.v1.ConfigAdminService.HealthCheck:output_type -> config.v1.ConfigHealthCheckResponse
	12, // 21: config.v1.ConfigAdminService.UnwatchConfig:output_type -> google.protobuf.Empty
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_configpb_v1_config_admin_service_proto_init() }
func file_configpb_v1_config_admin_service_proto_init() {
	if File_configpb_v1_config_admin_service_proto != nil {
		return
	}
	file_configpb_v1_backup_config_request_proto_init()
	file_configpb_v1_config_backup_proto_init()
	file_configpb_v1_config_snapshot_proto_init()
	file_configpb_v1_export_config_request_proto_init()
	file_configpb_v1_get_config_history_request_proto_init()
	file_configpb_v1_get_config_history_response_proto_init()
	file_configpb_v1_get_config_stats_request_proto_init()
	file_configpb_v1_get_config_stats_response_proto_init()
	file_configpb_v1_health_check_request_proto_init()
	file_configpb_v1_health_check_response_proto_init()
	file_configpb_v1_import_config_request_proto_init()
	file_configpb_v1_reload_config_request_proto_init()
	file_configpb_v1_restore_config_request_proto_init()
	file_configpb_v1_rollback_config_request_proto_init()
	file_configpb_v1_set_config_schema_request_proto_init()
	file_configpb_v1_unwatch_config_request_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_configpb_v1_config_admin_service_proto_rawDesc), len(file_configpb_v1_config_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_configpb_v1_config_admin_service_proto_goTypes,
		DependencyIndexes: file_configpb_v1_config_admin_service_proto_depIdxs,
	}.Build()
	File_configpb_v1_config_admin_service_proto = out.File
	file_configpb_v1_config_admin_service_proto_goTypes = nil
	file_configpb_v1_config_admin_service_proto_depIdxs = nil
}
