// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: databasepb/v2/health_check_response.proto

package v2

import (
	v2 "github.com/jdfalk/gcommon/pkg/commonpb/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// HealthCheckResponse contains the result of a database health check.
// Provides connection status, response time, and error details.
type DatabaseHealthCheckResponse struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Status       v2.CommonHealthStatus  `protobuf:"varint,1,opt,name=status,enum=common.v2.CommonHealthStatus"`
	xxx_hidden_ConnectionOk bool                   `protobuf:"varint,2,opt,name=connection_ok,json=connectionOk"`
	xxx_hidden_ResponseTime *durationpb.Duration   `protobuf:"bytes,3,opt,name=response_time,json=responseTime"`
	xxx_hidden_Error        *v2.Error              `protobuf:"bytes,4,opt,name=error"`
	// Deprecated: Do not use. This will be deleted in the near future.
	XXX_lazyUnmarshalInfo  protoimpl.LazyUnmarshalInfo
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DatabaseHealthCheckResponse) Reset() {
	*x = DatabaseHealthCheckResponse{}
	mi := &file_databasepb_v2_health_check_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatabaseHealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatabaseHealthCheckResponse) ProtoMessage() {}

func (x *DatabaseHealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_databasepb_v2_health_check_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DatabaseHealthCheckResponse) GetStatus() v2.CommonHealthStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Status
		}
	}
	return v2.CommonHealthStatus(0)
}

func (x *DatabaseHealthCheckResponse) GetConnectionOk() bool {
	if x != nil {
		return x.xxx_hidden_ConnectionOk
	}
	return false
}

func (x *DatabaseHealthCheckResponse) GetResponseTime() *durationpb.Duration {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 2) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_ResponseTime) {
				protoimpl.X.UnmarshalField(x, 3)
			}
			var rv *durationpb.Duration
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_ResponseTime), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *DatabaseHealthCheckResponse) GetError() *v2.Error {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			if protoimpl.X.AtomicCheckPointerIsNil(&x.xxx_hidden_Error) {
				protoimpl.X.UnmarshalField(x, 4)
			}
			var rv *v2.Error
			protoimpl.X.AtomicLoadPointer(protoimpl.Pointer(&x.xxx_hidden_Error), protoimpl.Pointer(&rv))
			return rv
		}
	}
	return nil
}

func (x *DatabaseHealthCheckResponse) SetStatus(v v2.CommonHealthStatus) {
	x.xxx_hidden_Status = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *DatabaseHealthCheckResponse) SetConnectionOk(v bool) {
	x.xxx_hidden_ConnectionOk = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *DatabaseHealthCheckResponse) SetResponseTime(v *durationpb.Duration) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_ResponseTime, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
	}
}

func (x *DatabaseHealthCheckResponse) SetError(v *v2.Error) {
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Error, v)
	if v == nil {
		protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	} else {
		protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
	}
}

func (x *DatabaseHealthCheckResponse) HasStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DatabaseHealthCheckResponse) HasConnectionOk() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DatabaseHealthCheckResponse) HasResponseTime() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DatabaseHealthCheckResponse) HasError() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DatabaseHealthCheckResponse) ClearStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Status = v2.CommonHealthStatus_HEALTH_STATUS_UNSPECIFIED
}

func (x *DatabaseHealthCheckResponse) ClearConnectionOk() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_ConnectionOk = false
}

func (x *DatabaseHealthCheckResponse) ClearResponseTime() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_ResponseTime, (*durationpb.Duration)(nil))
}

func (x *DatabaseHealthCheckResponse) ClearError() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	protoimpl.X.AtomicSetPointer(&x.xxx_hidden_Error, (*v2.Error)(nil))
}

type DatabaseHealthCheckResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Overall health status of the database
	Status *v2.CommonHealthStatus
	// Whether the database connection is operational
	ConnectionOk *bool
	// Time taken to perform the health check
	ResponseTime *durationpb.Duration
	// Error information if the health check failed
	Error *v2.Error
}

func (b0 DatabaseHealthCheckResponse_builder) Build() *DatabaseHealthCheckResponse {
	m0 := &DatabaseHealthCheckResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Status != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Status = *b.Status
	}
	if b.ConnectionOk != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_ConnectionOk = *b.ConnectionOk
	}
	if b.ResponseTime != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ResponseTime = b.ResponseTime
	}
	if b.Error != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Error = b.Error
	}
	return m0
}

var File_databasepb_v2_health_check_response_proto protoreflect.FileDescriptor

const file_databasepb_v2_health_check_response_proto_rawDesc = "" +
	"\n" +
	")databasepb/v2/health_check_response.proto\x12\vdatabase.v2\x1a\x17commonpb/v2/error.proto\x1a\x1fcommonpb/v2/health_status.proto\x1a\x1egoogle/protobuf/duration.proto\x1a!google/protobuf/go_features.proto\"\xe9\x01\n" +
	"\x1bDatabaseHealthCheckResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.common.v2.CommonHealthStatusR\x06status\x12#\n" +
	"\rconnection_ok\x18\x02 \x01(\bR\fconnectionOk\x12B\n" +
	"\rresponse_time\x18\x03 \x01(\v2\x19.google.protobuf.DurationB\x02(\x01R\fresponseTime\x12*\n" +
	"\x05error\x18\x04 \x01(\v2\x10.common.v2.ErrorB\x02(\x01R\x05errorB\xad\x01\n" +
	"\x0fcom.database.v2B\x18HealthCheckResponseProtoP\x01Z+github.com/jdfalk/gcommon/pkg/databasepb/v2\xa2\x02\x03DXX\xaa\x02\vDatabase.V2\xca\x02\vDatabase\\V2\xe2\x02\x17Database\\V2\\GPBMetadata\xea\x02\fDatabase::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_databasepb_v2_health_check_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_databasepb_v2_health_check_response_proto_goTypes = []any{
	(*DatabaseHealthCheckResponse)(nil), // 0: database.v2.DatabaseHealthCheckResponse
	(v2.CommonHealthStatus)(0),          // 1: common.v2.CommonHealthStatus
	(*durationpb.Duration)(nil),         // 2: google.protobuf.Duration
	(*v2.Error)(nil),                    // 3: common.v2.Error
}
var file_databasepb_v2_health_check_response_proto_depIdxs = []int32{
	1, // 0: database.v2.DatabaseHealthCheckResponse.status:type_name -> common.v2.CommonHealthStatus
	2, // 1: database.v2.DatabaseHealthCheckResponse.response_time:type_name -> google.protobuf.Duration
	3, // 2: database.v2.DatabaseHealthCheckResponse.error:type_name -> common.v2.Error
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_databasepb_v2_health_check_response_proto_init() }
func file_databasepb_v2_health_check_response_proto_init() {
	if File_databasepb_v2_health_check_response_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_databasepb_v2_health_check_response_proto_rawDesc), len(file_databasepb_v2_health_check_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_databasepb_v2_health_check_response_proto_goTypes,
		DependencyIndexes: file_databasepb_v2_health_check_response_proto_depIdxs,
		MessageInfos:      file_databasepb_v2_health_check_response_proto_msgTypes,
	}.Build()
	File_databasepb_v2_health_check_response_proto = out.File
	file_databasepb_v2_health_check_response_proto_goTypes = nil
	file_databasepb_v2_health_check_response_proto_depIdxs = nil
}
