// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: queue/v1/get_queue_health_response.proto

package queue

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetQueueHealthResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_QueueHealth   *[]*QueueHealth        `protobuf:"bytes,1,rep,name=queue_health,json=queueHealth"`
	xxx_hidden_ClusterHealth *ClusterHealth         `protobuf:"bytes,2,opt,name=cluster_health,json=clusterHealth"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetQueueHealthResponse) Reset() {
	*x = GetQueueHealthResponse{}
	mi := &file_queue_v1_get_queue_health_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetQueueHealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetQueueHealthResponse) ProtoMessage() {}

func (x *GetQueueHealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_get_queue_health_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetQueueHealthResponse) GetQueueHealth() []*QueueHealth {
	if x != nil {
		if x.xxx_hidden_QueueHealth != nil {
			return *x.xxx_hidden_QueueHealth
		}
	}
	return nil
}

func (x *GetQueueHealthResponse) GetClusterHealth() *ClusterHealth {
	if x != nil {
		return x.xxx_hidden_ClusterHealth
	}
	return nil
}

func (x *GetQueueHealthResponse) SetQueueHealth(v []*QueueHealth) {
	x.xxx_hidden_QueueHealth = &v
}

func (x *GetQueueHealthResponse) SetClusterHealth(v *ClusterHealth) {
	x.xxx_hidden_ClusterHealth = v
}

func (x *GetQueueHealthResponse) HasClusterHealth() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ClusterHealth != nil
}

func (x *GetQueueHealthResponse) ClearClusterHealth() {
	x.xxx_hidden_ClusterHealth = nil
}

type GetQueueHealthResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Health status for each queue
	QueueHealth []*QueueHealth
	// Overall cluster health
	ClusterHealth *ClusterHealth
}

func (b0 GetQueueHealthResponse_builder) Build() *GetQueueHealthResponse {
	m0 := &GetQueueHealthResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_QueueHealth = &b.QueueHealth
	x.xxx_hidden_ClusterHealth = b.ClusterHealth
	return m0
}

var File_queue_v1_get_queue_health_response_proto protoreflect.FileDescriptor

const file_queue_v1_get_queue_health_response_proto_rawDesc = "" +
	"\n" +
	"(queue/v1/get_queue_health_response.proto\x12\bqueue.v1\x1a\x1dqueue/v1/cluster_health.proto\x1a\x1bqueue/v1/queue_health.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\x9c\x01\n" +
	"\x16GetQueueHealthResponse\x12B\n" +
	"\fqueue_health\x18\x01 \x03(\v2\x15.queue.v1.QueueHealthB\b\xbaH\x05\x92\x01\x02\b\x01R\vqueueHealth\x12>\n" +
	"\x0ecluster_health\x18\x02 \x01(\v2\x17.queue.v1.ClusterHealthR\rclusterHealthB-Z#github.com/jdfalk/gcommon/pkg/queue\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_queue_v1_get_queue_health_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_queue_v1_get_queue_health_response_proto_goTypes = []any{
	(*GetQueueHealthResponse)(nil), // 0: queue.v1.GetQueueHealthResponse
	(*QueueHealth)(nil),            // 1: queue.v1.QueueHealth
	(*ClusterHealth)(nil),          // 2: queue.v1.ClusterHealth
}
var file_queue_v1_get_queue_health_response_proto_depIdxs = []int32{
	1, // 0: queue.v1.GetQueueHealthResponse.queue_health:type_name -> queue.v1.QueueHealth
	2, // 1: queue.v1.GetQueueHealthResponse.cluster_health:type_name -> queue.v1.ClusterHealth
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_queue_v1_get_queue_health_response_proto_init() }
func file_queue_v1_get_queue_health_response_proto_init() {
	if File_queue_v1_get_queue_health_response_proto != nil {
		return
	}
	file_queue_v1_cluster_health_proto_init()
	file_queue_v1_queue_health_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queue_v1_get_queue_health_response_proto_rawDesc), len(file_queue_v1_get_queue_health_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_queue_v1_get_queue_health_response_proto_goTypes,
		DependencyIndexes: file_queue_v1_get_queue_health_response_proto_depIdxs,
		MessageInfos:      file_queue_v1_get_queue_health_response_proto_msgTypes,
	}.Build()
	File_queue_v1_get_queue_health_response_proto = out.File
	file_queue_v1_get_queue_health_response_proto_goTypes = nil
	file_queue_v1_get_queue_health_response_proto_depIdxs = nil
}
