// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: queue/v1/list_queues_response.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/jdfalk/gcommon/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListQueuesResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Queues        *[]*QueueInfo          `protobuf:"bytes,1,rep,name=queues"`
	xxx_hidden_NextPageToken *string                `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken"`
	xxx_hidden_Metadata      *v1.ResponseMetadata   `protobuf:"bytes,3,opt,name=metadata"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ListQueuesResponse) Reset() {
	*x = ListQueuesResponse{}
	mi := &file_queue_v1_list_queues_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListQueuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListQueuesResponse) ProtoMessage() {}

func (x *ListQueuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_list_queues_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListQueuesResponse) GetQueues() []*QueueInfo {
	if x != nil {
		if x.xxx_hidden_Queues != nil {
			return *x.xxx_hidden_Queues
		}
	}
	return nil
}

func (x *ListQueuesResponse) GetNextPageToken() string {
	if x != nil {
		if x.xxx_hidden_NextPageToken != nil {
			return *x.xxx_hidden_NextPageToken
		}
		return ""
	}
	return ""
}

func (x *ListQueuesResponse) GetMetadata() *v1.ResponseMetadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ListQueuesResponse) SetQueues(v []*QueueInfo) {
	x.xxx_hidden_Queues = &v
}

func (x *ListQueuesResponse) SetNextPageToken(v string) {
	x.xxx_hidden_NextPageToken = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ListQueuesResponse) SetMetadata(v *v1.ResponseMetadata) {
	x.xxx_hidden_Metadata = v
}

func (x *ListQueuesResponse) HasNextPageToken() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ListQueuesResponse) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *ListQueuesResponse) ClearNextPageToken() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NextPageToken = nil
}

func (x *ListQueuesResponse) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

type ListQueuesResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Collection of queues
	Queues []*QueueInfo
	// Token to retrieve the next page
	NextPageToken *string
	// Standard response metadata
	Metadata *v1.ResponseMetadata
}

func (b0 ListQueuesResponse_builder) Build() *ListQueuesResponse {
	m0 := &ListQueuesResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Queues = &b.Queues
	if b.NextPageToken != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_NextPageToken = b.NextPageToken
	}
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

var File_queue_v1_list_queues_response_proto protoreflect.FileDescriptor

const file_queue_v1_list_queues_response_proto_rawDesc = "" +
	"\n" +
	"#queue/v1/list_queues_response.proto\x12\bqueue.v1\x1a!common/v1/response_metadata.proto\x1a\x19queue/v1/queue_info.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xb5\x01\n" +
	"\x12ListQueuesResponse\x125\n" +
	"\x06queues\x18\x01 \x03(\v2\x13.queue.v1.QueueInfoB\b\xbaH\x05\x92\x01\x02\b\x01R\x06queues\x12/\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\rnextPageToken\x127\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1b.common.v1.ResponseMetadataR\bmetadataB,Z\"github.com/jdfalk/gcommon/queue/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_queue_v1_list_queues_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_queue_v1_list_queues_response_proto_goTypes = []any{
	(*ListQueuesResponse)(nil),  // 0: queue.v1.ListQueuesResponse
	(*QueueInfo)(nil),           // 1: queue.v1.QueueInfo
	(*v1.ResponseMetadata)(nil), // 2: common.v1.ResponseMetadata
}
var file_queue_v1_list_queues_response_proto_depIdxs = []int32{
	1, // 0: queue.v1.ListQueuesResponse.queues:type_name -> queue.v1.QueueInfo
	2, // 1: queue.v1.ListQueuesResponse.metadata:type_name -> common.v1.ResponseMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_queue_v1_list_queues_response_proto_init() }
func file_queue_v1_list_queues_response_proto_init() {
	if File_queue_v1_list_queues_response_proto != nil {
		return
	}
	file_queue_v1_queue_info_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queue_v1_list_queues_response_proto_rawDesc), len(file_queue_v1_list_queues_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_queue_v1_list_queues_response_proto_goTypes,
		DependencyIndexes: file_queue_v1_list_queues_response_proto_depIdxs,
		MessageInfos:      file_queue_v1_list_queues_response_proto_msgTypes,
	}.Build()
	File_queue_v1_list_queues_response_proto = out.File
	file_queue_v1_list_queues_response_proto_goTypes = nil
	file_queue_v1_list_queues_response_proto_depIdxs = nil
}
