// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: queuepb/v1/queue_stats_response.proto

package queuepb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueueStatsResponse struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Stats      *QueueStats            `protobuf:"bytes,1,opt,name=stats"`
	xxx_hidden_TimeSeries *[]*QueueStatsPoint    `protobuf:"bytes,2,rep,name=time_series,json=timeSeries"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *QueueStatsResponse) Reset() {
	*x = QueueStatsResponse{}
	mi := &file_queuepb_v1_queue_stats_response_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStatsResponse) ProtoMessage() {}

func (x *QueueStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queuepb_v1_queue_stats_response_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *QueueStatsResponse) GetStats() *QueueStats {
	if x != nil {
		return x.xxx_hidden_Stats
	}
	return nil
}

func (x *QueueStatsResponse) GetTimeSeries() []*QueueStatsPoint {
	if x != nil {
		if x.xxx_hidden_TimeSeries != nil {
			return *x.xxx_hidden_TimeSeries
		}
	}
	return nil
}

func (x *QueueStatsResponse) SetStats(v *QueueStats) {
	x.xxx_hidden_Stats = v
}

func (x *QueueStatsResponse) SetTimeSeries(v []*QueueStatsPoint) {
	x.xxx_hidden_TimeSeries = &v
}

func (x *QueueStatsResponse) HasStats() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Stats != nil
}

func (x *QueueStatsResponse) ClearStats() {
	x.xxx_hidden_Stats = nil
}

type QueueStatsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Queue statistics
	Stats *QueueStats
	// Time series data
	TimeSeries []*QueueStatsPoint
}

func (b0 QueueStatsResponse_builder) Build() *QueueStatsResponse {
	m0 := &QueueStatsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Stats = b.Stats
	x.xxx_hidden_TimeSeries = &b.TimeSeries
	return m0
}

var File_queuepb_v1_queue_stats_response_proto protoreflect.FileDescriptor

const file_queuepb_v1_queue_stats_response_proto_rawDesc = "" +
	"\n" +
	"%queuepb/v1/queue_stats_response.proto\x12\bqueue.v1\x1a\x1cqueuepb/v1/queue_stats.proto\x1a\"queuepb/v1/queue_stats_point.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\x86\x01\n" +
	"\x12QueueStatsResponse\x12*\n" +
	"\x05stats\x18\x01 \x01(\v2\x14.queue.v1.QueueStatsR\x05stats\x12D\n" +
	"\vtime_series\x18\x02 \x03(\v2\x19.queue.v1.QueueStatsPointB\b\xbaH\x05\x92\x01\x02\b\x01R\n" +
	"timeSeriesB\x97\x01\n" +
	"\fcom.queue.v1B\x17QueueStatsResponseProtoP\x01Z%github.com/jdfalk/gcommon/pkg/queuepb\xa2\x02\x03QXX\xaa\x02\bQueue.V1\xca\x02\bQueue\\V1\xe2\x02\x14Queue\\V1\\GPBMetadata\xea\x02\tQueue::V1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_queuepb_v1_queue_stats_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_queuepb_v1_queue_stats_response_proto_goTypes = []any{
	(*QueueStatsResponse)(nil), // 0: queue.v1.QueueStatsResponse
	(*QueueStats)(nil),         // 1: queue.v1.QueueStats
	(*QueueStatsPoint)(nil),    // 2: queue.v1.QueueStatsPoint
}
var file_queuepb_v1_queue_stats_response_proto_depIdxs = []int32{
	1, // 0: queue.v1.QueueStatsResponse.stats:type_name -> queue.v1.QueueStats
	2, // 1: queue.v1.QueueStatsResponse.time_series:type_name -> queue.v1.QueueStatsPoint
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_queuepb_v1_queue_stats_response_proto_init() }
func file_queuepb_v1_queue_stats_response_proto_init() {
	if File_queuepb_v1_queue_stats_response_proto != nil {
		return
	}
	file_queuepb_v1_queue_stats_proto_init()
	file_queuepb_v1_queue_stats_point_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queuepb_v1_queue_stats_response_proto_rawDesc), len(file_queuepb_v1_queue_stats_response_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_queuepb_v1_queue_stats_response_proto_goTypes,
		DependencyIndexes: file_queuepb_v1_queue_stats_response_proto_depIdxs,
		MessageInfos:      file_queuepb_v1_queue_stats_response_proto_msgTypes,
	}.Build()
	File_queuepb_v1_queue_stats_response_proto = out.File
	file_queuepb_v1_queue_stats_response_proto_goTypes = nil
	file_queuepb_v1_queue_stats_response_proto_depIdxs = nil
}
