// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: config/v1/validate_config_request.proto

package v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/jdfalk/gcommon/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ValidateConfigRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Entries     *[]*ConfigEntry        `protobuf:"bytes,1,rep,name=entries"`
	xxx_hidden_SchemaName  *string                `protobuf:"bytes,2,opt,name=schema_name,json=schemaName"`
	xxx_hidden_Metadata    *v1.RequestMetadata    `protobuf:"bytes,3,opt,name=metadata"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ValidateConfigRequest) Reset() {
	*x = ValidateConfigRequest{}
	mi := &file_config_v1_validate_config_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateConfigRequest) ProtoMessage() {}

func (x *ValidateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_config_v1_validate_config_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValidateConfigRequest) GetEntries() []*ConfigEntry {
	if x != nil {
		if x.xxx_hidden_Entries != nil {
			return *x.xxx_hidden_Entries
		}
	}
	return nil
}

func (x *ValidateConfigRequest) GetSchemaName() string {
	if x != nil {
		if x.xxx_hidden_SchemaName != nil {
			return *x.xxx_hidden_SchemaName
		}
		return ""
	}
	return ""
}

func (x *ValidateConfigRequest) GetMetadata() *v1.RequestMetadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ValidateConfigRequest) SetEntries(v []*ConfigEntry) {
	x.xxx_hidden_Entries = &v
}

func (x *ValidateConfigRequest) SetSchemaName(v string) {
	x.xxx_hidden_SchemaName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *ValidateConfigRequest) SetMetadata(v *v1.RequestMetadata) {
	x.xxx_hidden_Metadata = v
}

func (x *ValidateConfigRequest) HasSchemaName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ValidateConfigRequest) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *ValidateConfigRequest) ClearSchemaName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_SchemaName = nil
}

func (x *ValidateConfigRequest) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

type ValidateConfigRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Configuration entries to validate
	Entries []*ConfigEntry
	// Schema to validate against
	SchemaName *string
	// Request metadata
	Metadata *v1.RequestMetadata
}

func (b0 ValidateConfigRequest_builder) Build() *ValidateConfigRequest {
	m0 := &ValidateConfigRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Entries = &b.Entries
	if b.SchemaName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_SchemaName = b.SchemaName
	}
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

var File_config_v1_validate_config_request_proto protoreflect.FileDescriptor

const file_config_v1_validate_config_request_proto_rawDesc = "" +
	"\n" +
	"'config/v1/validate_config_request.proto\x12\tconfig.v1\x1a common/v1/request_metadata.proto\x1a\x1cconfig/v1/config_entry.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xad\x01\n" +
	"\x15ValidateConfigRequest\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.config.v1.ConfigEntryR\aentries\x12*\n" +
	"\vschema_name\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\n" +
	"schemaName\x126\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1a.common.v1.RequestMetadataR\bmetadataB-Z#github.com/jdfalk/gcommon/config/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_config_v1_validate_config_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_config_v1_validate_config_request_proto_goTypes = []any{
	(*ValidateConfigRequest)(nil), // 0: config.v1.ValidateConfigRequest
	(*ConfigEntry)(nil),           // 1: config.v1.ConfigEntry
	(*v1.RequestMetadata)(nil),    // 2: common.v1.RequestMetadata
}
var file_config_v1_validate_config_request_proto_depIdxs = []int32{
	1, // 0: config.v1.ValidateConfigRequest.entries:type_name -> config.v1.ConfigEntry
	2, // 1: config.v1.ValidateConfigRequest.metadata:type_name -> common.v1.RequestMetadata
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_config_v1_validate_config_request_proto_init() }
func file_config_v1_validate_config_request_proto_init() {
	if File_config_v1_validate_config_request_proto != nil {
		return
	}
	file_config_v1_config_entry_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_config_v1_validate_config_request_proto_rawDesc), len(file_config_v1_validate_config_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_config_v1_validate_config_request_proto_goTypes,
		DependencyIndexes: file_config_v1_validate_config_request_proto_depIdxs,
		MessageInfos:      file_config_v1_validate_config_request_proto_msgTypes,
	}.Build()
	File_config_v1_validate_config_request_proto = out.File
	file_config_v1_validate_config_request_proto_goTypes = nil
	file_config_v1_validate_config_request_proto_depIdxs = nil
}
