// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: queue/v2/durability_config.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v2 "github.com/jdfalk/gcommon/pkg/common/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Configuration for message durability and persistence.
type DurabilityConfig struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Persistent        bool                   `protobuf:"varint,1,opt,name=persistent"`
	xxx_hidden_FlushPolicy       v2.FlushPolicy         `protobuf:"varint,2,opt,name=flush_policy,json=flushPolicy,enum=common.v2.FlushPolicy"`
	xxx_hidden_ReplicationFactor int32                  `protobuf:"varint,3,opt,name=replication_factor,json=replicationFactor"`
	xxx_hidden_AckLevel          v2.AckLevel            `protobuf:"varint,4,opt,name=ack_level,json=ackLevel,enum=common.v2.AckLevel"`
	xxx_hidden_DurabilityTimeout *durationpb.Duration   `protobuf:"bytes,5,opt,name=durability_timeout,json=durabilityTimeout"`
	xxx_hidden_WriteAheadLog     bool                   `protobuf:"varint,6,opt,name=write_ahead_log,json=writeAheadLog"`
	xxx_hidden_SyncInterval      *durationpb.Duration   `protobuf:"bytes,7,opt,name=sync_interval,json=syncInterval"`
	xxx_hidden_VerifyChecksums   bool                   `protobuf:"varint,8,opt,name=verify_checksums,json=verifyChecksums"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *DurabilityConfig) Reset() {
	*x = DurabilityConfig{}
	mi := &file_queue_v2_durability_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DurabilityConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DurabilityConfig) ProtoMessage() {}

func (x *DurabilityConfig) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v2_durability_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DurabilityConfig) GetPersistent() bool {
	if x != nil {
		return x.xxx_hidden_Persistent
	}
	return false
}

func (x *DurabilityConfig) GetFlushPolicy() v2.FlushPolicy {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 1) {
			return x.xxx_hidden_FlushPolicy
		}
	}
	return v2.FlushPolicy(0)
}

func (x *DurabilityConfig) GetReplicationFactor() int32 {
	if x != nil {
		return x.xxx_hidden_ReplicationFactor
	}
	return 0
}

func (x *DurabilityConfig) GetAckLevel() v2.AckLevel {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 3) {
			return x.xxx_hidden_AckLevel
		}
	}
	return v2.AckLevel(0)
}

func (x *DurabilityConfig) GetDurabilityTimeout() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_DurabilityTimeout
	}
	return nil
}

func (x *DurabilityConfig) GetWriteAheadLog() bool {
	if x != nil {
		return x.xxx_hidden_WriteAheadLog
	}
	return false
}

func (x *DurabilityConfig) GetSyncInterval() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_SyncInterval
	}
	return nil
}

func (x *DurabilityConfig) GetVerifyChecksums() bool {
	if x != nil {
		return x.xxx_hidden_VerifyChecksums
	}
	return false
}

func (x *DurabilityConfig) SetPersistent(v bool) {
	x.xxx_hidden_Persistent = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *DurabilityConfig) SetFlushPolicy(v v2.FlushPolicy) {
	x.xxx_hidden_FlushPolicy = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *DurabilityConfig) SetReplicationFactor(v int32) {
	x.xxx_hidden_ReplicationFactor = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *DurabilityConfig) SetAckLevel(v v2.AckLevel) {
	x.xxx_hidden_AckLevel = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *DurabilityConfig) SetDurabilityTimeout(v *durationpb.Duration) {
	x.xxx_hidden_DurabilityTimeout = v
}

func (x *DurabilityConfig) SetWriteAheadLog(v bool) {
	x.xxx_hidden_WriteAheadLog = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *DurabilityConfig) SetSyncInterval(v *durationpb.Duration) {
	x.xxx_hidden_SyncInterval = v
}

func (x *DurabilityConfig) SetVerifyChecksums(v bool) {
	x.xxx_hidden_VerifyChecksums = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 8)
}

func (x *DurabilityConfig) HasPersistent() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DurabilityConfig) HasFlushPolicy() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *DurabilityConfig) HasReplicationFactor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *DurabilityConfig) HasAckLevel() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *DurabilityConfig) HasDurabilityTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DurabilityTimeout != nil
}

func (x *DurabilityConfig) HasWriteAheadLog() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *DurabilityConfig) HasSyncInterval() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_SyncInterval != nil
}

func (x *DurabilityConfig) HasVerifyChecksums() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *DurabilityConfig) ClearPersistent() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Persistent = false
}

func (x *DurabilityConfig) ClearFlushPolicy() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_FlushPolicy = v2.FlushPolicy_FLUSH_POLICY_UNSPECIFIED
}

func (x *DurabilityConfig) ClearReplicationFactor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ReplicationFactor = 0
}

func (x *DurabilityConfig) ClearAckLevel() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_AckLevel = v2.AckLevel_ACK_LEVEL_UNSPECIFIED
}

func (x *DurabilityConfig) ClearDurabilityTimeout() {
	x.xxx_hidden_DurabilityTimeout = nil
}

func (x *DurabilityConfig) ClearWriteAheadLog() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_WriteAheadLog = false
}

func (x *DurabilityConfig) ClearSyncInterval() {
	x.xxx_hidden_SyncInterval = nil
}

func (x *DurabilityConfig) ClearVerifyChecksums() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_VerifyChecksums = false
}

type DurabilityConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether messages are persisted to disk
	Persistent *bool
	// Flush policy for writing messages to storage
	FlushPolicy *v2.FlushPolicy
	// Number of replicas for each message
	ReplicationFactor *int32
	// Acknowledgment level required before considering message durable
	AckLevel *v2.AckLevel
	// Timeout for durability operations
	DurabilityTimeout *durationpb.Duration
	// Whether to use write-ahead logging
	WriteAheadLog *bool
	// Sync frequency for flushing to disk
	SyncInterval *durationpb.Duration
	// Whether to verify checksums on read
	VerifyChecksums *bool
}

func (b0 DurabilityConfig_builder) Build() *DurabilityConfig {
	m0 := &DurabilityConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Persistent != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Persistent = *b.Persistent
	}
	if b.FlushPolicy != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_FlushPolicy = *b.FlushPolicy
	}
	if b.ReplicationFactor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_ReplicationFactor = *b.ReplicationFactor
	}
	if b.AckLevel != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_AckLevel = *b.AckLevel
	}
	x.xxx_hidden_DurabilityTimeout = b.DurabilityTimeout
	if b.WriteAheadLog != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_WriteAheadLog = *b.WriteAheadLog
	}
	x.xxx_hidden_SyncInterval = b.SyncInterval
	if b.VerifyChecksums != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 8)
		x.xxx_hidden_VerifyChecksums = *b.VerifyChecksums
	}
	return m0
}

var File_queue_v2_durability_config_proto protoreflect.FileDescriptor

const file_queue_v2_durability_config_proto_rawDesc = "" +
	"\n" +
	" queue/v2/durability_config.proto\x12\bqueue.v2\x1a\x19common/v2/ack_level.proto\x1a\x1ccommon/v2/flush_policy.proto\x1a\x1egoogle/protobuf/duration.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xb4\x03\n" +
	"\x10DurabilityConfig\x12\x1e\n" +
	"\n" +
	"persistent\x18\x01 \x01(\bR\n" +
	"persistent\x129\n" +
	"\fflush_policy\x18\x02 \x01(\x0e2\x16.common.v2.FlushPolicyR\vflushPolicy\x126\n" +
	"\x12replication_factor\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x11replicationFactor\x120\n" +
	"\tack_level\x18\x04 \x01(\x0e2\x13.common.v2.AckLevelR\backLevel\x12H\n" +
	"\x12durability_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x11durabilityTimeout\x12&\n" +
	"\x0fwrite_ahead_log\x18\x06 \x01(\bR\rwriteAheadLog\x12>\n" +
	"\rsync_interval\x18\a \x01(\v2\x19.google.protobuf.DurationR\fsyncInterval\x12)\n" +
	"\x10verify_checksums\x18\b \x01(\bR\x0fverifyChecksumsB0Z&github.com/jdfalk/gcommon/pkg/queue/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_queue_v2_durability_config_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_queue_v2_durability_config_proto_goTypes = []any{
	(*DurabilityConfig)(nil),    // 0: queue.v2.DurabilityConfig
	(v2.FlushPolicy)(0),         // 1: common.v2.FlushPolicy
	(v2.AckLevel)(0),            // 2: common.v2.AckLevel
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_queue_v2_durability_config_proto_depIdxs = []int32{
	1, // 0: queue.v2.DurabilityConfig.flush_policy:type_name -> common.v2.FlushPolicy
	2, // 1: queue.v2.DurabilityConfig.ack_level:type_name -> common.v2.AckLevel
	3, // 2: queue.v2.DurabilityConfig.durability_timeout:type_name -> google.protobuf.Duration
	3, // 3: queue.v2.DurabilityConfig.sync_interval:type_name -> google.protobuf.Duration
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_queue_v2_durability_config_proto_init() }
func file_queue_v2_durability_config_proto_init() {
	if File_queue_v2_durability_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queue_v2_durability_config_proto_rawDesc), len(file_queue_v2_durability_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_queue_v2_durability_config_proto_goTypes,
		DependencyIndexes: file_queue_v2_durability_config_proto_depIdxs,
		MessageInfos:      file_queue_v2_durability_config_proto_msgTypes,
	}.Build()
	File_queue_v2_durability_config_proto = out.File
	file_queue_v2_durability_config_proto_goTypes = nil
	file_queue_v2_durability_config_proto_depIdxs = nil
}
