// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: queue/v2/queue_service.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_queue_v2_queue_service_proto protoreflect.FileDescriptor

const file_queue_v2_queue_service_proto_rawDesc = "" +
	"\n" +
	"\x1cqueue/v2/queue_service.proto\x12\bqueue.v2\x1a\x1equeue/v2/dequeue_request.proto\x1a\x1fqueue/v2/dequeue_response.proto\x1a\x1equeue/v2/enqueue_request.proto\x1a\x1fqueue/v2/enqueue_response.proto\x1a%queue/v2/get_queue_info_request.proto\x1a&queue/v2/get_queue_info_response.proto\x1a\x1bqueue/v2/peek_request.proto\x1a\x1cqueue/v2/peek_response.proto\x1a\x1equeue/v2/publish_request.proto\x1a\x1fqueue/v2/publish_response.proto\x1a queue/v2/subscribe_request.proto\x1a!queue/v2/subscribe_response.proto\x1a!google/protobuf/go_features.proto2\xa6\x03\n" +
	"\fQueueService\x12>\n" +
	"\aEnqueue\x12\x18.queue.v2.EnqueueRequest\x1a\x19.queue.v2.EnqueueResponse\x12>\n" +
	"\aDequeue\x12\x18.queue.v2.DequeueRequest\x1a\x19.queue.v2.DequeueResponse\x125\n" +
	"\x04Peek\x12\x15.queue.v2.PeekRequest\x1a\x16.queue.v2.PeekResponse\x12M\n" +
	"\fGetQueueInfo\x12\x1d.queue.v2.GetQueueInfoRequest\x1a\x1e.queue.v2.GetQueueInfoResponse\x12K\n" +
	"\tSubscribe\x12\x1f.queue.v2.QueueSubscribeRequest\x1a\x1b.queue.v2.SubscribeResponse0\x01\x12C\n" +
	"\aPublish\x12\x1d.queue.v2.QueuePublishRequest\x1a\x19.queue.v2.PublishResponseB0Z&github.com/jdfalk/gcommon/pkg/queue/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_queue_v2_queue_service_proto_goTypes = []any{
	(*EnqueueRequest)(nil),        // 0: queue.v2.EnqueueRequest
	(*DequeueRequest)(nil),        // 1: queue.v2.DequeueRequest
	(*PeekRequest)(nil),           // 2: queue.v2.PeekRequest
	(*GetQueueInfoRequest)(nil),   // 3: queue.v2.GetQueueInfoRequest
	(*QueueSubscribeRequest)(nil), // 4: queue.v2.QueueSubscribeRequest
	(*QueuePublishRequest)(nil),   // 5: queue.v2.QueuePublishRequest
	(*EnqueueResponse)(nil),       // 6: queue.v2.EnqueueResponse
	(*DequeueResponse)(nil),       // 7: queue.v2.DequeueResponse
	(*PeekResponse)(nil),          // 8: queue.v2.PeekResponse
	(*GetQueueInfoResponse)(nil),  // 9: queue.v2.GetQueueInfoResponse
	(*SubscribeResponse)(nil),     // 10: queue.v2.SubscribeResponse
	(*PublishResponse)(nil),       // 11: queue.v2.PublishResponse
}
var file_queue_v2_queue_service_proto_depIdxs = []int32{
	0,  // 0: queue.v2.QueueService.Enqueue:input_type -> queue.v2.EnqueueRequest
	1,  // 1: queue.v2.QueueService.Dequeue:input_type -> queue.v2.DequeueRequest
	2,  // 2: queue.v2.QueueService.Peek:input_type -> queue.v2.PeekRequest
	3,  // 3: queue.v2.QueueService.GetQueueInfo:input_type -> queue.v2.GetQueueInfoRequest
	4,  // 4: queue.v2.QueueService.Subscribe:input_type -> queue.v2.QueueSubscribeRequest
	5,  // 5: queue.v2.QueueService.Publish:input_type -> queue.v2.QueuePublishRequest
	6,  // 6: queue.v2.QueueService.Enqueue:output_type -> queue.v2.EnqueueResponse
	7,  // 7: queue.v2.QueueService.Dequeue:output_type -> queue.v2.DequeueResponse
	8,  // 8: queue.v2.QueueService.Peek:output_type -> queue.v2.PeekResponse
	9,  // 9: queue.v2.QueueService.GetQueueInfo:output_type -> queue.v2.GetQueueInfoResponse
	10, // 10: queue.v2.QueueService.Subscribe:output_type -> queue.v2.SubscribeResponse
	11, // 11: queue.v2.QueueService.Publish:output_type -> queue.v2.PublishResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_queue_v2_queue_service_proto_init() }
func file_queue_v2_queue_service_proto_init() {
	if File_queue_v2_queue_service_proto != nil {
		return
	}
	file_queue_v2_dequeue_request_proto_init()
	file_queue_v2_dequeue_response_proto_init()
	file_queue_v2_enqueue_request_proto_init()
	file_queue_v2_enqueue_response_proto_init()
	file_queue_v2_get_queue_info_request_proto_init()
	file_queue_v2_get_queue_info_response_proto_init()
	file_queue_v2_peek_request_proto_init()
	file_queue_v2_peek_response_proto_init()
	file_queue_v2_publish_request_proto_init()
	file_queue_v2_publish_response_proto_init()
	file_queue_v2_subscribe_request_proto_init()
	file_queue_v2_subscribe_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queue_v2_queue_service_proto_rawDesc), len(file_queue_v2_queue_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queue_v2_queue_service_proto_goTypes,
		DependencyIndexes: file_queue_v2_queue_service_proto_depIdxs,
	}.Build()
	File_queue_v2_queue_service_proto = out.File
	file_queue_v2_queue_service_proto_goTypes = nil
	file_queue_v2_queue_service_proto_depIdxs = nil
}
