// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: queue/v2/queue_admin_service.proto

package v2

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_queue_v2_queue_admin_service_proto protoreflect.FileDescriptor

const file_queue_v2_queue_admin_service_proto_rawDesc = "" +
	"\n" +
	"\"queue/v2/queue_admin_service.proto\x12\bqueue.v2\x1a#queue/v2/create_queue_request.proto\x1a$queue/v2/create_queue_response.proto\x1a#queue/v2/delete_topic_request.proto\x1a$queue/v2/delete_topic_response.proto\x1a\"queue/v2/pause_queue_request.proto\x1a#queue/v2/pause_queue_response.proto\x1a\x1cqueue/v2/purge_request.proto\x1a\x1dqueue/v2/purge_response.proto\x1a(queue/v2/reset_queue_stats_request.proto\x1a)queue/v2/reset_queue_stats_response.proto\x1a#queue/v2/resume_queue_request.proto\x1a$queue/v2/resume_queue_response.proto\x1a!google/protobuf/go_features.proto2\xd7\x03\n" +
	"\x11QueueAdminService\x12J\n" +
	"\vCreateQueue\x12\x1c.queue.v2.CreateQueueRequest\x1a\x1d.queue.v2.CreateQueueResponse\x12J\n" +
	"\vDeleteTopic\x12\x1c.queue.v2.DeleteTopicRequest\x1a\x1d.queue.v2.DeleteTopicResponse\x12G\n" +
	"\n" +
	"PauseQueue\x12\x1b.queue.v2.PauseQueueRequest\x1a\x1c.queue.v2.PauseQueueResponse\x12J\n" +
	"\vResumeQueue\x12\x1c.queue.v2.ResumeQueueRequest\x1a\x1d.queue.v2.ResumeQueueResponse\x12=\n" +
	"\n" +
	"PurgeQueue\x12\x16.queue.v2.PurgeRequest\x1a\x17.queue.v2.PurgeResponse\x12V\n" +
	"\x0fResetQueueStats\x12 .queue.v2.ResetQueueStatsRequest\x1a!.queue.v2.ResetQueueStatsResponseB,Z\"github.com/jdfalk/gcommon/queue/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_queue_v2_queue_admin_service_proto_goTypes = []any{
	(*CreateQueueRequest)(nil),      // 0: queue.v2.CreateQueueRequest
	(*DeleteTopicRequest)(nil),      // 1: queue.v2.DeleteTopicRequest
	(*PauseQueueRequest)(nil),       // 2: queue.v2.PauseQueueRequest
	(*ResumeQueueRequest)(nil),      // 3: queue.v2.ResumeQueueRequest
	(*PurgeRequest)(nil),            // 4: queue.v2.PurgeRequest
	(*ResetQueueStatsRequest)(nil),  // 5: queue.v2.ResetQueueStatsRequest
	(*CreateQueueResponse)(nil),     // 6: queue.v2.CreateQueueResponse
	(*DeleteTopicResponse)(nil),     // 7: queue.v2.DeleteTopicResponse
	(*PauseQueueResponse)(nil),      // 8: queue.v2.PauseQueueResponse
	(*ResumeQueueResponse)(nil),     // 9: queue.v2.ResumeQueueResponse
	(*PurgeResponse)(nil),           // 10: queue.v2.PurgeResponse
	(*ResetQueueStatsResponse)(nil), // 11: queue.v2.ResetQueueStatsResponse
}
var file_queue_v2_queue_admin_service_proto_depIdxs = []int32{
	0,  // 0: queue.v2.QueueAdminService.CreateQueue:input_type -> queue.v2.CreateQueueRequest
	1,  // 1: queue.v2.QueueAdminService.DeleteTopic:input_type -> queue.v2.DeleteTopicRequest
	2,  // 2: queue.v2.QueueAdminService.PauseQueue:input_type -> queue.v2.PauseQueueRequest
	3,  // 3: queue.v2.QueueAdminService.ResumeQueue:input_type -> queue.v2.ResumeQueueRequest
	4,  // 4: queue.v2.QueueAdminService.PurgeQueue:input_type -> queue.v2.PurgeRequest
	5,  // 5: queue.v2.QueueAdminService.ResetQueueStats:input_type -> queue.v2.ResetQueueStatsRequest
	6,  // 6: queue.v2.QueueAdminService.CreateQueue:output_type -> queue.v2.CreateQueueResponse
	7,  // 7: queue.v2.QueueAdminService.DeleteTopic:output_type -> queue.v2.DeleteTopicResponse
	8,  // 8: queue.v2.QueueAdminService.PauseQueue:output_type -> queue.v2.PauseQueueResponse
	9,  // 9: queue.v2.QueueAdminService.ResumeQueue:output_type -> queue.v2.ResumeQueueResponse
	10, // 10: queue.v2.QueueAdminService.PurgeQueue:output_type -> queue.v2.PurgeResponse
	11, // 11: queue.v2.QueueAdminService.ResetQueueStats:output_type -> queue.v2.ResetQueueStatsResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_queue_v2_queue_admin_service_proto_init() }
func file_queue_v2_queue_admin_service_proto_init() {
	if File_queue_v2_queue_admin_service_proto != nil {
		return
	}
	file_queue_v2_create_queue_request_proto_init()
	file_queue_v2_create_queue_response_proto_init()
	file_queue_v2_delete_topic_request_proto_init()
	file_queue_v2_delete_topic_response_proto_init()
	file_queue_v2_pause_queue_request_proto_init()
	file_queue_v2_pause_queue_response_proto_init()
	file_queue_v2_purge_request_proto_init()
	file_queue_v2_purge_response_proto_init()
	file_queue_v2_reset_queue_stats_request_proto_init()
	file_queue_v2_reset_queue_stats_response_proto_init()
	file_queue_v2_resume_queue_request_proto_init()
	file_queue_v2_resume_queue_response_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queue_v2_queue_admin_service_proto_rawDesc), len(file_queue_v2_queue_admin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queue_v2_queue_admin_service_proto_goTypes,
		DependencyIndexes: file_queue_v2_queue_admin_service_proto_depIdxs,
	}.Build()
	File_queue_v2_queue_admin_service_proto = out.File
	file_queue_v2_queue_admin_service_proto_goTypes = nil
	file_queue_v2_queue_admin_service_proto_depIdxs = nil
}
