// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: queue/v2/resume_queue_request.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v2 "github.com/jdfalk/gcommon/common/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// *
// Request to resume a paused queue.
// Restarts message processing for a previously paused queue.
type ResumeQueueRequest struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_QueueName              *string                `protobuf:"bytes,1,opt,name=queue_name,json=queueName"`
	xxx_hidden_Reason                 *string                `protobuf:"bytes,2,opt,name=reason"`
	xxx_hidden_Metadata               *v2.RequestMetadata    `protobuf:"bytes,3,opt,name=metadata"`
	xxx_hidden_PartitionIds           []int32                `protobuf:"varint,4,rep,packed,name=partition_ids,json=partitionIds"`
	xxx_hidden_ResumeFromLastPosition bool                   `protobuf:"varint,5,opt,name=resume_from_last_position,json=resumeFromLastPosition"`
	XXX_raceDetectHookData            protoimpl.RaceDetectHookData
	XXX_presence                      [1]uint32
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *ResumeQueueRequest) Reset() {
	*x = ResumeQueueRequest{}
	mi := &file_queue_v2_resume_queue_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResumeQueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResumeQueueRequest) ProtoMessage() {}

func (x *ResumeQueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v2_resume_queue_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResumeQueueRequest) GetQueueName() string {
	if x != nil {
		if x.xxx_hidden_QueueName != nil {
			return *x.xxx_hidden_QueueName
		}
		return ""
	}
	return ""
}

func (x *ResumeQueueRequest) GetReason() string {
	if x != nil {
		if x.xxx_hidden_Reason != nil {
			return *x.xxx_hidden_Reason
		}
		return ""
	}
	return ""
}

func (x *ResumeQueueRequest) GetMetadata() *v2.RequestMetadata {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *ResumeQueueRequest) GetPartitionIds() []int32 {
	if x != nil {
		return x.xxx_hidden_PartitionIds
	}
	return nil
}

func (x *ResumeQueueRequest) GetResumeFromLastPosition() bool {
	if x != nil {
		return x.xxx_hidden_ResumeFromLastPosition
	}
	return false
}

func (x *ResumeQueueRequest) SetQueueName(v string) {
	x.xxx_hidden_QueueName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *ResumeQueueRequest) SetReason(v string) {
	x.xxx_hidden_Reason = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *ResumeQueueRequest) SetMetadata(v *v2.RequestMetadata) {
	x.xxx_hidden_Metadata = v
}

func (x *ResumeQueueRequest) SetPartitionIds(v []int32) {
	x.xxx_hidden_PartitionIds = v
}

func (x *ResumeQueueRequest) SetResumeFromLastPosition(v bool) {
	x.xxx_hidden_ResumeFromLastPosition = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *ResumeQueueRequest) HasQueueName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ResumeQueueRequest) HasReason() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ResumeQueueRequest) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *ResumeQueueRequest) HasResumeFromLastPosition() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ResumeQueueRequest) ClearQueueName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_QueueName = nil
}

func (x *ResumeQueueRequest) ClearReason() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Reason = nil
}

func (x *ResumeQueueRequest) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *ResumeQueueRequest) ClearResumeFromLastPosition() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_ResumeFromLastPosition = false
}

type ResumeQueueRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the queue to resume
	QueueName *string
	// Reason for resuming the queue
	Reason *string
	// Request metadata for tracing and correlation
	Metadata *v2.RequestMetadata
	// Whether to resume specific partitions only
	PartitionIds []int32
	// Whether to start processing from where it left off
	ResumeFromLastPosition *bool
}

func (b0 ResumeQueueRequest_builder) Build() *ResumeQueueRequest {
	m0 := &ResumeQueueRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.QueueName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_QueueName = b.QueueName
	}
	if b.Reason != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Reason = b.Reason
	}
	x.xxx_hidden_Metadata = b.Metadata
	x.xxx_hidden_PartitionIds = b.PartitionIds
	if b.ResumeFromLastPosition != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_ResumeFromLastPosition = *b.ResumeFromLastPosition
	}
	return m0
}

var File_queue_v2_resume_queue_request_proto protoreflect.FileDescriptor

const file_queue_v2_resume_queue_request_proto_rawDesc = "" +
	"\n" +
	"#queue/v2/resume_queue_request.proto\x12\bqueue.v2\x1a common/v2/request_metadata.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xee\x01\n" +
	"\x12ResumeQueueRequest\x12(\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\tqueueName\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x126\n" +
	"\bmetadata\x18\x03 \x01(\v2\x1a.common.v2.RequestMetadataR\bmetadata\x12#\n" +
	"\rpartition_ids\x18\x04 \x03(\x05R\fpartitionIds\x129\n" +
	"\x19resume_from_last_position\x18\x05 \x01(\bR\x16resumeFromLastPositionB,Z\"github.com/jdfalk/gcommon/queue/v2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_queue_v2_resume_queue_request_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_queue_v2_resume_queue_request_proto_goTypes = []any{
	(*ResumeQueueRequest)(nil), // 0: queue.v2.ResumeQueueRequest
	(*v2.RequestMetadata)(nil), // 1: common.v2.RequestMetadata
}
var file_queue_v2_resume_queue_request_proto_depIdxs = []int32{
	1, // 0: queue.v2.ResumeQueueRequest.metadata:type_name -> common.v2.RequestMetadata
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_queue_v2_resume_queue_request_proto_init() }
func file_queue_v2_resume_queue_request_proto_init() {
	if File_queue_v2_resume_queue_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queue_v2_resume_queue_request_proto_rawDesc), len(file_queue_v2_resume_queue_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_queue_v2_resume_queue_request_proto_goTypes,
		DependencyIndexes: file_queue_v2_resume_queue_request_proto_depIdxs,
		MessageInfos:      file_queue_v2_resume_queue_request_proto_msgTypes,
	}.Build()
	File_queue_v2_resume_queue_request_proto = out.File
	file_queue_v2_resume_queue_request_proto_goTypes = nil
	file_queue_v2_resume_queue_request_proto_depIdxs = nil
}
