// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: webpb/v2/middleware_config.proto

package v2

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v2 "github.com/jdfalk/gcommon/pkg/commonpb/v2"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MiddlewareConfig message definition.
// MiddlewareConfig represents a single middleware's configuration.
type MiddlewareConfig struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        v2.MiddlewareType      `protobuf:"varint,1,opt,name=type,enum=common.v2.MiddlewareType"`
	xxx_hidden_Enabled     bool                   `protobuf:"varint,2,opt,name=enabled"`
	xxx_hidden_Priority    int32                  `protobuf:"varint,3,opt,name=priority"`
	xxx_hidden_Options     map[string]string      `protobuf:"bytes,4,rep,name=options" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *MiddlewareConfig) Reset() {
	*x = MiddlewareConfig{}
	mi := &file_webpb_v2_middleware_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MiddlewareConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MiddlewareConfig) ProtoMessage() {}

func (x *MiddlewareConfig) ProtoReflect() protoreflect.Message {
	mi := &file_webpb_v2_middleware_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MiddlewareConfig) GetType() v2.MiddlewareType {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 0) {
			return x.xxx_hidden_Type
		}
	}
	return v2.MiddlewareType(0)
}

func (x *MiddlewareConfig) GetEnabled() bool {
	if x != nil {
		return x.xxx_hidden_Enabled
	}
	return false
}

func (x *MiddlewareConfig) GetPriority() int32 {
	if x != nil {
		return x.xxx_hidden_Priority
	}
	return 0
}

func (x *MiddlewareConfig) GetOptions() map[string]string {
	if x != nil {
		return x.xxx_hidden_Options
	}
	return nil
}

func (x *MiddlewareConfig) SetType(v v2.MiddlewareType) {
	x.xxx_hidden_Type = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *MiddlewareConfig) SetEnabled(v bool) {
	x.xxx_hidden_Enabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *MiddlewareConfig) SetPriority(v int32) {
	x.xxx_hidden_Priority = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *MiddlewareConfig) SetOptions(v map[string]string) {
	x.xxx_hidden_Options = v
}

func (x *MiddlewareConfig) HasType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *MiddlewareConfig) HasEnabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *MiddlewareConfig) HasPriority() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *MiddlewareConfig) ClearType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Type = v2.MiddlewareType_MIDDLEWARE_TYPE_UNSPECIFIED
}

func (x *MiddlewareConfig) ClearEnabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Enabled = false
}

func (x *MiddlewareConfig) ClearPriority() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Priority = 0
}

type MiddlewareConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Middleware type
	Type *v2.MiddlewareType
	// Whether the middleware is enabled
	Enabled *bool
	// Execution priority (lower runs first)
	Priority *int32
	// Additional middleware options
	Options map[string]string
}

func (b0 MiddlewareConfig_builder) Build() *MiddlewareConfig {
	m0 := &MiddlewareConfig{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Type != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Type = *b.Type
	}
	if b.Enabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Enabled = *b.Enabled
	}
	if b.Priority != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Priority = *b.Priority
	}
	x.xxx_hidden_Options = b.Options
	return m0
}

var File_webpb_v2_middleware_config_proto protoreflect.FileDescriptor

const file_webpb_v2_middleware_config_proto_rawDesc = "" +
	"\n" +
	" webpb/v2/middleware_config.proto\x12\x06web.v2\x1a!commonpb/v2/middleware_type.proto\x1a!google/protobuf/go_features.proto\x1a\x1bbuf/validate/validate.proto\"\xfd\x01\n" +
	"\x10MiddlewareConfig\x12-\n" +
	"\x04type\x18\x01 \x01(\x0e2\x19.common.v2.MiddlewareTypeR\x04type\x12\x18\n" +
	"\aenabled\x18\x02 \x01(\bR\aenabled\x12#\n" +
	"\bpriority\x18\x03 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\bpriority\x12?\n" +
	"\aoptions\x18\x04 \x03(\v2%.web.v2.MiddlewareConfig.OptionsEntryR\aoptions\x1a:\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x8c\x01\n" +
	"\n" +
	"com.web.v2B\x15MiddlewareConfigProtoP\x01Z&github.com/jdfalk/gcommon/pkg/webpb/v2\xa2\x02\x03WXX\xaa\x02\x06Web.V2\xca\x02\x06Web\\V2\xe2\x02\x12Web\\V2\\GPBMetadata\xea\x02\aWeb::V2\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_webpb_v2_middleware_config_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_webpb_v2_middleware_config_proto_goTypes = []any{
	(*MiddlewareConfig)(nil), // 0: web.v2.MiddlewareConfig
	nil,                      // 1: web.v2.MiddlewareConfig.OptionsEntry
	(v2.MiddlewareType)(0),   // 2: common.v2.MiddlewareType
}
var file_webpb_v2_middleware_config_proto_depIdxs = []int32{
	2, // 0: web.v2.MiddlewareConfig.type:type_name -> common.v2.MiddlewareType
	1, // 1: web.v2.MiddlewareConfig.options:type_name -> web.v2.MiddlewareConfig.OptionsEntry
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_webpb_v2_middleware_config_proto_init() }
func file_webpb_v2_middleware_config_proto_init() {
	if File_webpb_v2_middleware_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webpb_v2_middleware_config_proto_rawDesc), len(file_webpb_v2_middleware_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webpb_v2_middleware_config_proto_goTypes,
		DependencyIndexes: file_webpb_v2_middleware_config_proto_depIdxs,
		MessageInfos:      file_webpb_v2_middleware_config_proto_msgTypes,
	}.Build()
	File_webpb_v2_middleware_config_proto = out.File
	file_webpb_v2_middleware_config_proto_goTypes = nil
	file_webpb_v2_middleware_config_proto_depIdxs = nil
}
